//! Equivalence oracle for the Cargo.lock block bound, which now searches the
//! trailing-table markers only up to the next `[[package]]` instead of to
//! EOF. The previous implementation is kept as
//! [`lock_block_end_unbounded`]; every consumer (`plan_cargo_lock`,
//! `next_lock_block`) is a function of the bound alone, so equality at every
//! body offset of every lock shape is equality of the rewriter.

use super::*;

/// Deterministic xorshift64* — no `rand` dev-dependency.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
    fn chance(&mut self, percent: u64) -> bool {
        self.next() % 100 < percent
    }
}

const CRATES_IO: &str = "registry+https://github.com/rust-lang/crates.io-index";

/// A lock in the given format: v1 (checksums in a trailing `[metadata]`,
/// full-id dependency references), or v3/v4 (inline checksums). Randomly
/// sprinkles the hostile shapes the bound must not be fooled by: marker
/// look-alikes inside strings, multi-byte names, blank-line runs between
/// blocks, `[[patch.unused]]` / `[patch.*]` trailers, and a missing final
/// newline.
fn synth_lock(rng: &mut Rng, blocks: usize, v1: bool) -> String {
    let mut out = String::new();
    out.push_str("# This file is automatically @generated by Cargo.\n");
    out.push_str("# It is not intended for manual editing.\n");
    if !v1 {
        out.push_str(if rng.chance(50) {
            "version = 4\n"
        } else {
            "version = 3\n"
        });
    }
    let mut metadata = Vec::new();
    for i in 0..blocks {
        out.push('\n');
        if rng.chance(10) {
            out.push('\n');
        }
        let name = match rng.below(5) {
            0 => format!("crate-é{i}"),
            1 => format!("crate_{i}"),
            _ => format!("c{i}"),
        };
        let version = format!("{}.{}.{}", rng.below(3), rng.below(20), rng.below(9));
        out.push_str(&format!(
            "[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n"
        ));
        let has_source = !rng.chance(15);
        if has_source {
            out.push_str(&format!("source = \"{CRATES_IO}\"\n"));
            let sum = format!("{:016x}{:016x}", rng.next(), rng.next());
            if v1 {
                metadata.push(format!(
                    "\"checksum {name} {version} ({CRATES_IO})\" = \"{sum}\""
                ));
            } else {
                out.push_str(&format!("checksum = \"{sum}\"\n"));
            }
        }
        if rng.chance(70) {
            out.push_str("dependencies = [\n");
            for d in 0..rng.below(5) {
                let dep = format!("c{}", (i + d + 1) % blocks.max(1));
                if v1 || rng.chance(20) {
                    out.push_str(&format!(" \"{dep} 0.1.0 ({CRATES_IO})\",\n"));
                } else {
                    out.push_str(&format!(" \"{dep}\",\n"));
                }
            }
            if rng.chance(10) {
                // Marker look-alikes that are NOT line-anchored.
                out.push_str(" \"x [metadata] [[package]] [patch.unused]\",\n");
            }
            out.push_str("]\n");
        }
    }
    if (v1 || rng.chance(20)) && (!metadata.is_empty() || rng.chance(50)) {
        out.push_str("\n[metadata]\n");
        for line in &metadata {
            out.push_str(line);
            out.push('\n');
        }
    }
    if rng.chance(30) {
        out.push_str("\n[[patch.unused]]\nname = \"unused\"\nversion = \"1.0.0\"\n");
    }
    if rng.chance(15) {
        out.push_str("\n[patch.crates-io]\n");
    }
    if rng.chance(20) {
        while out.ends_with('\n') {
            out.pop();
        }
    } else if rng.chance(20) {
        out.push_str("\n\n");
    }
    out
}

fn assert_bound_matches_at(content: &str, body_start: usize, what: &str) {
    assert_eq!(
        lock_block_end(content, body_start),
        lock_block_end_unbounded(content, body_start),
        "{what}: bound at body offset {body_start}"
    );
}

/// Every char boundary is a body offset: the bound must agree even where
/// the rewriter never asks, so no future caller can find a divergence.
fn assert_bound_matches_everywhere(content: &str, what: &str) {
    for (at, _) in content.char_indices() {
        assert_bound_matches_at(content, at, what);
    }
    assert_bound_matches_at(content, content.len(), what);
}

#[test]
fn bound_matches_unbounded_at_every_offset_of_random_locks() {
    let mut rng = Rng(0x9E37_79B9_7F4A_7C15);
    for case in 0..300 {
        let v1 = rng.chance(50);
        let blocks = rng.below(12);
        let lock = synth_lock(&mut rng, blocks, v1);
        assert_bound_matches_everywhere(&lock, &format!("case {case} (v1={v1})"));
        let crlf = lock.replace('\n', "\r\n");
        assert_bound_matches_everywhere(&crlf, &format!("case {case} crlf"));
    }
}

#[test]
fn bound_matches_unbounded_on_hand_written_edges() {
    for lock in [
        "",
        "\n",
        "[[package]]\n",
        "[[package]]\nname = \"a\"\nversion = \"1.0.0\"",
        "[[package]]\nname = \"a\"\nversion = \"1.0.0\"\n\n\n",
        // Trailing tables immediately after the last block, and before it.
        "[[package]]\nname = \"a\"\n[metadata]\n\"x\" = \"y\"\n",
        "[[package]]\nname = \"a\"\n\n[patch.crates-io]\n\n[[package]]\nname = \"b\"\n",
        "[[package]]\nname = \"a\"\n\n[[patch.unused]]\nname = \"u\"\n\n[metadata]\n",
        // A trailer before a later block (not cargo-shaped, still must agree).
        "[[package]]\nname = \"a\"\n\n[metadata]\n\n[[package]]\nname = \"b\"\n",
        // Look-alikes without the leading newline.
        "[[package]]\nname = \"a [metadata]\"\nx = \" [[package]]\"\n",
        "\n\n[[package]]\n\n\n[[package]]\n\n",
    ] {
        assert_bound_matches_everywhere(lock, &format!("{lock:?}"));
    }
}

/// The CG1 guard shape: ≥1k blocks, where the unbounded search was
/// quadratic. Checked at every block body (what `plan_cargo_lock` asks for)
/// and along the `next_lock_block` walk its dependents loop takes.
#[test]
fn bound_matches_unbounded_at_every_block_of_a_large_lock() {
    let mut rng = Rng(0xD1B5_4A32_D192_ED03);
    for v1 in [false, true] {
        let lock = synth_lock(&mut rng, 1_200, v1);
        let mut blocks = 0;
        for (at, _) in lock.match_indices("[[package]]\n") {
            assert_bound_matches_at(&lock, at + "[[package]]\n".len(), "large");
            blocks += 1;
        }
        assert!(blocks >= 1_000, "fixture keeps the ≥1k-block shape");
        // The walk `plan_cargo_lock` does for dependents visits the same
        // blocks with the same spans under either bound.
        let mut cursor = 0;
        while let Some((start, end)) = next_lock_block(&lock, cursor) {
            assert_eq!(
                end,
                lock_block_end_unbounded(&lock, start + "[[package]]\n".len()),
                "large (v1={v1}): block at {start}"
            );
            cursor = end;
        }
    }
}
