//! Seeded and hand-written Cargo.lock sweeps for the hosted splice, which
//! edits the byte spans of the lock's one parse ([`CargoLock::parse`] →
//! [`CargoLock::plan_hosted`]). Every plan is pinned per case by
//! `tests/equivalence/cargo_lock_*.golden`, blessed while the previous
//! line-grammar planner still ran beside it as an oracle (identical bytes
//! and edits wherever that grammar could read the lock).

use crate::formats::cargo::hosted::CargoLockPlan;
use crate::formats::cargo::CargoLock;
use crate::golden::Golden;
use crate::patch::redirect::FileEdit;
use crate::test_rng::Rng;

const CRATES_IO: &str = "registry+https://github.com/rust-lang/crates.io-index";

/// A lock in the given format: v1 (checksums in a trailing `[metadata]`,
/// full-id dependency references), or v3/v4 (inline checksums). Randomly
/// sprinkles the hostile shapes the bound must not be fooled by: marker
/// look-alikes inside strings, multi-byte names, blank-line runs between
/// blocks, `[[patch.unused]]` / `[patch.*]` trailers, and a missing final
/// newline.
fn synth_lock(rng: &mut Rng, blocks: usize, v1: bool) -> String {
    let mut out = String::new();
    out.push_str("# This file is automatically @generated by Cargo.\n");
    out.push_str("# It is not intended for manual editing.\n");
    if !v1 {
        out.push_str(if rng.chance(50) {
            "version = 4\n"
        } else {
            "version = 3\n"
        });
    }
    let mut metadata = Vec::new();
    for i in 0..blocks {
        out.push('\n');
        if rng.chance(10) {
            out.push('\n');
        }
        let name = match rng.below(5) {
            0 => format!("crate-é{i}"),
            1 => format!("crate_{i}"),
            _ => format!("c{i}"),
        };
        let version = format!("{}.{}.{}", rng.below(3), rng.below(20), rng.below(9));
        out.push_str(&format!(
            "[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n"
        ));
        let has_source = !rng.chance(15);
        if has_source {
            out.push_str(&format!("source = \"{CRATES_IO}\"\n"));
            let sum = format!("{:016x}{:016x}", rng.next(), rng.next());
            if v1 {
                metadata.push(format!(
                    "\"checksum {name} {version} ({CRATES_IO})\" = \"{sum}\""
                ));
            } else {
                out.push_str(&format!("checksum = \"{sum}\"\n"));
            }
        }
        if rng.chance(70) {
            out.push_str("dependencies = [\n");
            for d in 0..rng.below(5) {
                let dep = format!("c{}", (i + d + 1) % blocks.max(1));
                if v1 || rng.chance(20) {
                    out.push_str(&format!(" \"{dep} 0.1.0 ({CRATES_IO})\",\n"));
                } else {
                    out.push_str(&format!(" \"{dep}\",\n"));
                }
            }
            if rng.chance(10) {
                // Marker look-alikes that are NOT line-anchored.
                out.push_str(" \"x [metadata] [[package]] [patch.unused]\",\n");
            }
            out.push_str("]\n");
        }
    }
    if (v1 || rng.chance(20)) && (!metadata.is_empty() || rng.chance(50)) {
        out.push_str("\n[metadata]\n");
        for line in &metadata {
            out.push_str(line);
            out.push('\n');
        }
    }
    if rng.chance(30) {
        out.push_str("\n[[patch.unused]]\nname = \"unused\"\nversion = \"1.0.0\"\n");
    }
    if rng.chance(15) {
        out.push_str("\n[patch.crates-io]\n");
    }
    if rng.chance(20) {
        while out.ends_with('\n') {
            out.pop();
        }
    } else if rng.chance(20) {
        out.push_str("\n\n");
    }
    out
}

const INDEX: &str = "sparse+https://socket.example/cargo/index/";

fn plan_new(lock: &str, name: &str, version: &str, cksum: &str) -> CargoLockPlan {
    CargoLock::parse(lock)
        .expect("synthesized locks parse")
        .plan_hosted(lock, name, version, INDEX, cksum)
}

/// A plan as comparable data.
fn shape(plan: &CargoLockPlan) -> (String, Option<String>, Vec<FileEdit>) {
    match plan {
        CargoLockPlan::Rewritten { content, edits } => {
            ("rewritten".into(), Some(content.clone()), edits.clone())
        }
        CargoLockPlan::AlreadyRedirected => ("already".into(), None, Vec::new()),
        CargoLockPlan::NotFound => ("not-found".into(), None, Vec::new()),
        CargoLockPlan::Ambiguous => ("ambiguous".into(), None, Vec::new()),
    }
}

fn check(g: &mut Golden, lock: &str, name: &str, version: &str, cksum: &str) -> Option<String> {
    let new = shape(&plan_new(lock, name, version, cksum));
    g.next(&(lock, name, version, cksum), &new);
    new.1
}

/// `(name, version)` of every `[[package]]` the lock holds, in order.
fn targets(lock: &str) -> Vec<(String, String)> {
    CargoLock::parse(lock)
        .expect("synthesized locks parse")
        .packages()
        .iter()
        .map(|p| (p.name.clone(), p.version.clone()))
        .collect()
}

/// Every package of `lock`, then a second package planned over the first's
/// output and a re-run of the first (the no-op path), and an absent package.
fn sweep_lock(g: &mut Golden, lock: &str, rng: &mut Rng) {
    let all = targets(lock);
    for (name, version) in &all {
        let cksum = format!("{:016x}{:016x}", rng.next(), rng.next());
        let Some(once) = check(g, lock, name, version, &cksum) else {
            continue;
        };
        check(g, &once, name, version, &cksum);
        if let Some((other, other_version)) = all.get(rng.below(all.len())) {
            check(g, &once, other, other_version, "00ff");
        }
    }
    check(g, lock, "absent-crate", "9.9.9", "00");
}

#[test]
fn span_splice_matches_golden_on_random_locks() {
    let mut g = Golden::new(
        "cargo_lock_random",
        "One package of a seeded Cargo.lock, planned for the hosted index.",
    )
    .chunked(20);
    let mut rng = Rng(0x9E37_79B9_7F4A_7C15);
    for _ in 0..300 {
        let v1 = rng.chance(50);
        let blocks = rng.below(12);
        let lock = synth_lock(&mut rng, blocks, v1);
        sweep_lock(&mut g, &lock, &mut rng);
    }
    g.finish();
}

/// Hand-written shapes the generator does not produce: multi-source twins
/// (one at the target index, and none), a v1 `[root]` table, a v1 block with
/// no source, a source ending the text, and blocks with neither line.
#[test]
fn span_splice_matches_golden_on_hand_written_locks() {
    let crates_io = CRATES_IO;
    let twins_ours = format!(
        "version = 3\n\n[[package]]\nname = \"t\"\nversion = \"1.0.0\"\nsource = \"{crates_io}\"\nchecksum = \"aa\"\n\n[[package]]\nname = \"t\"\nversion = \"1.0.0\"\nsource = \"{INDEX}\"\nchecksum = \"bb\"\n"
    );
    let twins_neither = twins_ours.replace(INDEX, "registry+https://other.example/index");
    let v1_root = format!(
        "[root]\nname = \"app\"\nversion = \"0.1.0\"\ndependencies = [\n \"d 1.0.0 ({crates_io})\",\n]\n\n[[package]]\nname = \"d\"\nversion = \"1.0.0\"\nsource = \"{crates_io}\"\n\n[[package]]\nname = \"u\"\nversion = \"2.0.0\"\nsource = \"{crates_io}\"\ndependencies = [\n \"d 1.0.0 ({crates_io})\",\n]\n\n[metadata]\n\"checksum d 1.0.0 ({crates_io})\" = \"cc\"\n\"checksum u 2.0.0 ({crates_io})\" = \"dd\"\n"
    );
    let sourceless_v1 = "[[package]]\nname = \"s\"\nversion = \"1.0.0\"\n\n[metadata]\n\"checksum s 1.0.0 (registry+x)\" = \"ee\"\n".to_string();
    let source_at_eof =
        format!("[[package]]\nname = \"e\"\nversion = \"1.0.0\"\nsource = \"{crates_io}\"");
    let bare = "version = 3\n\n[[package]]\nname = \"b\"\nversion = \"1.0.0\"\n\n[[package]]\nname = \"c\"\nversion = \"1.0.0\"\n".to_string();
    let mut g = Golden::new(
        "cargo_lock_hand_written",
        "One package of a hand-written Cargo.lock shape, planned for the hosted index.",
    );
    let mut rng = Rng(0xD1B5_4A32_D192_ED03);
    for (_what, lock) in [
        ("twins, one ours", twins_ours),
        ("twins, neither ours", twins_neither),
        ("v1 [root]", v1_root),
        ("v1 sourceless", sourceless_v1),
        ("source at EOF", source_at_eof),
        ("bare blocks", bare),
    ] {
        sweep_lock(&mut g, &lock, &mut rng);
    }
    g.finish();
}

/// The large-lock shape: ≥1k blocks, both formats, a sample of targets.
#[test]
fn span_splice_matches_golden_on_a_large_lock() {
    let mut g = Golden::new(
        "cargo_lock_large",
        "One sampled package of a seeded ≥1k-block Cargo.lock, planned for the hosted index.",
    );
    let mut rng = Rng(0x2545_F491_4F6C_DD1D);
    for v1 in [false, true] {
        let lock = synth_lock(&mut rng, 1_200, v1);
        let all = targets(&lock);
        assert!(all.len() >= 1_000, "fixture keeps the ≥1k-block shape");
        for (name, version) in all.iter().step_by(97) {
            check(&mut g, &lock, name, version, "abcd");
        }
    }
    g.finish();
}
