//! Hosted (URL-source) redirects for `poetry.lock`, every lock generation
//! Poetry 1.0+ has written. Poetry 0.12 (format `"0"`) ignores URL sources and
//! is refused by the shared rewriter. See `crate::utils::poetry_lock`.

use std::collections::BTreeMap;

use serde_json::Value;
use toml_edit::DocumentMut;

use super::{DepOverride, FileEdit, RewriteResult, RewriteWarning};
use crate::utils::poetry_lock::{
    generated_by_version, lock_version, poetry_lock_edits, rewrite_poetry_lock,
};

/// Whether the lock was written by a Poetry release older than 1.4. Those
/// installers neither verify hashes for local wheels nor replace an
/// already-installed package at the same version, so a warm virtualenv keeps
/// serving the upstream bytes after the redirect. Formats `0`/`1.0`/`1.1` are
/// only written by such releases; lock `2.0` is written by 1.3 through 1.8, so
/// the `@generated by Poetry X.Y.Z` header (present from 1.4) decides there.
fn pre_1_4_writer(lock_text: &str) -> Option<&'static str> {
    let lock = lock_text.parse::<DocumentMut>().ok()?;
    match lock_version(&lock) {
        Ok("0") => Some("0"),
        Ok("1.0") => Some("1.0"),
        Ok("1.1") => Some("1.1"),
        Ok("2.0") if !matches!(generated_by_version(lock_text), Some(v) if v >= (1, 4)) => {
            Some("2.0")
        }
        _ => None,
    }
}

pub(super) fn rewrite_poetry(
    files: &BTreeMap<String, String>,
    overrides: &[DepOverride],
    result: &mut RewriteResult,
) {
    let locks: Vec<(&String, &String)> = files
        .iter()
        .filter(|(path, _)| path.as_str() == "poetry.lock" || path.ends_with("/poetry.lock"))
        .collect();
    if locks.is_empty() {
        return;
    }
    // Intake gate ONCE per dep, not once per lock file (uv parity).
    let mut usable: Vec<(&DepOverride, &str)> = Vec::new();
    for dep in overrides.iter().filter(|dep| dep.ecosystem == "pypi") {
        result.python_lock_uuids.insert(dep.patch_uuid.clone());
        match dep.integrity.sha256.as_deref() {
            Some(sha256) => usable.push((dep, sha256)),
            None => result.warnings.push(RewriteWarning {
                code: "redirect_poetry_missing_sha256".into(),
                detail: format!("{} has no SHA-256 integrity", dep.name),
            }),
        }
    }
    for (path, original) in locks {
        let mut content = original.clone();
        let mut stale_warned = false;
        for &(dep, sha256) in &usable {
            let filename = dep.artifact_url.rsplit('/').next().unwrap_or("");
            match rewrite_poetry_lock(
                &content,
                &dep.name,
                &dep.version,
                "url",
                &dep.artifact_url,
                filename,
                sha256,
            ) {
                Ok(Some(rewritten)) if rewritten != content => {
                    match poetry_lock_edits(&content, &rewritten, &dep.name) {
                        Ok(edits) => {
                            for (original, new) in edits {
                                result.edits.push(FileEdit {
                                    path: path.clone(),
                                    kind: "redirect_poetry_lock_package".into(),
                                    action: "rewritten".into(),
                                    key: Some(format!("{}@{}", dep.name, dep.version)),
                                    original: Some(Value::String(original)),
                                    new: Some(Value::String(new)),
                                });
                            }
                        }
                        Err(detail) => {
                            result.refused_python_lock_uuids.insert(dep.patch_uuid.clone());
                            result.warnings.push(RewriteWarning {
                                code: "redirect_poetry_lock_unsupported".into(),
                                detail: format!("{path}: {detail}"),
                            });
                            continue;
                        }
                    }
                    result.confirmed_python_lock_uuids.insert(dep.patch_uuid.clone());
                    content = rewritten;
                    if !stale_warned {
                        if let Some(format) = pre_1_4_writer(&content) {
                            stale_warned = true;
                            // Poetry 1.0 installs url sources through pip, which reads
                            // the hash from the URL fragment; pip 22.3–23.0 take the
                            // rest of the fragment (`&#egg=<name>`, appended by Poetry)
                            // as part of the digest and refuse the install (measured;
                            // pip <= 22.2 and >= 23.1 install and verify).
                            let pip_note = if format == "1.0" {
                                " Poetry 1.0 installs through pip: pip 22.3–23.0 misparse the \
                                 hash fragment and refuse the install (fail-closed) — use pip \
                                 <= 22.2 or >= 23.1 in the virtualenv."
                            } else {
                                ""
                            };
                            result.warnings.push(RewriteWarning {
                                code: "redirect_poetry_stale_install_risk".into(),
                                detail: format!(
                                    "{path} was written by Poetry < 1.4, which does not replace \
                                     an already-installed package at the same version: an \
                                     existing virtualenv keeps the upstream {} until it is \
                                     recreated (or the package is `pip uninstall`ed) before \
                                     `poetry install`; fresh installs pick up the patched \
                                     wheel.{pip_note}",
                                    dep.name
                                ),
                            });
                        }
                    }
                }
                // Already redirected to this artifact (idempotent re-scan).
                Ok(Some(_)) => {
                    result.confirmed_python_lock_uuids.insert(dep.patch_uuid.clone());
                }
                Ok(None) => result.warnings.push(RewriteWarning {
                    code: "redirect_poetry_entry_not_found".into(),
                    detail: format!("no {path} entry for {}@{}", dep.name, dep.version),
                }),
                Err(detail) => {
                    result.refused_python_lock_uuids.insert(dep.patch_uuid.clone());
                    result.warnings.push(RewriteWarning {
                        code: "redirect_poetry_lock_unsupported".into(),
                        detail: format!("{path}: {detail}"),
                    });
                }
            }
        }
        if content != *original {
            result.files.insert(path.clone(), content);
        }
    }
}
