//! The vendor ledger's version-2 snapshot table (see
//! `socket_patch_core::vendor::ledger_snapshots`): whole-file wiring
//! snapshots are stored once per file plus one small edit per package, and
//! every older ledger keeps reverting byte for byte.
//!
//! * `legacy_ledgers_revert_byte_for_byte` replays ledgers the integrated
//!   base binary wrote (version 1, inline whole-file snapshots — checked in
//!   under `tests/fixtures/legacy-ledgers/<eco>/`, regenerated by the
//!   ignored `generate_legacy_ledger_fixtures` below) through this binary's
//!   `vendor --revert`, for every ecosystem, and requires exactly the tree
//!   the base binary's own revert left.
//! * `new_ledgers_compact_whole_file_snapshots_and_revert` vendors each
//!   ecosystem with this binary: the ledgers that hold whole-file snapshots
//!   (maven, nuget, pylock) come out as version 2 and much smaller than the
//!   inline form, the others stay version 1, and the revert is exact.

#[path = "vendor_ecosystem_fixtures/mod.rs"]
mod fx;

use std::path::{Path, PathBuf};

use fx::{masked_tree, tree, Fixture};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/legacy-ledgers")
}

/// The files of `after` that are new or changed relative to `before`,
/// minus the artifacts under `.socket/vendor/<eco>/` (the ledger and the
/// project's wiring files are what a legacy checkout carries forward; the
/// revert deletes the artifacts either way).
fn wiring_delta(
    before: &[(String, Vec<u8>)],
    after: &[(String, Vec<u8>)],
) -> Vec<(String, Vec<u8>)> {
    after
        .iter()
        .filter(|entry| !before.contains(entry))
        .filter(|(rel, _)| {
            !rel.starts_with(".socket/vendor/") || rel == ".socket/vendor/state.json"
        })
        .cloned()
        .collect()
}

fn write_tree(dir: &Path, files: &[(String, Vec<u8>)]) {
    for (rel, bytes) in files {
        let path = dir.join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, bytes).unwrap();
    }
}

fn read_tree(dir: &Path) -> Vec<(String, Vec<u8>)> {
    if !dir.exists() {
        return Vec::new();
    }
    tree(dir)
}

/// Regenerate `tests/fixtures/legacy-ledgers/` with the binary named by
/// `SOCKET_PATCH_LEGACY_BIN` (the integrated base, before the version-2
/// ledger). For each ecosystem it stores the wiring files and the ledger
/// that binary's `vendor` wrote (`wired/`), and the wiring files its
/// `vendor --revert` then left (`reverted/`).
#[test]
#[ignore = "regenerates checked-in fixtures; needs SOCKET_PATCH_LEGACY_BIN"]
fn generate_legacy_ledger_fixtures() {
    let bin = std::env::var("SOCKET_PATCH_LEGACY_BIN").expect("SOCKET_PATCH_LEGACY_BIN");
    for eco in fx::ALL {
        let f = Fixture::new(eco);
        let pristine = tree(&f.root);
        let (code, stdout, stderr) = f.run_bin(&bin, &["vendor", "--json", "--offline"], &[]);
        assert_eq!(code, 0, "{eco}: {stdout}\n{stderr}");
        let wired = wiring_delta(&pristine, &tree(&f.root));
        let (code, stdout, stderr) =
            f.run_bin(&bin, &["vendor", "--json", "--offline", "--revert"], &[]);
        assert_eq!(code, 0, "{eco} revert: {stdout}\n{stderr}");
        let reverted = wiring_delta(&pristine, &tree(&f.root));
        let out = fixtures_dir().join(eco);
        let _ = std::fs::remove_dir_all(&out);
        write_tree(&out.join("wired"), &wired);
        write_tree(&out.join("reverted"), &reverted);
    }
}

#[test]
fn legacy_ledgers_revert_byte_for_byte() {
    for eco in fx::ALL {
        let dir = fixtures_dir().join(eco);
        let wired = read_tree(&dir.join("wired"));
        let legacy_ledger = wired
            .iter()
            .find(|(rel, _)| rel == ".socket/vendor/state.json")
            .unwrap_or_else(|| panic!("{eco}: fixture carries the legacy ledger"));
        let ledger: serde_json::Value = serde_json::from_slice(&legacy_ledger.1).unwrap();
        assert_eq!(ledger["version"], 1, "{eco}: a version-1 ledger");
        assert!(ledger.get("snapshots").is_none(), "{eco}");

        let f = Fixture::new(eco);
        let pristine = tree(&f.root);
        write_tree(&f.root, &wired);
        let (code, stdout, stderr) = f.vendor(&["--revert"], &[]);
        assert_eq!(code, 0, "{eco}: {stdout}\n{stderr}");
        let mut expected = pristine
            .iter()
            .filter(|(rel, _)| {
                !read_tree(&dir.join("reverted"))
                    .iter()
                    .any(|(r, _)| r == rel)
            })
            .cloned()
            .collect::<Vec<_>>();
        expected.extend(read_tree(&dir.join("reverted")));
        expected.sort();
        assert_eq!(
            tree(&f.root),
            expected,
            "{eco}: this binary reverts a legacy ledger to exactly the base binary's result"
        );
        if !["pnpm", "nuget"].contains(eco) {
            assert_eq!(tree(&f.root), pristine, "{eco}: byte-exact restore");
        }
    }
}

#[test]
fn new_ledgers_compact_whole_file_snapshots_and_revert() {
    for eco in fx::ALL {
        let f = Fixture::new(eco);
        let pristine = masked_tree(&f.root);
        let (code, stdout, stderr) = f.vendor(&[], &[]);
        assert_eq!(code, 0, "{eco}: {stdout}\n{stderr}");
        let bytes = std::fs::read(f.root.join(".socket/vendor/state.json")).unwrap();
        let ledger: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        let whole_file = ["maven", "nuget", "pylock"].contains(eco);
        assert_eq!(
            ledger["version"],
            if whole_file { 2 } else { 1 },
            "{eco}: {ledger:#}"
        );
        if whole_file {
            let legacy: serde_json::Value = serde_json::from_slice(
                &std::fs::read(
                    fixtures_dir()
                        .join(eco)
                        .join("wired/.socket/vendor/state.json"),
                )
                .unwrap(),
            )
            .unwrap();
            // The whole-file snapshot bytes the base binary stored inline…
            let inline: usize = legacy["entries"]
                .as_object()
                .unwrap()
                .values()
                .flat_map(|e| e["wiring"].as_array().unwrap().iter())
                .flat_map(|r| [&r["original"], &r["new"]])
                .filter_map(|v| v.as_str())
                .filter(|t| t.len() >= 1024)
                .map(str::len)
                .sum();
            // …against the table this binary stores them in.
            let table = serde_json::to_vec(&ledger["snapshots"]).unwrap().len();
            assert!(
                table * 2 < inline,
                "{eco}: the snapshot table ({table} bytes) is well under the inline \
                 snapshots ({inline} bytes)"
            );
            let table = ledger["snapshots"].as_object().unwrap();
            assert!(
                table.values().filter(|e| e.get("text").is_some()).count() <= 2,
                "{eco}: at most one full text per snapshotted file: {ledger:#}"
            );
        }

        let (code, stdout, stderr) = f.vendor(&["--revert"], &[]);
        assert_eq!(code, 0, "{eco} revert: {stdout}\n{stderr}");
        if !["pnpm", "nuget"].contains(eco) {
            assert_eq!(masked_tree(&f.root), pristine, "{eco}: byte-exact restore");
        } else {
            let reverted = read_tree(&fixtures_dir().join(eco).join("reverted"));
            for (rel, bytes) in reverted {
                assert_eq!(
                    std::fs::read(f.root.join(&rel)).unwrap(),
                    bytes,
                    "{eco}: {rel} reverts exactly as the base binary reverted it"
                );
            }
        }
    }
}

/// Against the integrated base: for every ecosystem this binary wires
/// exactly the files the base binary wired (the checked-in legacy
/// fixtures), and its ledger — whatever its on-disk version — loads to the
/// same entries the base's version-1 ledger loads to.
#[tokio::test]
async fn this_binary_wires_what_the_base_binary_wired() {
    for eco in fx::ALL {
        let base_wired = read_tree(&fixtures_dir().join(eco).join("wired"));
        let f = Fixture::new(eco);
        let pristine = tree(&f.root);
        let (code, stdout, stderr) = f.vendor(&[], &[]);
        assert_eq!(code, 0, "{eco}: {stdout}\n{stderr}");
        let wired = wiring_delta(&pristine, &tree(&f.root));
        let strip = |t: &[(String, Vec<u8>)]| -> Vec<(String, Vec<u8>)> {
            t.iter()
                .filter(|(rel, _)| rel != ".socket/vendor/state.json")
                .cloned()
                .collect()
        };
        assert_eq!(
            strip(&wired),
            strip(&base_wired),
            "{eco}: the same wiring files, byte for byte"
        );
        let base_dir = tempfile::tempdir().unwrap();
        write_tree(base_dir.path(), &base_wired);
        let base_state = socket_patch_core::vendor::load_state(base_dir.path())
            .await
            .unwrap();
        let state = socket_patch_core::vendor::load_state(&f.root)
            .await
            .unwrap();
        assert_eq!(
            state.entries, base_state.entries,
            "{eco}: the same ledger entries"
        );
    }
}
