//! The vendor ledger's version-2 snapshot edits (see
//! `socket_patch_core::vendor::ledger_snapshots`): a whole-file wiring
//! record's `new` is stored as a small edit of the same record's
//! `original`, and every older ledger keeps reverting byte for byte.
//!
//! * `legacy_ledgers_revert_byte_for_byte` replays ledgers the integrated
//!   base binary wrote (version 1, inline whole-file snapshots — checked in
//!   under `tests/fixtures/legacy-ledgers/<eco>/`, regenerated by the
//!   ignored `generate_legacy_ledger_fixtures` below) through this binary's
//!   `vendor --revert`, for every ecosystem, and requires exactly the tree
//!   the base binary's own revert left.
//! * `new_ledgers_compact_whole_file_snapshots_and_revert` vendors each
//!   ecosystem with this binary: the ledgers that hold whole-file snapshots
//!   (maven, nuget, pylock) come out as version 2 with every `new` an edit
//!   far smaller than the inline text, the others stay version 1, and the
//!   revert is exact.

#[path = "vendor_ecosystem_fixtures/mod.rs"]
mod fx;

use std::path::{Path, PathBuf};

use fx::{masked_tree, tree, Fixture};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/legacy-ledgers")
}

/// The files of `after` that are new or changed relative to `before`,
/// minus the artifacts under `.socket/vendor/<eco>/` (the ledger and the
/// project's wiring files are what a legacy checkout carries forward; the
/// revert deletes the artifacts either way).
fn wiring_delta(
    before: &[(String, Vec<u8>)],
    after: &[(String, Vec<u8>)],
) -> Vec<(String, Vec<u8>)> {
    after
        .iter()
        .filter(|entry| !before.contains(entry))
        .filter(|(rel, _)| {
            !rel.starts_with(".socket/vendor/") || rel == ".socket/vendor/state.json"
        })
        .cloned()
        .collect()
}

fn write_tree(dir: &Path, files: &[(String, Vec<u8>)]) {
    for (rel, bytes) in files {
        let path = dir.join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, bytes).unwrap();
    }
}

fn read_tree(dir: &Path) -> Vec<(String, Vec<u8>)> {
    if !dir.exists() {
        return Vec::new();
    }
    tree(dir)
}

/// Regenerate `tests/fixtures/legacy-ledgers/` with the binary named by
/// `SOCKET_PATCH_LEGACY_BIN` (the integrated base, before the version-2
/// ledger). For each ecosystem it stores the wiring files and the ledger
/// that binary's `vendor` wrote (`wired/`), and the wiring files its
/// `vendor --revert` then left (`reverted/`).
#[test]
#[ignore = "regenerates checked-in fixtures; needs SOCKET_PATCH_LEGACY_BIN"]
fn generate_legacy_ledger_fixtures() {
    let bin = std::env::var("SOCKET_PATCH_LEGACY_BIN").expect("SOCKET_PATCH_LEGACY_BIN");
    for eco in fx::ALL {
        let f = Fixture::new(eco);
        let pristine = tree(&f.root);
        let (code, stdout, stderr) = f.run_bin(&bin, &["vendor", "--json", "--offline"], &[]);
        assert_eq!(code, 0, "{eco}: {stdout}\n{stderr}");
        let wired = wiring_delta(&pristine, &tree(&f.root));
        let (code, stdout, stderr) =
            f.run_bin(&bin, &["vendor", "--json", "--offline", "--revert"], &[]);
        assert_eq!(code, 0, "{eco} revert: {stdout}\n{stderr}");
        let reverted = wiring_delta(&pristine, &tree(&f.root));
        let out = fixtures_dir().join(eco);
        let _ = std::fs::remove_dir_all(&out);
        write_tree(&out.join("wired"), &wired);
        write_tree(&out.join("reverted"), &reverted);
    }
}

#[test]
fn legacy_ledgers_revert_byte_for_byte() {
    for eco in fx::ALL {
        let dir = fixtures_dir().join(eco);
        let wired = read_tree(&dir.join("wired"));
        let legacy_ledger = wired
            .iter()
            .find(|(rel, _)| rel == ".socket/vendor/state.json")
            .unwrap_or_else(|| panic!("{eco}: fixture carries the legacy ledger"));
        let ledger: serde_json::Value = serde_json::from_slice(&legacy_ledger.1).unwrap();
        assert_eq!(ledger["version"], 1, "{eco}: a version-1 ledger");
        assert!(ledger.get("snapshots").is_none(), "{eco}");

        let f = Fixture::new(eco);
        let pristine = tree(&f.root);
        write_tree(&f.root, &wired);
        let (code, stdout, stderr) = f.vendor(&["--revert"], &[]);
        assert_eq!(code, 0, "{eco}: {stdout}\n{stderr}");
        let mut expected = pristine
            .iter()
            .filter(|(rel, _)| {
                !read_tree(&dir.join("reverted"))
                    .iter()
                    .any(|(r, _)| r == rel)
            })
            .cloned()
            .collect::<Vec<_>>();
        expected.extend(read_tree(&dir.join("reverted")));
        expected.sort();
        assert_eq!(
            tree(&f.root),
            expected,
            "{eco}: this binary reverts a legacy ledger to exactly the base binary's result"
        );
        if !["pnpm", "nuget"].contains(eco) {
            assert_eq!(tree(&f.root), pristine, "{eco}: byte-exact restore");
        }
    }
}

#[test]
fn new_ledgers_compact_whole_file_snapshots_and_revert() {
    for eco in fx::ALL {
        let f = Fixture::new(eco);
        let pristine = masked_tree(&f.root);
        let (code, stdout, stderr) = f.vendor(&[], &[]);
        assert_eq!(code, 0, "{eco}: {stdout}\n{stderr}");
        let bytes = std::fs::read(f.root.join(".socket/vendor/state.json")).unwrap();
        let ledger: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        // Maven vendors through the JVM planner (#973), whose fragment
        // records hold no whole-file snapshot.
        let whole_file = ["nuget", "pylock"].contains(eco);
        assert_eq!(
            ledger["version"],
            if whole_file { 2 } else { 1 },
            "{eco}: {ledger:#}"
        );
        if whole_file {
            let legacy: serde_json::Value = serde_json::from_slice(
                &std::fs::read(
                    fixtures_dir()
                        .join(eco)
                        .join("wired/.socket/vendor/state.json"),
                )
                .unwrap(),
            )
            .unwrap();
            // The whole-file `new` texts the base binary stored inline…
            let inline: usize = legacy["entries"]
                .as_object()
                .unwrap()
                .values()
                .flat_map(|e| e["wiring"].as_array().unwrap().iter())
                .filter_map(|r| r["new"].as_str())
                .filter(|t| t.len() >= 1024)
                .map(str::len)
                .sum();
            // …against the edits this binary stores them as. Every record
            // stays self-contained: its `original` is still plain text and
            // nothing lives outside the entries (an older binary re-saving
            // the ledger drops unknown top-level fields).
            assert!(ledger.get("snapshots").is_none(), "{eco}: {ledger:#}");
            let records: Vec<&serde_json::Value> = ledger["entries"]
                .as_object()
                .unwrap()
                .values()
                .flat_map(|e| e["wiring"].as_array().unwrap().iter())
                .collect();
            assert!(
                records
                    .iter()
                    .all(|r| r["original"].get("snapshot").is_none()),
                "{eco}: an original is never an edit: {ledger:#}"
            );
            let stored: usize = records
                .iter()
                .map(|r| &r["new"])
                .filter(|v| v.get("snapshot").is_some())
                .map(|v| serde_json::to_vec(v).unwrap().len())
                .sum();
            assert!(stored > 0, "{eco}: {ledger:#}");
            assert!(
                stored * 4 < inline,
                "{eco}: the edits ({stored} bytes) are well under the inline \
                 `new` texts ({inline} bytes)"
            );
        }

        let (code, stdout, stderr) = f.vendor(&["--revert"], &[]);
        assert_eq!(code, 0, "{eco} revert: {stdout}\n{stderr}");
        if !["pnpm", "nuget"].contains(eco) {
            assert_eq!(masked_tree(&f.root), pristine, "{eco}: byte-exact restore");
        } else {
            let reverted = read_tree(&fixtures_dir().join(eco).join("reverted"));
            for (rel, mut bytes) in reverted {
                // The base binary always ended a re-rendered pnpm
                // package.json with a newline; this binary keeps the
                // file's own trailer, and the fixture's has none (#662).
                if *eco == "pnpm" && rel == "package.json" {
                    assert_eq!(bytes.pop(), Some(b'\n'), "{eco}: {rel}");
                }
                assert_eq!(
                    std::fs::read(f.root.join(&rel)).unwrap(),
                    bytes,
                    "{eco}: {rel} reverts exactly as the base binary reverted it"
                );
            }
        }
    }
}

/// `bytes` with every ` --hash=sha256:<64 hex>` option removed.
fn strip_sha256_hash_options(bytes: &[u8]) -> Vec<u8> {
    const NEEDLE: &[u8] = b" --hash=sha256:";
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        let hex = bytes.get(i + NEEDLE.len()..i + NEEDLE.len() + 64);
        if bytes[i..].starts_with(NEEDLE)
            && hex.is_some_and(|h| h.iter().all(u8::is_ascii_hexdigit))
        {
            i += NEEDLE.len() + 64;
        } else {
            out.push(bytes[i]);
            i += 1;
        }
    }
    out
}

/// Against the integrated base: for every ecosystem this binary wires
/// exactly the files the base binary wired (the checked-in legacy
/// fixtures), and its ledger — whatever its on-disk version — loads to the
/// same entries the base's version-1 ledger loads to.
#[tokio::test]
async fn server_artifacts_preserve_legacy_wiring_shape_and_originals() {
    // Maven now vendors through the suffixed JVM planner (#973); its
    // legacy fixture is revert-only (`legacy_maven_ledger_is_refused_until_reverted`).
    for eco in fx::ALL.iter().filter(|eco| **eco != "maven") {
        let mut base_wired = read_tree(&fixtures_dir().join(eco).join("wired"));
        if *eco == "pypi-requirements" {
            // The one intended difference: the base binary pinned its vendor
            // lines with `--hash` even in this unhashed requirements.txt,
            // which put pip in hash-checking mode for every other
            // requirement (#376). This binary writes the same lines without
            // it — in the file and in the ledger's recorded `new` text.
            for (_, bytes) in &mut base_wired {
                *bytes = strip_sha256_hash_options(bytes);
            }
        }
        let f = Fixture::new(eco);
        let (code, stdout, stderr) = f.vendor(&[], &[]);
        assert_eq!(code, 0, "{eco}: {stdout}\n{stderr}");
        let base_dir = tempfile::tempdir().unwrap();
        write_tree(base_dir.path(), &base_wired);
        let base = socket_patch_core::vendor::load_state(base_dir.path())
            .await
            .unwrap();
        let state = socket_patch_core::vendor::load_state(&f.root)
            .await
            .unwrap();
        assert_eq!(state.entries.len(), base.entries.len(), "{eco}");
        for (purl, old) in &base.entries {
            let new = &state.entries[purl];
            assert_eq!(
                (
                    &new.ecosystem,
                    &new.base_purl,
                    &new.uuid,
                    &new.artifact.path
                ),
                (
                    &old.ecosystem,
                    &old.base_purl,
                    &old.uuid,
                    &old.artifact.path
                ),
                "{eco}"
            );
            let shape = |entry: &socket_patch_core::vendor::state::VendorEntry| {
                entry
                    .wiring
                    .iter()
                    .map(|w| {
                        let original = w.original.clone().map(|value| {
                            if let serde_json::Value::String(mut text) = value {
                                for (purl, current) in &state.entries {
                                    let legacy = &base.entries[purl];
                                    if !current.artifact.sha256.is_empty() {
                                        text = text.replace(
                                            &current.artifact.sha256,
                                            &legacy.artifact.sha256,
                                        );
                                    }
                                }
                                serde_json::Value::String(text)
                            } else {
                                value
                            }
                        });
                        (w.file.clone(), w.kind.clone(), original)
                    })
                    .collect::<Vec<_>>()
            };
            assert_eq!(
                shape(new),
                shape(old),
                "{eco}: rollback originals survive server repacking"
            );
        }
    }
}

/// #973: a project still holding the pre-v5 single-POM ledger (the base
/// binary's `maven_pom_repository` wiring) is refused whole, with nothing
/// written; `vendor --revert` restores it byte for byte, and the next
/// vendor plans it through the suffixed JVM planner.
#[test]
fn legacy_maven_ledger_is_refused_until_reverted() {
    let wired = read_tree(&fixtures_dir().join("maven/wired"));
    let f = Fixture::new("maven");
    let pristine = tree(&f.root);
    write_tree(&f.root, &wired);
    let before = tree(&f.root);

    let (code, stdout, stderr) = f.vendor(&[], &[]);
    assert_ne!(code, 0, "{stdout}\n{stderr}");
    assert!(
        stdout.contains("vendor_jvm_shape_unsupported")
            && stdout.contains("reason: legacy_maven_root: "),
        "{stdout}"
    );
    assert_eq!(tree(&f.root), before, "the refusal writes nothing");

    let (code, stdout, stderr) = f.vendor(&["--revert"], &[]);
    assert_eq!(code, 0, "{stdout}\n{stderr}");
    assert_eq!(tree(&f.root), pristine, "byte-exact revert");

    let (code, stdout, stderr) = f.vendor(&[], &[]);
    assert_eq!(code, 0, "{stdout}\n{stderr}");
    let ledger = std::fs::read_to_string(f.root.join(".socket/vendor/state.json")).unwrap();
    assert!(ledger.contains("\"ecosystem\": \"jvm\""), "{ledger}");
    assert!(!ledger.contains("maven_pom_repository"), "{ledger}");
    assert!(std::fs::read_to_string(f.root.join("pom.xml"))
        .unwrap()
        .contains("1.0.0-socket.11111111"));
}
