//! `scan --mode hosted` over a yarn classic project whose grant carries
//! only a sha512 for the hosted tarball (#558). Yarn classic files a
//! tarball in its cache under `npm-<name>-<version>-<fragment>`, the
//! fragment being the `#<sha1>` of `resolved`. A fragmentless hosted URL
//! shares the slot of every fragmentless upstream copy, so a warm cache
//! installs stale bytes (yarn <= 1.17) or fails (yarn >= 1.19). The scan
//! downloads the served tarball, checks it against the grant's sha512 and
//! pins the sha1 of those bytes. A tarball it cannot fetch or verify drops
//! the patch (`npm_tarball_unavailable`) rather than pin a fragmentless URL.
//!
//! Runs the built binary as a subprocess against a wiremock patch API.

use std::path::Path;

use serde_json::{json, Value};
use wiremock::matchers::{method, path, path_regex};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::common;

const ORG: &str = "test-org";
const PURL: &str = "pkg:npm/left-pad@1.3.0";
const UUID: &str = "55858558-5585-4558-8558-558558558558";
const TOKEN: &str = "33333333-3333-4333-8333-333333333333";

fn tgz(entries: &[(&str, &[u8])]) -> Vec<u8> {
    let mut builder = tar::Builder::new(flate2::write::GzEncoder::new(
        Vec::new(),
        flate2::Compression::default(),
    ));
    for (name, data) in entries {
        let mut header = tar::Header::new_gnu();
        header.set_size(data.len() as u64);
        header.set_mode(0o644);
        header.set_cksum();
        builder.append_data(&mut header, name, *data).unwrap();
    }
    builder.into_inner().unwrap().finish().unwrap()
}

fn sha512_sri(bytes: &[u8]) -> String {
    use base64::Engine as _;
    use sha2::Digest as _;
    format!(
        "sha512-{}",
        base64::engine::general_purpose::STANDARD.encode(sha2::Sha512::digest(bytes))
    )
}

fn sha1_hex(bytes: &[u8]) -> String {
    use sha1::Digest as _;
    hex::encode(sha1::Sha1::digest(bytes))
}

fn patched_tarball() -> Vec<u8> {
    tgz(&[
        (
            "package/package.json",
            br#"{"name":"left-pad","version":"1.3.0","main":"index.js"}"#,
        ),
        ("package/index.js", b"module.exports = 'patched';\n"),
    ])
}

/// A classic lock whose `resolved` has no `#sha1` fragment (a private
/// registry, or a lock yarn wrote from such a registry).
const LOCK: &str = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n\
# yarn lockfile v1\n\n\n\
left-pad@1.3.0:\n  version \"1.3.0\"\n  \
resolved \"https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz\"\n  \
integrity sha512-XI5MPzVNApjAyhQzphX8BkmKsKUxD4LdyK24iZeQGinBN9yTQT3bFlCBy/aVx2HrNcqQGsdot8ghrjyrvMCoEA==\n";

fn write_classic_project(root: &Path) {
    std::fs::create_dir_all(root.join("node_modules/left-pad")).unwrap();
    std::fs::write(
        root.join("package.json"),
        "{\n  \"name\": \"app\",\n  \"version\": \"1.0.0\",\n  \"private\": true,\n  \
         \"packageManager\": \"yarn@1.22.22\",\n  \
         \"dependencies\": {\n    \"left-pad\": \"1.3.0\"\n  }\n}\n",
    )
    .unwrap();
    std::fs::write(root.join("yarn.lock"), LOCK).unwrap();
    std::fs::write(
        root.join("node_modules/left-pad/package.json"),
        r#"{"name":"left-pad","version":"1.3.0"}"#,
    )
    .unwrap();
}

/// The patch API, granting the hosted tarball with a sha512-only
/// integrity of `grant_bytes`, and serving `served` (or 404).
async fn mock_api(server: &MockServer, grant_bytes: &[u8], served: Option<Vec<u8>>) -> String {
    let artifact = format!("/patch/npm/left-pad/1.3.0/{TOKEN}/{UUID}/left-pad-1.3.0.tgz");
    let url = format!("{}{artifact}", server.uri());
    let sha512 = sha512_sri(grant_bytes);
    Mock::given(method("POST"))
        .and(path(format!("/v0/orgs/{ORG}/patches/batch")))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "packages": [{
                "purl": PURL,
                "patches": [{
                    "uuid": UUID, "purl": PURL, "tier": "free",
                    "cveIds": [], "ghsaIds": [], "severity": "high",
                    "title": "left-pad fixture"
                }]
            }],
            "canAccessPaidPatches": false,
        })))
        .mount(server)
        .await;
    Mock::given(method("GET"))
        .and(path_regex(format!(
            "^/v0/orgs/{ORG}/patches/by-package/.+$"
        )))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "patches": [{
                "uuid": UUID, "purl": PURL,
                "publishedAt": "2026-01-01T00:00:00Z",
                "description": "x", "license": "MIT", "tier": "free",
                "vulnerabilities": {}
            }],
            "canAccessPaidPatches": false,
        })))
        .mount(server)
        .await;
    Mock::given(method("POST"))
        .and(path(format!("/v0/orgs/{ORG}/patches/package")))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "results": {
                UUID: {
                    "status": "granted",
                    "url": url,
                    "purl": PURL,
                    "artifacts": [
                        { "kind": "tarball", "url": url, "integrity": { "sha512": sha512 } }
                    ],
                    "registryOverride": null
                }
            }
        })))
        .mount(server)
        .await;
    Mock::given(method("GET"))
        .and(path(format!("/v0/orgs/{ORG}/patches/view/{UUID}")))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "uuid": UUID, "purl": PURL,
            "publishedAt": "2026-01-01T00:00:00Z",
            "files": {},
            "vulnerabilities": {},
            "description": "x", "license": "MIT", "tier": "free"
        })))
        .mount(server)
        .await;
    let response = match served {
        Some(bytes) => ResponseTemplate::new(200).set_body_raw(bytes, "application/octet-stream"),
        None => ResponseTemplate::new(404),
    };
    Mock::given(method("GET"))
        .and(path(artifact))
        .respond_with(response)
        .mount(server)
        .await;
    url
}

fn scan(root: &Path, api: &str) -> (i32, Value, String) {
    let cwd = root.to_str().unwrap().to_string();
    let (code, stdout, stderr) = common::run_with_env(
        root,
        &[
            "scan",
            "--mode",
            "hosted",
            "--json",
            "--yes",
            "--cwd",
            &cwd,
            "--api-url",
            api,
            "--org",
            ORG,
            "--api-token",
            "fake",
        ],
        &[],
    );
    let doc: Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("JSON envelope ({e}):\n{stdout}\n{stderr}"));
    (code, doc, stderr)
}

#[tokio::test]
async fn issue_558_sha512_only_grant_pins_the_served_tarballs_sha1() {
    let server = MockServer::start().await;
    let tarball = patched_tarball();
    let url = mock_api(&server, &tarball, Some(tarball.clone())).await;
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().join("proj");
    write_classic_project(&root);

    let (code, doc, stderr) = scan(&root, &server.uri());
    assert_eq!(code, 0, "{doc:#}\n{stderr}");
    assert_eq!(common::envelope::hosted_pins(&doc).len(), 1, "{doc:#}");
    let lock = std::fs::read_to_string(root.join("yarn.lock")).unwrap();
    assert!(
        lock.contains(&format!(
            "  resolved \"{url}#{}\"\n  integrity {}\n",
            sha1_hex(&tarball),
            sha512_sri(&tarball)
        )),
        "the hosted pin carries the served tarball's sha1 fragment:\n{lock}"
    );
}

/// The served bytes are not the ones the grant's sha512 names (a stale CDN
/// copy, a truncated proxy body): no sha1 is derived from them, and nothing
/// is pinned.
#[tokio::test]
async fn issue_558_served_tarball_not_matching_the_grant_skips_the_patch() {
    let server = MockServer::start().await;
    let tarball = patched_tarball();
    mock_api(&server, &tarball, Some(b"not the granted tarball".to_vec())).await;
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().join("proj");
    write_classic_project(&root);

    let (_, doc, stderr) = scan(&root, &server.uri());
    assert_skipped_untouched(&root, &doc, &stderr);
}

#[tokio::test]
async fn issue_558_unfetchable_tarball_skips_the_patch() {
    let server = MockServer::start().await;
    let tarball = patched_tarball();
    mock_api(&server, &tarball, None).await;
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().join("proj");
    write_classic_project(&root);

    let (_, doc, stderr) = scan(&root, &server.uri());
    let detail = assert_skipped_untouched(&root, &doc, &stderr);
    // The detail still says where the fetch went, with the token redacted.
    assert!(
        detail.contains(&format!(
            "cannot fetch the hosted tarball: artifact not found: {}/patch/npm/left-pad/1.3.0/<redacted>/{UUID}/left-pad-1.3.0.tgz",
            server.uri()
        )),
        "{detail}"
    );
}

fn assert_skipped_untouched(root: &Path, doc: &Value, stderr: &str) -> String {
    // v5.0: a hosted skip is a `skipped` event, its code the `errorCode`
    // and its detail the `reason`.
    let skipped: Vec<&Value> = common::envelope::mode_events(doc, "hosted")
        .into_iter()
        .filter(|s| s["action"] == "skipped" && s["errorCode"] == "npm_tarball_unavailable")
        .collect();
    assert!(!skipped.is_empty(), "hosted skip: {doc:#}\n{stderr}");
    assert_eq!(skipped.len(), 1, "{doc:#}");
    assert_eq!(skipped[0]["purl"], PURL, "{doc:#}");
    // The served URL's grant token authorizes the org's download: never
    // shown, whatever the detail says.
    let detail = skipped[0]["reason"].as_str().unwrap();
    assert!(
        !detail.contains(TOKEN),
        "the grant token is redacted: {detail}"
    );
    assert!(common::envelope::hosted_pins(&doc).is_empty(), "{doc:#}");
    assert_eq!(
        std::fs::read_to_string(root.join("yarn.lock")).unwrap(),
        LOCK,
        "no fragmentless hosted pin is written"
    );
    detail.to_string()
}

/// #591: the served tarball's package.json adds a dependency yarn.lock
/// doesn't lock. Yarn 1 installs only what the lock names, so a pin would
/// install the patched package without it (and `vex` would attest it):
/// the scan refuses the pin with an actionable warning and leaves the
/// lock alone. The grant carries a sha1 here, so only the dependency
/// check needs the tarball.
#[tokio::test]
async fn issue_591_served_dependency_the_lock_does_not_lock_is_refused() {
    let server = MockServer::start().await;
    let tarball = tgz(&[
        (
            "package/package.json",
            br#"{"name":"left-pad","version":"1.3.0","dependencies":{"is-odd":"^3.0.0"}}"#,
        ),
        ("package/index.js", b"module.exports = require('is-odd');\n"),
    ]);
    mock_api_with_sha1(&server, &tarball).await;
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().join("proj");
    write_classic_project(&root);

    let (code, doc, stderr) = scan(&root, &server.uri());
    assert_eq!(code, 0, "{doc:#}\n{stderr}");
    assert!(common::envelope::hosted_pins(&doc).is_empty(), "{doc:#}");
    let warning = doc["warnings"]
        .as_array()
        .unwrap()
        .iter()
        .find(|w| w["code"] == "redirect_yarn_classic_dep_manifest_unlocked")
        .unwrap_or_else(|| panic!("refusal warning: {doc:#}"));
    let detail = warning["detail"].as_str().unwrap();
    assert!(
        detail.contains("is-odd@^3.0.0") && detail.contains("yarn add is-odd@^3.0.0"),
        "{detail}"
    );
    assert_eq!(
        std::fs::read_to_string(root.join("yarn.lock")).unwrap(),
        LOCK,
        "nothing is pinned with an incomplete dependency graph"
    );
}

/// [`mock_api`] with a grant that carries the tarball's sha1 too.
async fn mock_api_with_sha1(server: &MockServer, tarball: &[u8]) {
    let artifact = format!("/patch/npm/left-pad/1.3.0/{TOKEN}/{UUID}/left-pad-1.3.0.tgz");
    let url = format!("{}{artifact}", server.uri());
    Mock::given(method("POST"))
        .and(path(format!("/v0/orgs/{ORG}/patches/package")))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "results": {
                UUID: {
                    "status": "granted",
                    "url": url,
                    "purl": PURL,
                    "artifacts": [{
                        "kind": "tarball", "url": url,
                        "integrity": { "sha512": sha512_sri(tarball), "sha1": sha1_hex(tarball) }
                    }],
                    "registryOverride": null
                }
            }
        })))
        .mount(server)
        .await;
    mock_api(server, tarball, Some(tarball.to_vec())).await;
}
