//! `scan --mode hosted` over a yarn berry project whose patched package
//! declares a `bin` (#718): yarn builds the pinned tarball entry from the
//! served tarball's own package.json, whose `bin` keeps its published
//! spelling (`./dist/bin/uuid`) where the registry entry carries the
//! normalized `dist/bin/uuid`. The scan fetches the served tarball and
//! writes its `bin:` map; a tarball it cannot fetch drops the patch
//! (`npm_manifest_unavailable`) rather than pin an entry yarn rewrites.
//!
//! Runs the built binary as a subprocess against a wiremock patch API.

use std::path::Path;

use serde_json::{json, Value};
use wiremock::matchers::{method, path, path_regex};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::common;

const ORG: &str = "test-org";
const PURL: &str = "pkg:npm/uuid@9.0.1";
const UUID: &str = "71717171-7171-4171-8171-717171717171";
const TOKEN: &str = "33333333-3333-4333-8333-333333333333";

/// The hosted `skipped` events of a scan envelope as v4's
/// `redirect.skipped[]` rows: `{purl, uuid, reason: <errorCode>, detail:
/// <reason>}` (v5.0 records them as `details.mode: "hosted"` events).
fn hosted_skipped(doc: &serde_json::Value) -> Vec<serde_json::Value> {
    doc["events"]
        .as_array()
        .into_iter()
        .flatten()
        .filter(|e| e["details"]["mode"] == "hosted" && e["action"] == "skipped")
        .map(|e| {
            serde_json::json!({
                "purl": e["purl"], "uuid": e["uuid"],
                "reason": e["errorCode"], "detail": e["reason"],
            })
        })
        .collect()
}

fn tgz(entries: &[(&str, &[u8])]) -> Vec<u8> {
    let mut builder = tar::Builder::new(flate2::write::GzEncoder::new(
        Vec::new(),
        flate2::Compression::default(),
    ));
    for (name, data) in entries {
        let mut header = tar::Header::new_gnu();
        header.set_size(data.len() as u64);
        header.set_mode(0o644);
        header.set_cksum();
        builder.append_data(&mut header, name, *data).unwrap();
    }
    builder.into_inner().unwrap().finish().unwrap()
}

fn sha512_sri(bytes: &[u8]) -> String {
    use base64::Engine as _;
    use sha2::Digest as _;
    format!(
        "sha512-{}",
        base64::engine::general_purpose::STANDARD.encode(sha2::Sha512::digest(bytes))
    )
}

fn write_berry_project(root: &Path) {
    std::fs::create_dir_all(root.join("node_modules/uuid")).unwrap();
    std::fs::write(
        root.join("package.json"),
        "{\n  \"name\": \"app\",\n  \"version\": \"1.0.0\",\n  \"private\": true,\n  \
         \"dependencies\": {\n    \"uuid\": \"^9.0.0\"\n  }\n}\n",
    )
    .unwrap();
    std::fs::write(
        root.join(".yarnrc.yml"),
        "nodeLinker: node-modules\nenableGlobalCache: false\n",
    )
    .unwrap();
    std::fs::write(
        root.join("yarn.lock"),
        format!(
            "# This file is generated by running \"yarn install\" inside your project.\n\
             # Manual changes might be lost - proceed with caution!\n\n\
             __metadata:\n  version: 8\n  cacheKey: 10c0\n\n\
             \"app@workspace:.\":\n  version: 0.0.0-use.local\n  resolution: \"app@workspace:.\"\n  \
             dependencies:\n    uuid: \"npm:^9.0.0\"\n  languageName: unknown\n  linkType: soft\n\n\
             \"uuid@npm:^9.0.0\":\n  version: 9.0.1\n  resolution: \"uuid@npm:9.0.1\"\n  \
             bin:\n    uuid: dist/bin/uuid\n  checksum: 10c0/{}\n  languageName: node\n  \
             linkType: hard\n",
            "1".repeat(128)
        ),
    )
    .unwrap();
    std::fs::write(
        root.join("node_modules/uuid/package.json"),
        r#"{"name":"uuid","version":"9.0.1","bin":{"uuid":"./dist/bin/uuid"}}"#,
    )
    .unwrap();
}

/// The patch API, with the hosted tarball served as `tarball` (or 404).
async fn mock_api(server: &MockServer, tarball: Option<Vec<u8>>) -> String {
    let artifact = format!("/patch/npm/uuid/9.0.1/{TOKEN}/{UUID}/uuid-9.0.1.tgz");
    let url = format!("{}{artifact}", server.uri());
    let sha512 = tarball
        .as_deref()
        .map(sha512_sri)
        .unwrap_or_else(|| sha512_sri(b"never served"));
    Mock::given(method("POST"))
        .and(path(format!("/v0/orgs/{ORG}/patches/batch")))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "packages": [{
                "purl": PURL,
                "patches": [{
                    "uuid": UUID, "purl": PURL, "tier": "free",
                    "cveIds": [], "ghsaIds": [], "severity": "high",
                    "title": "uuid fixture"
                }]
            }],
            "canAccessPaidPatches": false,
        })))
        .mount(server)
        .await;
    Mock::given(method("GET"))
        .and(path_regex(format!(
            "^/v0/orgs/{ORG}/patches/by-package/.+$"
        )))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "patches": [{
                "uuid": UUID, "purl": PURL,
                "publishedAt": "2026-01-01T00:00:00Z",
                "description": "x", "license": "MIT", "tier": "free",
                "vulnerabilities": {}
            }],
            "canAccessPaidPatches": false,
        })))
        .mount(server)
        .await;
    Mock::given(method("POST"))
        .and(path(format!("/v0/orgs/{ORG}/patches/package")))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "results": {
                UUID: {
                    "status": "granted",
                    "url": url,
                    "purl": PURL,
                    "artifacts": [
                        { "kind": "tarball", "url": url, "integrity": { "sha512": sha512 } },
                        { "kind": "yarn-berry-zip", "url": url,
                          "integrity": { "yarnBerry10c0": format!("10c0/{}", "7".repeat(128)) } }
                    ],
                    "registryOverride": null
                }
            }
        })))
        .mount(server)
        .await;
    Mock::given(method("GET"))
        .and(path(format!("/v0/orgs/{ORG}/patches/view/{UUID}")))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "uuid": UUID, "purl": PURL,
            "publishedAt": "2026-01-01T00:00:00Z",
            "files": {},
            "vulnerabilities": {},
            "description": "x", "license": "MIT", "tier": "free"
        })))
        .mount(server)
        .await;
    let served = match tarball {
        Some(bytes) => ResponseTemplate::new(200).set_body_raw(bytes, "application/octet-stream"),
        None => ResponseTemplate::new(404),
    };
    Mock::given(method("GET"))
        .and(path(artifact))
        .respond_with(served)
        .mount(server)
        .await;
    url
}

fn scan(root: &Path, api: &str) -> (i32, Value, String) {
    let cwd = root.to_str().unwrap().to_string();
    let (code, stdout, stderr) = common::run_with_env(
        root,
        &[
            "scan",
            "--mode",
            "hosted",
            "--json",
            "--yes",
            "--cwd",
            &cwd,
            "--api-url",
            api,
            "--org",
            ORG,
            "--api-token",
            "fake",
        ],
        &[],
    );
    let doc: Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("JSON envelope ({e}):\n{stdout}\n{stderr}"));
    (code, doc, stderr)
}

#[tokio::test]
async fn issue_718_hosted_pin_takes_bin_from_the_served_tarball() {
    let server = MockServer::start().await;
    let manifest = br#"{"name":"uuid","version":"9.0.1","bin":{"uuid":"./dist/bin/uuid"}}"#;
    let url = mock_api(
        &server,
        Some(tgz(&[
            ("package/package.json", manifest),
            ("package/dist/bin/uuid", b"#!/usr/bin/env node\n"),
        ])),
    )
    .await;
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().join("proj");
    write_berry_project(&root);

    let (code, doc, stderr) = scan(&root, &server.uri());
    assert_eq!(code, 0, "{doc:#}\n{stderr}");
    assert_eq!(
        crate::common::envelope::hosted_pins(&doc).len(),
        1,
        "{doc:#}"
    );
    let lock = std::fs::read_to_string(root.join("yarn.lock")).unwrap();
    assert!(
        lock.contains(&format!(
            "\"uuid@{url}\":\n  version: 9.0.1\n  resolution: \"uuid@{url}\"\n  \
             bin:\n    uuid: ./dist/bin/uuid\n  checksum: 10c0/{}\n",
            "7".repeat(128)
        )),
        "the pin carries the served tarball's bin map:\n{lock}"
    );
}

#[tokio::test]
async fn unfetchable_served_manifest_skips_the_patch() {
    let server = MockServer::start().await;
    mock_api(&server, None).await;
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().join("proj");
    write_berry_project(&root);
    let lock_before = std::fs::read(root.join("yarn.lock")).unwrap();

    let (_, doc, _stderr) = scan(&root, &server.uri());
    let all_skipped = hosted_skipped(&doc);
    let skipped: Vec<&Value> = all_skipped
        .iter()
        .filter(|s| s["reason"] == "npm_manifest_unavailable")
        .collect();
    assert_eq!(skipped.len(), 1, "{doc:#}");
    assert_eq!(skipped[0]["purl"], PURL, "{doc:#}");
    let detail = skipped[0]["detail"].as_str().unwrap();
    assert!(
        !detail.contains(&server.uri()),
        "the hosted URL is redacted: {detail}"
    );
    assert_eq!(
        crate::common::envelope::hosted_pins(&doc).len(),
        0,
        "{doc:#}"
    );
    assert_eq!(
        std::fs::read(root.join("yarn.lock")).unwrap(),
        lock_before,
        "nothing is pinned without the served manifest"
    );
}
