// Generated by socket-patch. Do not edit; re-run `socket-patch vendor`.
val socketPatchVendorPins = Seq[(String, String, String, String, String, String)](
  // (group, artifact, socket version, repo-relative path, sha256, source URL; "" = vendored)
  ("org.apache.commons", "commons-lang3", "3.11-socket.abcdef12", "org/apache/commons/commons-lang3/3.11-socket.abcdef12/commons-lang3-3.11-socket.abcdef12.pom", "b883c974d2b1e818d95e597c6c0c48ac79bd8bef5d148c2a55e503b061431f7f", ""), // socket-patch abcdef12-0000-4000-8000-000000000001
  ("org.apache.commons", "commons-lang3", "3.11-socket.abcdef12", "org/apache/commons/commons-lang3/3.11-socket.abcdef12/commons-lang3-3.11-socket.abcdef12.jar", "9a89cb5d42d1007bdf1c8fcaa621088adea13d4bb3ee3880c30eda55459b2940", ""), // socket-patch abcdef12-0000-4000-8000-000000000001
  ("org.apache.commons", "commons-text", "1.9-socket.12345678", "org/apache/commons/commons-text/1.9-socket.12345678/commons-text-1.9-socket.12345678.pom", "769677b191e5c2d2b1a616d8ae779909f1008955758ddfb3414c4b007154b237", ""), // socket-patch 12345678-0000-4000-8000-000000000002
  ("org.apache.commons", "commons-text", "1.9-socket.12345678", "org/apache/commons/commons-text/1.9-socket.12345678/commons-text-1.9-socket.12345678.jar", "60588301ab3c82c261151a35fad5e547a635e0e5b90985f4c2a668e5cea0ac2e", "") // socket-patch 12345678-0000-4000-8000-000000000002
)
val socketPatchVendorRows = SettingKey[Seq[(String, String, String, String, String, String)]]("socketPatchVendorRows")
val socketPatchVendorApplied = SettingKey[Boolean]("socketPatchApplied")
def socketPatchVendorFail(m: String): Nothing = sys.error("socket-patch: " + m + ". Re-run `socket-patch vendor`.")
def socketPatchVendorSha256(f: java.io.File): String = java.security.MessageDigest.getInstance("SHA-256")
  .digest(java.nio.file.Files.readAllBytes(f.toPath)).map(b => "%02x".format(b & 0xff)).mkString
def socketPatchVendorNewer(v: String, base: String): Boolean = {
  def nums(s: String): Seq[BigInt] = "^[0-9]+(\\.[0-9]+)*".r.findFirstIn(s.trim).toSeq.flatMap(_.split('.')).map(n => BigInt(n))
  nums(v).zipAll(nums(base), BigInt(0), BigInt(0)).find(t => t._1 != t._2).exists(t => t._1 > t._2)
}
def socketPatchVendorVerify(p: String, pins: Seq[(String, String, String, String, String, String)], deps: Seq[ModuleID], r: UpdateReport): UpdateReport = {
  deps.foreach { d => pins.find(x => x._1 == d.organization && (x._2 == d.name || x._2.startsWith(d.name + "_"))).foreach { case (g, a, sv, _, _, _) =>
    val base = sv.substring(0, sv.lastIndexOf("-socket."))
    if (!d.revision.exists(c => "+[](),".indexOf(c) >= 0) && !d.revision.startsWith("latest.") && socketPatchVendorNewer(d.revision, base)) socketPatchVendorFail(p + " declares " + g + ":" + a + ":" + d.revision + " but socket-patch forces " + sv + " (a downgrade); roll the patch back, or declare " + base)
  } }
  r.configurations.foreach { c => c.modules.filter(!_.evicted).foreach { m =>
    val mine = pins.filter(x => x._1 == m.module.organization && x._2 == m.module.name)
    mine.headOption.foreach { case (g, a, sv, _, _, _) =>
      if (m.module.revision != sv) socketPatchVendorFail(p + " resolves " + g + ":" + a + ":" + m.module.revision + ", expected " + sv + "; a dependencyOverrides := or resolver change in the build replaced socket-patch's")
      m.artifacts.foreach { case (_, f) =>
        val got = socketPatchVendorSha256(f)
        if (!mine.exists(_._5 == got)) socketPatchVendorFail(g + ":" + a + ":" + sv + " resolved to " + f + " with sha256 " + got + ", which is not pinned (tampered, or from ivy-local, mavenLocal or another checkout); delete it and run sbt update")
      }
    }
  } }
  r
}
Global / socketPatchVendorRows := socketPatchVendorPins
inThisBuild(Seq(
  resolvers += {
    val repo = new java.io.File(baseDirectory.value, ".socket/vendor/maven2").getCanonicalFile
    socketPatchVendorPins.foreach { case (_, _, _, rel, want, src) =>
      val f = new java.io.File(repo, rel)
      if (!f.isFile || socketPatchVendorSha256(f) != want) {
        if (src.isEmpty) socketPatchVendorFail(if (f.isFile) "" + f + " has sha256 " + socketPatchVendorSha256(f) + ", pinned " + want else "missing " + f)
        f.getParentFile.mkdirs()
        val tmp = java.io.File.createTempFile("socket-patch", ".part", f.getParentFile)
        try {
          try {
            val c = new java.net.URL(src).openConnection(); c.setConnectTimeout(30000); c.setReadTimeout(120000)
            val in = c.getInputStream
            try java.nio.file.Files.copy(in, tmp.toPath, java.nio.file.StandardCopyOption.REPLACE_EXISTING) finally in.close()
          } catch { case e: java.io.IOException => socketPatchVendorFail("cannot download " + src + " (" + e + ")") }
          val got = socketPatchVendorSha256(tmp)
          if (got != want) socketPatchVendorFail("" + src + " served sha256 " + got + ", pinned " + want)
          java.nio.file.Files.move(tmp.toPath, f.toPath, java.nio.file.StandardCopyOption.REPLACE_EXISTING)
        } finally tmp.delete()
      }
    }
    "socket-patch-vendor" at repo.toURI.toString
  },
  dependencyOverrides += "org.apache.commons" % "commons-lang3" % "3.11-socket.abcdef12", // socket-patch abcdef12-0000-4000-8000-000000000001 deps=0a1b2c3d
  dependencyOverrides += "org.apache.commons" % "commons-text" % "1.9-socket.12345678" // socket-patch 12345678-0000-4000-8000-000000000002 deps=4e5f6a7b
))
Global / onLoad := (Global / onLoad).value andThen { s =>
  val x = Project.extract(s)
  val pins = Seq("socketPatchHostedRows", "socketPatchVendorRows").flatMap(k => x.getOpt(Global / SettingKey[Seq[(String, String, String, String, String, String)]](k)).getOrElse(Nil))
  if (x.getOpt(Global / socketPatchVendorApplied).isDefined) s
  else x.appendWithoutSession((Global / socketPatchVendorApplied := true) +: x.structure.allProjectRefs.map(p => p / update := Def.uncached(socketPatchVendorVerify(p.project, pins, (p / allDependencies).value, (p / update).value))), s)
}
