//! sbt upstream restore: the inverse of `redirect::sbt::rewrite_sbt`, no
//! network. Strictly parse `socket-patch.sbt`, drop the in-scope pins' rows
//! ([`crate::patch::redirect::sbt::remove_pins`]), re-render, or delete the
//! file when none remain. The downloads under `.socket/sbt-hosted/` are
//! left alone (gitignored, inert once no row names them). Order
//! independent: every pass re-reads the staged text.

use std::collections::BTreeSet;

use super::{Ctx, FormatResult, HostedPin, View};
use crate::formats::sbt::owned_file::{OwnedFileError, HOSTED_FILE};
use crate::patch::redirect::sbt::{hosted_pins, remove_pins};

pub(crate) async fn restore(
    view: &mut View<'_>,
    pins: &[&HostedPin],
    files: &[String],
    ctx: &Ctx<'_>,
) -> FormatResult {
    let _ = ctx;
    let mut result = FormatResult::default();
    let in_scope: Vec<&HostedPin> = pins
        .iter()
        .copied()
        .filter(|p| p.files.iter().any(|f| f == HOSTED_FILE))
        .collect();
    if !files.iter().any(|f| f == HOSTED_FILE) || in_scope.is_empty() {
        return result;
    }
    let refuse_all = |result: &mut FormatResult, why: String| {
        for pin in &in_scope {
            result.refuse(&pin.uuid, why.clone());
        }
    };
    let text = match view.read(HOSTED_FILE).await {
        Ok(Some(text)) => text,
        Ok(None) => {
            refuse_all(&mut result, format!("{HOSTED_FILE} is gone"));
            return result;
        }
        Err(why) => {
            refuse_all(&mut result, why);
            return result;
        }
    };
    let file_pins = match hosted_pins(&text) {
        Ok(pins) => pins,
        Err(OwnedFileError::Modified(why)) => {
            refuse_all(
                &mut result,
                format!("{HOSTED_FILE} was edited ({why}), so socket-patch cannot rewrite it"),
            );
            return result;
        }
        Err(OwnedFileError::Foreign) => {
            refuse_all(
                &mut result,
                format!("{HOSTED_FILE} was not generated by socket-patch"),
            );
            return result;
        }
    };
    let mut remove: BTreeSet<String> = BTreeSet::new();
    for pin in &in_scope {
        let row = file_pins.iter().find(|p| p.uuid == pin.uuid);
        let purl_matches = row.is_some_and(|row| {
            crate::utils::purl::parse_maven_purl(&pin.purl).is_some_and(|(g, a, v)| {
                g.as_ref() == row.group && a.as_ref() == row.artifact && v.as_ref() == row.base
            })
        });
        match row {
            Some(_) if purl_matches => {
                remove.insert(pin.uuid.clone());
            }
            Some(row) => result.refuse(
                &pin.uuid,
                format!(
                    "{HOSTED_FILE} pins patch {} for {}:{}:{}, not {}",
                    pin.uuid, row.group, row.artifact, row.base, pin.purl
                ),
            ),
            None => result.refuse(
                &pin.uuid,
                format!("{HOSTED_FILE} does not pin patch {}", pin.uuid),
            ),
        }
    }
    if remove.is_empty() {
        return result;
    }
    match remove_pins(&text, &remove) {
        Ok(Some(next)) => view.write(HOSTED_FILE, next),
        Ok(None) => view.remove(HOSTED_FILE),
        Err(why) => {
            refuse_all(
                &mut result,
                format!("{HOSTED_FILE} cannot be re-rendered: {why:?}"),
            );
            return result;
        }
    }
    result.handled.extend(remove);
    result
}

#[cfg(test)]
mod tests {
    use super::super::{restore_upstream, RestoreOptions};
    use super::*;

    const LANG3_UUID: &str = "abcdef12-0000-4000-8000-000000000001";
    const TEXT_UUID: &str = "12345678-0000-4000-8000-000000000002";
    const LANG3: &str = "pkg:maven/org.apache.commons/commons-lang3@3.11";
    const TEXT: &str = "pkg:maven/org.apache.commons/commons-text@1.9";

    fn fixture(name: &str) -> String {
        std::fs::read_to_string(format!(
            "{}/tests/fixtures/sbt/owned_file/{name}",
            env!("CARGO_MANIFEST_DIR")
        ))
        .unwrap()
    }

    fn pin(purl: &str, uuid: &str) -> HostedPin {
        HostedPin {
            purl: purl.into(),
            uuid: uuid.into(),
            files: vec![HOSTED_FILE.into()],
        }
    }

    async fn run(root: &std::path::Path, pins: &[HostedPin]) -> super::super::RestoreOutcome {
        restore_upstream(
            root,
            pins,
            &RestoreOptions {
                offline: true,
                ..Default::default()
            },
        )
        .await
    }

    #[tokio::test]
    async fn removes_one_of_two_then_the_last_in_either_order() {
        for order in [[TEXT_UUID, LANG3_UUID], [LANG3_UUID, TEXT_UUID]] {
            let tmp = tempfile::tempdir().unwrap();
            let file = tmp.path().join(HOSTED_FILE);
            std::fs::write(&file, fixture("hosted-1-2pin.sbt")).unwrap();
            let purl = |u: &str| if u == LANG3_UUID { LANG3 } else { TEXT };
            let out = run(tmp.path(), &[pin(purl(order[0]), order[0])]).await;
            assert_eq!(out.refused().count(), 0, "{:?}", out.pins);
            let left = std::fs::read_to_string(&file).unwrap();
            assert!(!left.contains(order[0]) && left.contains(order[1]));
            if order[0] == TEXT_UUID {
                assert_eq!(left, fixture("hosted-1-1pin.sbt"));
            }
            let out = run(tmp.path(), &[pin(purl(order[1]), order[1])]).await;
            assert_eq!(out.refused().count(), 0, "{:?}", out.pins);
            assert!(!file.exists(), "the last pin out deletes the file");
            assert_eq!(out.reverted_files, [HOSTED_FILE]);
        }
    }

    #[tokio::test]
    async fn both_at_once_delete_the_file() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join(HOSTED_FILE), fixture("hosted-2-2pin.sbt")).unwrap();
        let out = run(tmp.path(), &[pin(LANG3, LANG3_UUID), pin(TEXT, TEXT_UUID)]).await;
        assert_eq!(out.restored().count(), 2);
        assert!(!tmp.path().join(HOSTED_FILE).exists());
    }

    #[tokio::test]
    async fn refuses_an_edited_file_a_wrong_purl_and_an_unpinned_uuid() {
        let tmp = tempfile::tempdir().unwrap();
        let file = tmp.path().join(HOSTED_FILE);
        let edited = fixture("hosted-1-2pin.sbt").replace("Do not edit", "Do edit");
        std::fs::write(&file, &edited).unwrap();
        let out = run(tmp.path(), &[pin(LANG3, LANG3_UUID)]).await;
        let (_, why) = out.refused().next().expect("refused");
        assert!(why.contains("was edited"), "{why}");
        assert_eq!(std::fs::read_to_string(&file).unwrap(), edited);

        std::fs::write(&file, fixture("hosted-1-2pin.sbt")).unwrap();
        let out = run(
            tmp.path(),
            &[
                pin("pkg:maven/org.apache.commons/commons-lang3@9.9", LANG3_UUID),
                pin(TEXT, "99999999-0000-4000-8000-000000000009"),
            ],
        )
        .await;
        assert_eq!(out.refused().count(), 2);
        assert_eq!(
            std::fs::read_to_string(&file).unwrap(),
            fixture("hosted-1-2pin.sbt")
        );
    }
}
