// Generated by socket-patch. Do not edit; re-run `socket-patch get`.
val socketPatchHostedPins = Seq[(String, String, String, String, String, String)](
  // (group, artifact, socket version, repo-relative path, sha256, source URL; "" = vendored)
  ("org.apache.commons", "commons-text", "1.9-socket.12345678", "org/apache/commons/commons-text/1.9-socket.12345678/commons-text-1.9-socket.12345678.pom", "b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2", "https://patch.socket.dev/patch-registry/maven/11111111-1111-4111-8111-111111111111/12345678-0000-4000-8000-000000000002/maven2/org/apache/commons/commons-text/1.9-socket.12345678/commons-text-1.9-socket.12345678.pom"), // socket-patch 12345678-0000-4000-8000-000000000002
  ("org.apache.commons", "commons-text", "1.9-socket.12345678", "org/apache/commons/commons-text/1.9-socket.12345678/commons-text-1.9-socket.12345678.jar", "c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2", "https://patch.socket.dev/patch-registry/maven/11111111-1111-4111-8111-111111111111/12345678-0000-4000-8000-000000000002/maven2/org/apache/commons/commons-text/1.9-socket.12345678/commons-text-1.9-socket.12345678.jar") // socket-patch 12345678-0000-4000-8000-000000000002
)
val socketPatchHostedRows = SettingKey[Seq[(String, String, String, String, String, String)]]("socketPatchHostedRows")
val socketPatchHostedApplied = SettingKey[Boolean]("socketPatchApplied")
def socketPatchHostedFail(m: String): Nothing = sys.error("socket-patch: " + m + ". Re-run `socket-patch get`.")
def socketPatchHostedSha256(f: java.io.File): String = java.security.MessageDigest.getInstance("SHA-256")
  .digest(java.nio.file.Files.readAllBytes(f.toPath)).map(b => "%02x".format(b & 0xff)).mkString
def socketPatchHostedNewer(v: String, base: String): Boolean = {
  def nums(s: String): Seq[BigInt] = "^[0-9]+(\\.[0-9]+)*".r.findFirstIn(s.trim).toSeq.flatMap(_.split('.')).map(n => BigInt(n))
  nums(v).zipAll(nums(base), BigInt(0), BigInt(0)).find(t => t._1 != t._2).exists(t => t._1 > t._2)
}
def socketPatchHostedVerify(p: String, pins: Seq[(String, String, String, String, String, String)], deps: Seq[ModuleID], r: UpdateReport): UpdateReport = {
  deps.foreach { d => pins.find(x => x._1 == d.organization && (x._2 == d.name || x._2.startsWith(d.name + "_"))).foreach { case (g, a, sv, _, _, _) =>
    val base = sv.substring(0, sv.lastIndexOf("-socket."))
    if (!d.revision.exists(c => "+[](),".indexOf(c) >= 0) && !d.revision.startsWith("latest.") && socketPatchHostedNewer(d.revision, base)) socketPatchHostedFail(p + " declares " + g + ":" + a + ":" + d.revision + " but socket-patch forces " + sv + " (a downgrade); roll the patch back, or declare " + base)
  } }
  r.configurations.foreach { c => c.modules.filter(!_.evicted).foreach { m =>
    val mine = pins.filter(x => x._1 == m.module.organization && x._2 == m.module.name)
    mine.headOption.foreach { case (g, a, sv, _, _, _) =>
      if (m.module.revision != sv) socketPatchHostedFail(p + " resolves " + g + ":" + a + ":" + m.module.revision + ", expected " + sv + "; a dependencyOverrides := or resolver change in the build replaced socket-patch's")
      m.artifacts.foreach { case (_, f) =>
        val got = socketPatchHostedSha256(f)
        if (!mine.exists(_._5 == got)) socketPatchHostedFail(g + ":" + a + ":" + sv + " resolved to " + f + " with sha256 " + got + ", which is not pinned (tampered, or from ivy-local, mavenLocal or another checkout); delete it and run sbt update")
      }
    }
  } }
  r
}
Global / socketPatchHostedRows := socketPatchHostedPins
inThisBuild(Seq(
  resolvers += {
    val repo = new java.io.File(baseDirectory.value, ".socket/sbt-hosted/maven2").getCanonicalFile
    val gitignore = new java.io.File(repo.getParentFile, ".gitignore"); if (!gitignore.isFile) { repo.mkdirs(); java.nio.file.Files.write(gitignore.toPath, "*\n".getBytes) }
    socketPatchHostedPins.foreach { case (_, _, _, rel, want, src) =>
      val f = new java.io.File(repo, rel)
      if (!f.isFile || socketPatchHostedSha256(f) != want) {
        if (src.isEmpty) socketPatchHostedFail(if (f.isFile) "" + f + " has sha256 " + socketPatchHostedSha256(f) + ", pinned " + want else "missing " + f)
        f.getParentFile.mkdirs()
        val tmp = java.io.File.createTempFile("socket-patch", ".part", f.getParentFile)
        try {
          try {
            val c = new java.net.URL(src).openConnection(); c.setConnectTimeout(30000); c.setReadTimeout(120000)
            val in = c.getInputStream
            try java.nio.file.Files.copy(in, tmp.toPath, java.nio.file.StandardCopyOption.REPLACE_EXISTING) finally in.close()
          } catch { case e: java.io.IOException => socketPatchHostedFail("cannot download " + src + " (" + e + ")") }
          val got = socketPatchHostedSha256(tmp)
          if (got != want) socketPatchHostedFail("" + src + " served sha256 " + got + ", pinned " + want)
          java.nio.file.Files.move(tmp.toPath, f.toPath, java.nio.file.StandardCopyOption.REPLACE_EXISTING)
        } finally tmp.delete()
      }
    }
    "socket-patch" at repo.toURI.toString
  },
  dependencyOverrides += "org.apache.commons" % "commons-text" % "1.9-socket.12345678" // socket-patch 12345678-0000-4000-8000-000000000002 deps=0a1b2c3d
))
Global / onLoad := (Global / onLoad).value andThen { s =>
  val x = Project.extract(s)
  val pins = Seq("socketPatchHostedRows", "socketPatchVendorRows").flatMap(k => x.getOpt(Global / SettingKey[Seq[(String, String, String, String, String, String)]](k)).getOrElse(Nil))
  if (x.getOpt(Global / socketPatchHostedApplied).isDefined) s
  else x.appendWithoutSession((Global / socketPatchHostedApplied := true) +: x.structure.allProjectRefs.flatMap(p => Seq[Def.Setting[_]](p / update := socketPatchHostedVerify(p.project, pins, (p / allDependencies).value, (p / update).value), p / externalResolvers := { val (ours, rest) = (p / externalResolvers).value.partition(r => r.name == "socket-patch" || r.name == "socket-patch-vendor"); ours ++ rest })), s)
}
