//! Manifest-less VEX for yarn BERRY — hermetic cells for the berry-only
//! layouts and lock shapes the flavor matrix in `e2e_vex_lockfile/yarn.rs`
//! does not reach. No toolchain, no network, every OS (the pnpm-linker
//! symlink cell is unix-only). The real-yarn counterparts of these shapes
//! live in the `e2e_*yarn*berry*_build.rs` / `e2e_yarn4_*_build.rs`
//! capstones (see `yarn_berry_common`).
//!
//! The only inputs are what a checkout with NO `.socket/manifest.json`
//! (and, unless a cell adds one, no ledgers) carries: `package.json`,
//! `yarn.lock`, `.yarnrc.yml`, an installed tree and — vendored — the
//! committed `.socket/vendor/npm/<uuid>/<leaf>.tgz`. The record comes from
//! a wiremock patch API (`vex_e2e_common::PatchApi`).
//!
//! | cell | shape | expectation |
//! |---|---|---|
//! | pnpm linker | `node_modules/<pkg>` → `.store/<pkg>-npm-…/package` symlink | patched attests; tampered store file `hash_mismatch`; pristine `not_applied`; vendored `left-pad-file-…` store entry: artifact evidence |
//! | workspaces | member dependency, hoisted install, root `resolutions` selectors | hosted attests; vendored attests for `name` / `**/name` / `parent/name` / `name@range`; a MEMBER-only `resolutions` is no wiring (`vendor_unwired` for a ledger) |
//! | scoped | `@scope/pkg` hosted `__archiveUrl` + vendored `@scope/pkg-<v>.tgz` | both attest `pkg:npm/%40scope/pkg@v` (events: `@scope`) from the API record; offline `record_unavailable`, zero requests; pristine install `not_applied` |
//! | npm alias | `"lp@npm:left-pad@1.3.0"` installed at `node_modules/lp` | the REAL package is attested after hashing the alias dir; tampered `hash_mismatch`; stale pristine `not_applied` (regression: the alias dir used to be "not installed", so the lock pin attested it) |
//! | multi-descriptor + CRLF + BOM | one block for `^1.0.0, ^1.3.0` | attests from the `10c0` pin |
//! | two uuids for one package | two live blocks wiring one purl to different patches | never attested (`wiring_conflict`) |
//! | user `yarn patch` on top | `patch:` entry wrapping the hosted locator | the hosted base entry still attests when the user patch leaves the Socket file intact; a user patch rewriting it is `hash_mismatch` |
//! | foreign / look-alike hosts, uuid-shaped token only | `__archiveUrl` not on the patch host, or whose LAST uuid is the grant token of another patch | nothing discovered (exit 2), zero requests |
//! | record for another package | API record names `@scope/other` for the wired uuid | `record_mismatch` |

use std::path::Path;

use crate::vex_e2e_common;
use vex_e2e_common::*;

const UUID: &str = "6a7b8c9d-0e1f-4a2b-8c3d-4e5f6a7b8c9d";
/// Another canonical uuid (a different patch).
const OTHER_UUID: &str = "7b8c9d0e-1f2a-4b3c-9d4e-5f6a7b8c9d0e";
/// Uuid-shaped grant token (the patch uuid is the LAST uuid segment).
const TOKEN: &str = "11111111-2222-4333-8444-555555555555";
const GHSA: &str = "GHSA-berry-cells-0001";
const CVE: &str = "CVE-2026-7101";
const PRISTINE: &[u8] = b"module.exports = function leftPad() {};\n";
const PATCHED: &[u8] = b"/* SOCKET-PATCHED */\nmodule.exports = function leftPad() {};\n";
const SOCKET: &str = "https://patch.socket.dev";
const ROOT_LOCATOR: &str = "app%40workspace%3A.";

// ── lock writers (the shapes the real yarn 4 / Socket's rewriters write) ──

fn header() -> String {
    "# This file is generated by running \"yarn install\" inside your project.\n\
     # Manual changes might be lost - proceed with caution!\n\n__metadata:\n  \
     version: 8\n  cacheKey: 10c0\n\n"
        .to_string()
}

fn checksum(c: char) -> String {
    format!("10c0/{}", std::iter::repeat_n(c, 128).collect::<String>())
}

/// JavaScript's `encodeURIComponent`.
fn enc(s: &str) -> String {
    let mut out = String::new();
    for b in s.bytes() {
        if b.is_ascii_alphanumeric() || b"-_.!~*'()".contains(&b) {
            out.push(b as char);
        } else {
            out.push_str(&format!("%{b:02X}"));
        }
    }
    out
}

/// The hosted artifact URL for `leaf` (`left-pad-1.3.0.tgz`) on `origin`.
fn hosted_url(origin: &str, uuid: &str, leaf: &str) -> String {
    format!("{origin}/patch/npm/{TOKEN}/{uuid}/{leaf}")
}

/// A berry block resolving `name@version` from a hosted Socket patch.
fn hosted_block(key: &str, name: &str, version: &str, url: &str) -> String {
    format!(
        "\"{key}\":\n  version: {version}\n  resolution: \
         \"{name}@npm:{version}::__archiveUrl={}\"\n  checksum: {}\n  languageName: node\n  \
         linkType: hard\n\n",
        enc(url),
        checksum('7')
    )
}

/// A berry block wiring `name@version` to the committed tarball `rel`
/// (the shape `vendor_yarn_berry` writes).
fn vendored_block(name: &str, version: &str, rel: &str, locator: &str) -> String {
    format!(
        "\"{name}@file:./{rel}::locator={locator}\":\n  version: {version}\n  resolution: \
         \"{name}@file:./{rel}#./{rel}::hash=39ea9b&locator={locator}\"\n  checksum: {}\n  \
         languageName: node\n  linkType: hard\n\n",
        checksum('9')
    )
}

/// The root workspace block depending on `deps` (`name`, `range`).
fn workspace_block(ident: &str, path: &str, deps: &[(&str, &str)]) -> String {
    let mut s = format!(
        "\"{ident}@workspace:{path}\":\n  version: 0.0.0-use.local\n  resolution: \
         \"{ident}@workspace:{path}\"\n"
    );
    if !deps.is_empty() {
        s.push_str("  dependencies:\n");
        for (n, r) in deps {
            s.push_str(&format!("    {n}: \"{r}\"\n"));
        }
    }
    s.push_str("  languageName: unknown\n  linkType: soft\n\n");
    s
}

fn put(root: &Path, rel: &str, bytes: &[u8]) {
    let path = root.join(rel);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, bytes).unwrap();
}

fn project(cwd: &Path, deps: serde_json::Value, resolutions: Option<serde_json::Value>) {
    let mut doc = serde_json::json!({ "name": "app", "version": "1.0.0", "dependencies": deps });
    if let Some(r) = resolutions {
        doc["resolutions"] = r;
    }
    put(cwd, "package.json", doc.to_string().as_bytes());
    put(
        cwd,
        ".yarnrc.yml",
        b"nodeLinker: node-modules\nenableGlobalCache: false\n",
    );
}

/// An installed package dir at `dir` (`node_modules/left-pad`, a `.store`
/// entry, an alias dir) for `name@version` whose `index.js` holds `bytes`.
fn install_at(cwd: &Path, dir: &str, name: &str, version: &str, bytes: &[u8]) {
    put(
        cwd,
        &format!("{dir}/package.json"),
        format!(r#"{{"name":"{name}","version":"{version}"}}"#).as_bytes(),
    );
    put(cwd, &format!("{dir}/index.js"), bytes);
}

fn write_tgz(cwd: &Path, rel: &str, bytes: &[u8]) {
    let mut out = Vec::new();
    {
        let enc = flate2::write::GzEncoder::new(&mut out, flate2::Compression::new(6));
        let mut builder = tar::Builder::new(enc);
        let mut header = tar::Header::new_gnu();
        header.set_size(bytes.len() as u64);
        header.set_mode(0o644);
        header.set_cksum();
        builder
            .append_data(&mut header, "package/index.js", bytes)
            .unwrap();
        builder.into_inner().unwrap().finish().unwrap();
    }
    put(cwd, rel, &out);
}

/// The API view: one file, the REAL before/after hashes (so a pristine
/// install classifies as `not_applied`, anything else as `hash_mismatch`).
fn view(uuid: &str, purl: &str) -> serde_json::Value {
    let mut v = patch_view(
        uuid,
        purl,
        &[("package/index.js", &git_sha256(PATCHED))],
        &[(GHSA, &[CVE])],
    );
    v["files"]["package/index.js"]["beforeHash"] = git_sha256(PRISTINE).into();
    v
}

fn api_for(purl: &str) -> PatchApi {
    PatchApi::start(vec![(UUID.to_string(), view(UUID, purl))])
}

fn attested(out: &VexOutcome, purl: &str, marker: Marker, ctx: &str) {
    assert_eq!(out.code, Some(0), "{ctx}: {out}");
    assert_attested(out.doc(), purl, UUID, marker, &[(GHSA, &[CVE])]);
}

fn omitted(out: &VexOutcome, purl: &str, reason: &str, ctx: &str) {
    assert_eq!(out.code, Some(1), "{ctx}: {out}");
    assert_not_attested(&out.envelope, purl, reason);
    assert!(out.doc.is_none(), "{ctx}: no document");
}

fn nothing_discovered(out: &VexOutcome, ctx: &str) {
    assert_eq!(out.code, Some(2), "{ctx}: {out}");
    assert_eq!(
        out.envelope["error"]["code"], "manifest_not_found",
        "{ctx}: {out}"
    );
    assert!(out.doc.is_none(), "{ctx}");
}

const LP: &str = "pkg:npm/left-pad@1.3.0";

fn lp_hosted_lock(url: &str) -> String {
    format!(
        "{}{}{}",
        header(),
        workspace_block("app", ".", &[("left-pad", "npm:1.3.0")]),
        hosted_block("left-pad@npm:1.3.0", "left-pad", "1.3.0", url)
    )
}

fn vendored_rel(uuid: &str, leaf: &str) -> String {
    format!(".socket/vendor/npm/{uuid}/{leaf}")
}

// ── pnpm linker (unix: the layout is symlinks) ──────────────────────────

/// `nodeLinker: pnpm` installs into `node_modules/.store/<name>-npm-<v>-<h>/
/// package` and exposes it through a symlink: the installed tree VEX
/// hashes is the store copy, reached through the link.
#[cfg(unix)]
#[test]
fn pnpm_linker_store_layout() {
    let store = "node_modules/.store/left-pad-npm-1.3.0-abc123/package";
    let link = |cwd: &Path| {
        std::fs::create_dir_all(cwd.join("node_modules")).unwrap();
        let _ = std::fs::remove_file(cwd.join("node_modules/left-pad"));
        std::os::unix::fs::symlink(
            ".store/left-pad-npm-1.3.0-abc123/package",
            cwd.join("node_modules/left-pad"),
        )
        .unwrap();
    };

    // hosted
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    project(cwd, serde_json::json!({ "left-pad": "1.3.0" }), None);
    put(
        cwd,
        ".yarnrc.yml",
        b"nodeLinker: pnpm\nenableGlobalCache: false\n",
    );
    put(
        cwd,
        "yarn.lock",
        lp_hosted_lock(&hosted_url(SOCKET, UUID, "left-pad-1.3.0.tgz")).as_bytes(),
    );
    let api = api_for(LP);
    for (bytes, expect) in [
        (PATCHED, None),
        (&b"/* tampered store copy */\n"[..], Some("hash_mismatch")),
        (PRISTINE, Some("not_applied")),
    ] {
        install_at(cwd, store, "left-pad", "1.3.0", bytes);
        link(cwd);
        let out = run_vex(&binary(), cwd, &VexRun::online(&api));
        let ctx = format!("pnpm-linker hosted {expect:?}");
        match expect {
            None => attested(&out, LP, Marker::Redirected, &ctx),
            Some(reason) => omitted(&out, LP, reason, &ctx),
        }
    }

    // vendored: the store entry is `left-pad-file-<hash>`, but the committed
    // artifact is the evidence whatever the store holds.
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    let rel = vendored_rel(UUID, "left-pad-1.3.0.tgz");
    write_tgz(cwd, &rel, PATCHED);
    project(
        cwd,
        serde_json::json!({ "left-pad": "1.3.0" }),
        Some(serde_json::json!({ "left-pad": format!("file:./{rel}") })),
    );
    put(
        cwd,
        ".yarnrc.yml",
        b"nodeLinker: pnpm\nenableGlobalCache: false\n",
    );
    put(
        cwd,
        "yarn.lock",
        format!(
            "{}{}{}",
            header(),
            workspace_block("app", ".", &[("left-pad", "npm:1.3.0")]),
            vendored_block("left-pad", "1.3.0", &rel, ROOT_LOCATOR)
        )
        .as_bytes(),
    );
    install_at(
        cwd,
        "node_modules/.store/left-pad-file-9f8e7d/package",
        "left-pad",
        "1.3.0",
        PATCHED,
    );
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(&out, LP, Marker::Vendored, "pnpm-linker vendored");
    write_tgz(cwd, &rel, b"/* tampered artifact */\n");
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    omitted(
        &out,
        LP,
        "vendor_hash_mismatch",
        "pnpm-linker vendored tampered",
    );
}

// ── workspaces ───────────────────────────────────────────────────────────

fn workspace_project(cwd: &Path, root_resolutions: Option<serde_json::Value>) {
    let mut root = serde_json::json!({
        "name": "ws-root", "version": "0.0.0", "private": true,
        "workspaces": ["packages/app"],
    });
    if let Some(r) = root_resolutions {
        root["resolutions"] = r;
    }
    put(cwd, "package.json", root.to_string().as_bytes());
    put(
        cwd,
        "packages/app/package.json",
        br#"{"name":"app","version":"1.0.0","dependencies":{"left-pad":"1.3.0"}}"#,
    );
    put(
        cwd,
        ".yarnrc.yml",
        b"nodeLinker: node-modules\nenableGlobalCache: false\n",
    );
}

fn workspace_lock(dep_block: &str) -> String {
    format!(
        "{}{}{}{}",
        header(),
        workspace_block("app", "packages/app", &[("left-pad", "npm:1.3.0")]),
        dep_block,
        workspace_block("ws-root", ".", &[])
    )
}

/// A workspace MEMBER's dependency is wired by the single root lock (and,
/// vendored, the ROOT `resolutions` — the only place berry honors them).
#[test]
fn workspace_member_dependency() {
    let api = api_for(LP);

    // hosted, hoisted to the root node_modules
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    workspace_project(cwd, None);
    put(
        cwd,
        "yarn.lock",
        workspace_lock(&hosted_block(
            "left-pad@npm:1.3.0",
            "left-pad",
            "1.3.0",
            &hosted_url(SOCKET, UUID, "left-pad-1.3.0.tgz"),
        ))
        .as_bytes(),
    );
    install_at(cwd, "node_modules/left-pad", "left-pad", "1.3.0", PATCHED);
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(&out, LP, Marker::Redirected, "workspace hosted");

    // vendored, every root selector spelling
    let rel = vendored_rel(UUID, "left-pad-1.3.0.tgz");
    let locator = "ws-root%40workspace%3A.";
    for selector in ["left-pad", "**/left-pad", "app/left-pad", "left-pad@1.3.0"] {
        let tmp = tempfile::tempdir().unwrap();
        let cwd = tmp.path();
        workspace_project(
            cwd,
            Some(serde_json::json!({ selector: format!("file:./{rel}") })),
        );
        write_tgz(cwd, &rel, PATCHED);
        put(
            cwd,
            "yarn.lock",
            workspace_lock(&vendored_block("left-pad", "1.3.0", &rel, locator)).as_bytes(),
        );
        let out = run_vex(&binary(), cwd, &VexRun::online(&api));
        attested(
            &out,
            LP,
            Marker::Vendored,
            &format!("workspace vendored selector {selector:?}"),
        );
    }

    // A `resolutions` entry in the MEMBER package.json is ignored by berry:
    // the lock's `file:` entry is orphaned, so it is no wiring — nothing is
    // discovered, and a vendor ledger for it is unwired.
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    workspace_project(cwd, None);
    put(
        cwd,
        "packages/app/package.json",
        serde_json::json!({
            "name": "app", "version": "1.0.0",
            "dependencies": { "left-pad": "1.3.0" },
            "resolutions": { "left-pad": format!("file:./{rel}") },
        })
        .to_string()
        .as_bytes(),
    );
    write_tgz(cwd, &rel, PATCHED);
    put(
        cwd,
        "yarn.lock",
        workspace_lock(&vendored_block("left-pad", "1.3.0", &rel, locator)).as_bytes(),
    );
    let before = api.request_count();
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    nothing_discovered(&out, "member-only resolutions");
    assert_eq!(
        api.request_count(),
        before,
        "member-only resolutions: no fetch"
    );
    write_vendor_ledger(cwd, LP, &rel);
    for no_verify in [false, true] {
        let out = run_vex(
            &binary(),
            cwd,
            &VexRun {
                no_verify,
                ..VexRun::offline()
            },
        );
        omitted(
            &out,
            LP,
            "vendor_unwired",
            &format!("member-only resolutions + ledger, no_verify={no_verify}"),
        );
    }
}

/// A minimal vendor ledger claiming `purl` at `rel` (embedded record).
fn write_vendor_ledger(cwd: &Path, purl: &str, rel: &str) {
    let state = serde_json::json!({
        "version": 1,
        "entries": { purl: {
            "ecosystem": "npm",
            "basePurl": purl,
            "uuid": UUID,
            "artifact": { "path": rel, "sha256": "" },
            "wiring": [
                { "file": "package.json", "kind": "yarn_berry_resolution", "action": "rewritten", "key": "left-pad" },
                { "file": "yarn.lock", "kind": "yarn_berry_lock_entry", "action": "rewritten", "key": "left-pad" }
            ],
            "detached": false,
            "flavor": "yarn-berry",
            "record": {
                "uuid": UUID,
                "exportedAt": "2026-03-27T00:00:00Z",
                "files": { "package/index.js": {
                    "beforeHash": git_sha256(PRISTINE), "afterHash": git_sha256(PATCHED)
                }},
                "vulnerabilities": { GHSA: {
                    "cves": [CVE], "summary": "s", "severity": "high", "description": "d"
                }},
                "description": "d", "license": "MIT", "tier": "free"
            }
        }}
    });
    put(
        cwd,
        ".socket/vendor/state.json",
        serde_json::to_string_pretty(&state).unwrap().as_bytes(),
    );
}

// ── scoped package ───────────────────────────────────────────────────────

#[test]
fn scoped_package_hosted_and_vendored() {
    // The API spells the scope percent-encoded, and so does the OpenVEX
    // subcomponent (the canonical purl form); envelope events carry the
    // decoded `@scope` spelling discovery derived from the lock when there
    // is no record, and the record's spelling once there is one.
    let purl = "pkg:npm/%40scope/pkg@2.0.0";
    let event_purl = "pkg:npm/@scope/pkg@2.0.0";
    let api = api_for(purl);

    // hosted
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    project(cwd, serde_json::json!({ "@scope/pkg": "2.0.0" }), None);
    put(
        cwd,
        "yarn.lock",
        format!(
            "{}{}{}",
            header(),
            hosted_block(
                "@scope/pkg@npm:2.0.0",
                "@scope/pkg",
                "2.0.0",
                &hosted_url(SOCKET, UUID, "pkg-2.0.0.tgz")
            ),
            workspace_block("app", ".", &[("@scope/pkg", "npm:2.0.0")])
        )
        .as_bytes(),
    );
    let before = api.request_count();
    let out = run_vex(&binary(), cwd, &VexRun::offline());
    omitted(
        &out,
        event_purl,
        "record_unavailable",
        "scoped hosted offline",
    );
    assert_eq!(api.request_count(), before, "offline: zero requests");
    // Not installed: the `10c0` pin is the evidence.
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(
        &out,
        purl,
        Marker::Redirected,
        "scoped hosted, not installed",
    );
    install_at(
        cwd,
        "node_modules/@scope/pkg",
        "@scope/pkg",
        "2.0.0",
        PATCHED,
    );
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(&out, purl, Marker::Redirected, "scoped hosted, installed");
    install_at(
        cwd,
        "node_modules/@scope/pkg",
        "@scope/pkg",
        "2.0.0",
        PRISTINE,
    );
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    omitted(&out, purl, "not_applied", "scoped hosted, pristine install");

    // vendored: `.socket/vendor/npm/<uuid>/@scope/pkg-2.0.0.tgz`
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    let rel = vendored_rel(UUID, "@scope/pkg-2.0.0.tgz");
    write_tgz(cwd, &rel, PATCHED);
    project(
        cwd,
        serde_json::json!({ "@scope/pkg": "2.0.0" }),
        Some(serde_json::json!({ "@scope/pkg": format!("file:./{rel}") })),
    );
    put(
        cwd,
        "yarn.lock",
        format!(
            "{}{}{}",
            header(),
            vendored_block("@scope/pkg", "2.0.0", &rel, ROOT_LOCATOR),
            workspace_block("app", ".", &[("@scope/pkg", "npm:2.0.0")])
        )
        .as_bytes(),
    );
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(&out, purl, Marker::Vendored, "scoped vendored");

    // The API record names ANOTHER package for the wired uuid.
    let liar = PatchApi::start(vec![(
        UUID.to_string(),
        view(UUID, "pkg:npm/%40scope/other@2.0.0"),
    )]);
    let out = run_vex(&binary(), cwd, &VexRun::online(&liar));
    omitted(
        &out,
        event_purl,
        "record_mismatch",
        "scoped vendored, record for another package",
    );
}

// ── npm alias ────────────────────────────────────────────────────────────

/// `"lp": "npm:left-pad@1.3.0"`: the lock key carries the alias, the
/// resolution (and the installed `package.json`) the real package, so the
/// REAL package is what is attested — from the alias's install dir.
///
/// Socket's own hosted rewriter refuses alias entries
/// (`redirect_yarn_berry_alias_skipped`, observed against the real yarn 4),
/// so this wiring is hand-written or another tool's — exactly the committed,
/// tamperable input VEX must not take on faith.
#[test]
fn npm_alias_dependency() {
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    project(cwd, serde_json::json!({ "lp": "npm:left-pad@1.3.0" }), None);
    put(
        cwd,
        "yarn.lock",
        format!(
            "{}{}{}",
            header(),
            workspace_block("app", ".", &[("lp", "npm:left-pad@1.3.0")]),
            hosted_block(
                "lp@npm:left-pad@1.3.0",
                "left-pad",
                "1.3.0",
                &hosted_url(SOCKET, UUID, "left-pad-1.3.0.tgz")
            )
        )
        .as_bytes(),
    );
    let api = api_for(LP);
    install_at(cwd, "node_modules/lp", "left-pad", "1.3.0", PATCHED);
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(&out, LP, Marker::Redirected, "alias installed patched");
    install_at(
        cwd,
        "node_modules/lp",
        "left-pad",
        "1.3.0",
        b"/* tampered */\n",
    );
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    omitted(&out, LP, "hash_mismatch", "alias installed tampered");
    // REGRESSION: a STALE alias install (the lock was redirected but the
    // tree never reinstalled) is the registry's pristine bytes — installed
    // evidence, so never excused as "not installed" by the lock pin.
    install_at(cwd, "node_modules/lp", "left-pad", "1.3.0", PRISTINE);
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    omitted(&out, LP, "not_applied", "alias installed pristine (stale)");
    // With no install at all, the pin is the evidence again.
    std::fs::remove_dir_all(cwd.join("node_modules")).unwrap();
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(&out, LP, Marker::Redirected, "alias not installed");
}

// ── lock spellings ───────────────────────────────────────────────────────

/// One block for several descriptors, CRLF line endings and a leading BOM
/// (a Windows checkout) — the pin still attests.
#[test]
fn multi_descriptor_key_crlf_and_bom() {
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    project(cwd, serde_json::json!({ "left-pad": "^1.3.0" }), None);
    let lock = format!(
        "\u{feff}{}{}{}",
        header(),
        workspace_block("app", ".", &[("left-pad", "npm:^1.3.0")]),
        hosted_block(
            "left-pad@npm:^1.0.0, left-pad@npm:^1.3.0",
            "left-pad",
            "1.3.0",
            &hosted_url(SOCKET, UUID, "left-pad-1.3.0.tgz")
        )
    )
    .replace('\n', "\r\n");
    put(cwd, "yarn.lock", lock.as_bytes());
    let api = api_for(LP);
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(&out, LP, Marker::Redirected, "multi-descriptor CRLF BOM");
}

/// Two LIVE blocks wiring the same package version to two different
/// patches: which one yarn installs is not the lock's to say, so neither is
/// attested.
#[test]
fn two_uuids_for_one_package_are_a_conflict() {
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    project(cwd, serde_json::json!({ "left-pad": "^1.0.0" }), None);
    put(
        cwd,
        "yarn.lock",
        format!(
            "{}{}{}{}",
            header(),
            workspace_block("app", ".", &[("left-pad", "npm:^1.0.0")]),
            hosted_block(
                "left-pad@npm:^1.0.0",
                "left-pad",
                "1.3.0",
                &hosted_url(SOCKET, UUID, "left-pad-1.3.0.tgz")
            ),
            hosted_block(
                "left-pad@npm:1.3.0",
                "left-pad",
                "1.3.0",
                &hosted_url(SOCKET, OTHER_UUID, "left-pad-1.3.0.tgz")
            )
        )
        .as_bytes(),
    );
    install_at(cwd, "node_modules/left-pad", "left-pad", "1.3.0", PATCHED);
    let api = PatchApi::start(vec![
        (UUID.to_string(), view(UUID, LP)),
        (OTHER_UUID.to_string(), view(OTHER_UUID, LP)),
    ]);
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    omitted(&out, LP, "wiring_conflict", "two uuids for one package");
}

/// A user `yarn patch` on top of Socket's hosted patch: yarn keeps the
/// hosted base entry and adds a `patch:` entry wrapping its locator. The
/// `patch:` entry is not Socket's (silently skipped); the base entry is,
/// and the installed tree (base + the user's patch) decides.
#[test]
fn user_yarn_patch_on_top_of_hosted() {
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    project(
        cwd,
        serde_json::json!({ "left-pad": "patch:left-pad@npm%3A1.3.0#~/.yarn/patches/left-pad-npm-1.3.0-0123456789.patch" }),
        None,
    );
    let url = hosted_url(SOCKET, UUID, "left-pad-1.3.0.tgz");
    let inner = format!("npm:1.3.0::__archiveUrl={}", enc(&url));
    let patch_block = format!(
        "\"left-pad@patch:left-pad@npm%3A1.3.0#~/.yarn/patches/left-pad-npm-1.3.0-0123456789.patch\":\n  \
         version: 1.3.0\n  resolution: \"left-pad@patch:left-pad@{}#~/.yarn/patches/left-pad-npm-1.3.0-0123456789.patch::version=1.3.0&hash=abcdef\"\n  \
         checksum: {}\n  languageName: node\n  linkType: hard\n\n",
        enc(&inner),
        checksum('5')
    );
    put(
        cwd,
        "yarn.lock",
        format!(
            "{}{}{}{}",
            header(),
            workspace_block(
                "app",
                ".",
                &[(
                    "left-pad",
                    "patch:left-pad@npm%3A1.3.0#~/.yarn/patches/left-pad-npm-1.3.0-0123456789.patch"
                )]
            ),
            hosted_block("left-pad@npm:1.3.0", "left-pad", "1.3.0", &url),
            patch_block
        )
        .as_bytes(),
    );
    let api = api_for(LP);
    // The user's patch touched another file: the Socket-patched file is
    // intact in the installed tree.
    install_at(cwd, "node_modules/left-pad", "left-pad", "1.3.0", PATCHED);
    put(
        cwd,
        "node_modules/left-pad/README.md",
        b"user-patched readme\n",
    );
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    attested(&out, LP, Marker::Redirected, "user patch elsewhere");
    // The user's patch rewrote the Socket-patched file: not attested.
    install_at(
        cwd,
        "node_modules/left-pad",
        "left-pad",
        "1.3.0",
        b"/* user yarn patch */\nmodule.exports = 1;\n",
    );
    let out = run_vex(&binary(), cwd, &VexRun::online(&api));
    omitted(&out, LP, "hash_mismatch", "user patch rewrote the file");
}

// ── spoofing ─────────────────────────────────────────────────────────────

/// An `__archiveUrl` that is not on the Socket patch host — including
/// look-alikes — or whose uuid-shaped segments are only a GRANT TOKEN of
/// the patch host's path grammar, is never a patch reference: nothing is
/// discovered and nothing is fetched.
#[test]
fn foreign_hosts_and_token_only_urls_are_not_references() {
    let api = api_for(LP);
    for url in [
        hosted_url("https://evil.example", UUID, "left-pad-1.3.0.tgz"),
        hosted_url(
            "https://patch.socket.dev.evil.example",
            UUID,
            "left-pad-1.3.0.tgz",
        ),
        hosted_url(
            "https://patch.socket.dev@evil.example",
            UUID,
            "left-pad-1.3.0.tgz",
        ),
        hosted_url(
            "http://patch.socket.dev:8080.evil.example",
            UUID,
            "left-pad-1.3.0.tgz",
        ),
        // The uuid only in a query string / fragment of a foreign URL.
        format!("https://evil.example/left-pad-1.3.0.tgz?patch={UUID}"),
        format!("https://evil.example/left-pad-1.3.0.tgz#{UUID}"),
    ] {
        let tmp = tempfile::tempdir().unwrap();
        let cwd = tmp.path();
        project(cwd, serde_json::json!({ "left-pad": "1.3.0" }), None);
        put(cwd, "yarn.lock", lp_hosted_lock(&url).as_bytes());
        install_at(cwd, "node_modules/left-pad", "left-pad", "1.3.0", PATCHED);
        let before = api.request_count();
        let out = run_vex(&binary(), cwd, &VexRun::online(&api));
        nothing_discovered(&out, &url);
        assert_eq!(api.request_count(), before, "{url}: network call made");
    }
}
