//! Manifest-less VEX for yarn classic (`# yarn lockfile v1`) — hermetic cells
//! over the lock shapes the REAL yarn 1.x releases write, hosted AND vendored,
//! with no `.socket/manifest.json` and no ledgers.
//!
//! The real-yarn capstones (`e2e_redirect_yarn_classic_build`,
//! `e2e_vendor_yarn_classic_build`, `e2e_vendor_yarn_classic_dev_flow`,
//! `mode_migration_npm`) prove the happy path per release; the berry-and-
//! classic grammar matrix is `e2e_vex_lockfile::yarn`. This suite pins what
//! only a hand-built tree can reach, on every OS with no toolchain:
//!
//! * the release-dependent pin: yarn >= 1.10 locks carry `integrity sha512-…`;
//!   1.0–1.9 (and any 1.x lock a pre-1.10 yarn re-saved) pin by the
//!   `#<sha1>` fragment of `resolved` alone — a hosted entry nothing installed
//!   attests from EITHER pin, and from neither when the lock has none;
//! * installed pristine / tampered trees and a tampered vendored tarball
//!   member are omitted (the installed/committed bytes win over the lock);
//! * a uuid-shaped segment on a non-Socket host (or look-alike host) is no
//!   reference at all — nothing discovered, zero API requests;
//! * a patch record whose purl or uuid disagrees with the lock is
//!   `record_mismatch`;
//! * real-yarn key spellings: multi-pattern block headers, scoped names,
//!   CRLF (a Windows checkout with `core.autocrlf`).

use crate::vex_e2e_common;

use std::path::Path;

use serde_json::Value;
use vex_e2e_common::*;

const UUID: &str = "6f708192-a3b4-4c5d-9e6f-708192a3b4c5";
const OTHER_UUID: &str = "708192a3-b4c5-4d6e-8f70-8192a3b4c5d6";
/// uuid-shaped grant token: the patch uuid is the LAST uuid segment.
const TOKEN: &str = "22222222-3333-4444-8555-666666666666";
const NAME: &str = "left-pad";
const VERSION: &str = "1.3.0";
const PURL: &str = "pkg:npm/left-pad@1.3.0";
const GHSA: &str = "GHSA-yc1a-ssic-vex1";
const CVE: &str = "CVE-2026-7101";
const MEMBER: &str = "package/index.js";
const PRISTINE: &[u8] = b"module.exports = leftPad;\n";
const PATCHED: &[u8] = b"/* SOCKET-PATCHED */\nmodule.exports = leftPad;\n";
const SHA1: &str = "5b8a3a7765dfe001261dde915589e782f8c94d1e";
const SRI: &str = "sha512-UEFUQ0hFRHBhdGNoZWRQQVRDSEVEcGF0Y2hlZA==";

const HEADER: &str =
    "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n";

/// Which integrity pin the block carries — the release that wrote it.
#[derive(Clone, Copy, Debug)]
enum Pin {
    /// yarn >= 1.10: `#sha1` fragment AND an `integrity` line.
    Integrity,
    /// yarn 1.0–1.9: the `#sha1` fragment only.
    Sha1Only,
    /// Hand-edited: neither.
    None,
}

fn hosted_url(origin: &str, name: &str, uuid: &str) -> String {
    let leaf = name.rsplit('/').next().unwrap();
    format!("{origin}/patch/npm/{name}/{VERSION}/{TOKEN}/{uuid}/{leaf}-{VERSION}.tgz")
}

/// One classic block `key` resolving to `resolved` with `pin`.
fn block(key: &str, resolved: &str, pin: Pin) -> String {
    let (fragment, integrity) = match pin {
        Pin::Integrity => (format!("#{SHA1}"), format!("  integrity {SRI}\n")),
        Pin::Sha1Only => (format!("#{SHA1}"), String::new()),
        Pin::None => (String::new(), String::new()),
    };
    format!("{key}:\n  version \"{VERSION}\"\n  resolved \"{resolved}{fragment}\"\n{integrity}")
}

fn put(root: &Path, rel: &str, bytes: &[u8]) {
    let path = root.join(rel);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, bytes).unwrap();
}

fn project(cwd: &Path, name: &str, lock: &str) {
    put(
        cwd,
        "package.json",
        serde_json::json!({"name": "app", "version": "1.0.0", "dependencies": { name: VERSION }})
            .to_string()
            .as_bytes(),
    );
    put(cwd, "yarn.lock", lock.as_bytes());
}

/// The hosted lock `scan --mode hosted` writes on `origin`, as a given
/// release leaves it.
fn hosted(cwd: &Path, origin: &str, pin: Pin) {
    let lock = format!(
        "{HEADER}{}",
        block(
            &format!("{NAME}@{VERSION}"),
            &hosted_url(origin, NAME, UUID),
            pin
        )
    );
    project(cwd, NAME, &lock);
}

fn vendored_rel() -> String {
    format!(".socket/vendor/npm/{UUID}/{NAME}-{VERSION}.tgz")
}

/// Single-member `.tgz`.
fn member_tgz(dest: &Path, member: &str, bytes: &[u8]) {
    std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
    let mut out = Vec::new();
    {
        let enc = flate2::write::GzEncoder::new(&mut out, flate2::Compression::new(6));
        let mut builder = tar::Builder::new(enc);
        let mut header = tar::Header::new_gnu();
        header.set_size(bytes.len() as u64);
        header.set_mode(0o644);
        header.set_cksum();
        builder.append_data(&mut header, member, bytes).unwrap();
        builder.into_inner().unwrap().finish().unwrap();
    }
    std::fs::write(dest, &out).unwrap();
}

/// The vendored lock `vendor` writes (`file:./…#sha1` + integrity), as a
/// given release leaves it, with the committed tarball holding `artifact`.
fn vendored(cwd: &Path, pin: Pin, artifact: &[u8]) {
    let rel = vendored_rel();
    member_tgz(&cwd.join(&rel), MEMBER, artifact);
    let lock = format!(
        "{HEADER}{}",
        block(&format!("{NAME}@{VERSION}"), &format!("file:./{rel}"), pin)
    );
    project(cwd, NAME, &lock);
}

fn install(cwd: &Path, name: &str, bytes: &[u8]) {
    put(
        cwd,
        &format!("node_modules/{name}/package.json"),
        format!(r#"{{"name":"{name}","version":"{VERSION}"}}"#).as_bytes(),
    );
    put(cwd, &format!("node_modules/{name}/index.js"), bytes);
}

/// The patch view, with the real `beforeHash` (so a pristine install reads
/// as `not_applied`, not a mismatch).
fn view(uuid: &str, purl: &str) -> Value {
    let mut v = patch_view(
        uuid,
        purl,
        &[(MEMBER, &git_sha256(PATCHED))],
        &[(GHSA, &[CVE])],
    );
    v["files"][MEMBER]["beforeHash"] = Value::String(git_sha256(PRISTINE));
    v
}

fn api() -> PatchApi {
    PatchApi::start(vec![(UUID.to_string(), view(UUID, PURL))])
}

fn vex(cwd: &Path, run: &VexRun) -> VexOutcome {
    let out = run_vex(&binary(), cwd, run);
    assert!(
        !cwd.join(".socket/manifest.json").exists(),
        "vex never writes a manifest"
    );
    out
}

fn attested(out: &VexOutcome, purl: &str, marker: Marker, cell: &str) {
    assert_eq!(out.code, Some(0), "{cell}:\n{out}");
    assert_attested(out.doc(), purl, UUID, marker, &[(GHSA, &[CVE])]);
}

fn omitted(out: &VexOutcome, purl: &str, reason: &str, cell: &str) {
    assert_eq!(out.code, Some(1), "{cell}:\n{out}");
    assert_eq!(
        out.envelope["error"]["code"], "no_applicable_patches",
        "{cell}:\n{out}"
    );
    assert_not_attested(&out.envelope, purl, reason);
    assert!(out.doc.is_none(), "{cell}: a failed run leaves no document");
}

// ── release-dependent pins ────────────────────────────────────────────

/// Hosted, nothing installed (a lockfile-only CI checkout): the lock pin is
/// the evidence. yarn >= 1.10's `integrity` line and yarn 1.0–1.9's bare
/// `#sha1` fragment both pin; a hand-edited entry with neither does not.
/// Once installed, the tree is what counts: patched attests, pristine and
/// tampered are omitted, whatever the pin.
#[test]
fn hosted_pins_of_every_classic_release() {
    for pin in [Pin::Integrity, Pin::Sha1Only, Pin::None] {
        let tmp = tempfile::tempdir().unwrap();
        let cwd = tmp.path();
        hosted(cwd, "https://patch.socket.dev", pin);
        let api = api();
        let cell = format!("hosted {pin:?}, not installed");
        let out = vex(cwd, &VexRun::online(&api));
        match pin {
            Pin::Integrity | Pin::Sha1Only => attested(&out, PURL, Marker::Redirected, &cell),
            Pin::None => omitted(&out, PURL, "package_not_found", &cell),
        }

        install(cwd, NAME, PATCHED);
        let out = vex(cwd, &VexRun::online(&api));
        attested(
            &out,
            PURL,
            Marker::Redirected,
            &format!("hosted {pin:?}, installed patched"),
        );

        install(cwd, NAME, PRISTINE);
        let out = vex(cwd, &VexRun::online(&api));
        omitted(
            &out,
            PURL,
            "not_applied",
            &format!("hosted {pin:?}, installed pristine"),
        );

        install(cwd, NAME, b"tampered\n");
        let out = vex(cwd, &VexRun::online(&api));
        omitted(
            &out,
            PURL,
            "hash_mismatch",
            &format!("hosted {pin:?}, installed tampered"),
        );
    }
}

/// Vendored: the committed tarball is the evidence, whichever release wrote
/// the pin (pre-1.10 re-saves drop the `integrity` line) — and a tampered
/// member is omitted even though the lock still wires it. The installed
/// tree plays no part (yarn < 1.7 installs nothing for a `file:` entry).
#[test]
fn vendored_pins_of_every_classic_release_and_tampered_member() {
    for pin in [Pin::Integrity, Pin::Sha1Only] {
        let tmp = tempfile::tempdir().unwrap();
        let cwd = tmp.path();
        vendored(cwd, pin, PATCHED);
        let api = api();
        let out = vex(cwd, &VexRun::online(&api));
        attested(&out, PURL, Marker::Vendored, &format!("vendored {pin:?}"));

        member_tgz(&cwd.join(vendored_rel()), MEMBER, b"tampered\n");
        let out = vex(cwd, &VexRun::online(&api));
        omitted(
            &out,
            PURL,
            "vendor_hash_mismatch",
            &format!("vendored {pin:?}, tampered member"),
        );
    }
}

// ── spoofing ──────────────────────────────────────────────────────────

/// A uuid-shaped segment on a host that is not Socket's patch server (nor
/// the operator's `--patch-server-url`) is the user's own tarball source:
/// nothing is discovered (`manifest_not_found`, exit 2) and the patch API is
/// never asked about the uuid. The same lock on the configured origin IS a
/// reference.
#[test]
fn uuid_on_a_non_socket_host_is_nothing() {
    for origin in [
        "https://evil.example",
        "https://patch.socket.dev.evil.example",
        "https://patch.socket.dev@evil.example",
        "https://evil.example/patch.socket.dev",
    ] {
        let tmp = tempfile::tempdir().unwrap();
        let cwd = tmp.path();
        hosted(cwd, origin, Pin::Integrity);
        let api = api();
        let out = vex(cwd, &VexRun::online(&api));
        assert_eq!(out.code, Some(2), "{origin}:\n{out}");
        assert_eq!(
            out.envelope["error"]["code"], "manifest_not_found",
            "{origin}:\n{out}"
        );
        assert_absent(out.doc.as_ref(), PURL);
        api.assert_no_requests();
    }

    // The operator's own patch server counts once named.
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    let api = api();
    hosted(cwd, &api.uri(), Pin::Integrity);
    let out = vex(
        cwd,
        &VexRun {
            patch_server_url: Some(api.uri()),
            ..VexRun::online(&api)
        },
    );
    attested(
        &out,
        PURL,
        Marker::Redirected,
        "configured patch server origin",
    );
}

/// The record the API serves for the wired uuid names another package,
/// another version or another patch: never attested, hosted and vendored.
#[test]
fn record_disagreeing_with_the_lock_is_a_mismatch() {
    for (what, body) in [
        ("another package", view(UUID, "pkg:npm/minimist@1.2.5")),
        ("another version", view(UUID, "pkg:npm/left-pad@1.2.0")),
        ("another uuid", view(OTHER_UUID, PURL)),
    ] {
        for mode in ["hosted", "vendored"] {
            let tmp = tempfile::tempdir().unwrap();
            let cwd = tmp.path();
            if mode == "hosted" {
                hosted(cwd, "https://patch.socket.dev", Pin::Integrity);
                install(cwd, NAME, PATCHED);
            } else {
                vendored(cwd, Pin::Integrity, PATCHED);
            }
            let api = PatchApi::start(vec![(UUID.to_string(), body.clone())]);
            let out = vex(cwd, &VexRun::online(&api));
            omitted(&out, PURL, "record_mismatch", &format!("{mode}: {what}"));
        }
    }
}

// ── real-yarn key spellings ───────────────────────────────────────────

/// yarn merges every range that resolves to one version into ONE block with
/// a comma-separated, partly quoted header; scoped names are always quoted.
/// Each is one reference.
#[test]
fn multi_pattern_and_scoped_headers() {
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    let lock = format!(
        "{HEADER}{}",
        block(
            &format!("\"{NAME}@^1.3.0\", {NAME}@{VERSION}, \"{NAME}@~1.3.0\""),
            &hosted_url("https://patch.socket.dev", NAME, UUID),
            Pin::Integrity
        )
    );
    project(cwd, NAME, &lock);
    let api = api();
    let out = vex(cwd, &VexRun::online(&api));
    attested(&out, PURL, Marker::Redirected, "multi-pattern header");
    assert_eq!(
        statements_for(out.doc(), PURL).len(),
        1,
        "one statement:\n{out}"
    );

    let scoped = "@acme/left-pad";
    let scoped_purl = "pkg:npm/%40acme/left-pad@1.3.0";
    let tmp = tempfile::tempdir().unwrap();
    let cwd = tmp.path();
    let lock = format!(
        "{HEADER}{}",
        block(
            &format!("\"{scoped}@{VERSION}\""),
            &hosted_url("https://patch.socket.dev", scoped, UUID),
            Pin::Integrity
        )
    );
    project(cwd, scoped, &lock);
    let api = PatchApi::start(vec![(UUID.to_string(), view(UUID, scoped_purl))]);
    let out = vex(cwd, &VexRun::online(&api));
    attested(&out, scoped_purl, Marker::Redirected, "scoped header");
}

/// A Windows checkout (`core.autocrlf=true`) turns every lock line into
/// CRLF: hosted and vendored references are still read, and the reverted
/// (registry) CRLF lock still wires nothing.
#[test]
fn crlf_checkouts() {
    for mode in ["hosted", "vendored"] {
        let tmp = tempfile::tempdir().unwrap();
        let cwd = tmp.path();
        let marker = if mode == "hosted" {
            hosted(cwd, "https://patch.socket.dev", Pin::Integrity);
            Marker::Redirected
        } else {
            vendored(cwd, Pin::Integrity, PATCHED);
            Marker::Vendored
        };
        let lock = std::fs::read_to_string(cwd.join("yarn.lock")).unwrap();
        std::fs::write(cwd.join("yarn.lock"), lock.replace('\n', "\r\n")).unwrap();
        let api = api();
        let out = vex(cwd, &VexRun::online(&api));
        attested(&out, PURL, marker, &format!("{mode} CRLF"));

        let registry = format!(
            "{HEADER}{}",
            block(
                &format!("{NAME}@{VERSION}"),
                "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz",
                Pin::Integrity
            )
        );
        std::fs::write(cwd.join("yarn.lock"), registry.replace('\n', "\r\n")).unwrap();
        let out = vex(cwd, &VexRun::online(&api));
        assert_eq!(out.code, Some(2), "{mode} CRLF reverted:\n{out}");
        assert_absent(out.doc.as_ref(), PURL);
    }
}
