# socket-patch Bundler plugin (published-gem form).
#
# Keeps the gem patches recorded in .socket/manifest.json applied on every
# `bundle install` — including a cached/no-op install — by re-running the
# socket-patch CLI. This is the Phase-2 published-gem counterpart of the in-tree
# plugin generated by `socket-patch setup` under .socket/bundler-plugin/; the
# applier logic is identical, but because a published plugin is loaded from the
# gem cache (not from inside the repo) it resolves the project root from the
# bundle context rather than relative to its own location.
#
# Two complementary triggers feed one idempotent applier:
#   * load-time — evaluated during Bundler's Gemfile pass on EVERY `bundle`
#     invocation, covering the cached/no-op install the after-install-all hook
#     would miss;
#   * the `after-install-all` hook — fires after the installer finishes,
#     covering the fresh install where gems exist only afterwards.
#
# A digest of (manifest + every committed file under .socket/ + Gemfile.lock)
# gates the load-time work. The stamp lives under Bundler.bundle_path so it
# travels WITH the gems. On any patch failure it raises Bundler::BundlerError so
# the build breaks loudly rather than shipping stale/unpatched gems. The
# socket-patch CLI must be on PATH (or pointed at by SOCKET_PATCH_BIN).

require "digest"
require "fileutils"

module SocketPatch
  BIN_ENV = "SOCKET_PATCH_BIN".freeze
  STAMP_NAME = ".socket-patch-gem-stamp".freeze

  module_function

  # A published plugin is loaded from the gem cache, so the project root (where
  # the Gemfile / .socket/ live) is resolved from the bundle context: prefer
  # `Bundler.root` (the Gemfile's directory), then walk up from the working
  # directory to a dir containing .socket/manifest.json, else fall back to cwd.
  def project_root
    begin
      return Bundler.root.to_s if defined?(Bundler) && Bundler.respond_to?(:root) && Bundler.root
    rescue StandardError
      # Bundler.root raises outside a bundle context — fall through to the walk.
    end
    dir = Dir.pwd
    loop do
      return dir if File.file?(File.join(dir, ".socket", "manifest.json"))
      parent = File.dirname(dir)
      break if parent == dir
      dir = parent
    end
    Dir.pwd
  end

  def manifest_path
    File.join(project_root, ".socket", "manifest.json")
  end

  def socket_bin
    env = ENV[BIN_ENV]
    env && !env.empty? ? env : "socket-patch"
  end

  # Files whose change must force a reapply: the manifest, every committed file
  # under .socket/ (patch blobs etc.), and Gemfile.lock.
  def digest_inputs
    inputs = [manifest_path]
    lock = File.join(project_root, "Gemfile.lock")
    inputs << lock if File.file?(lock)
    socket_dir = File.join(project_root, ".socket")
    if File.directory?(socket_dir)
      Dir.glob(File.join(socket_dir, "**", "*")).sort.each do |p|
        inputs << p if File.file?(p)
      end
    end
    inputs.uniq
  end

  def current_digest
    d = Digest::SHA256.new
    digest_inputs.each do |path|
      d.update(path)
      d.update("\0")
      begin
        d.update(File.binread(path))
      rescue StandardError
        # Unreadable now -> contributes only its path; a later readable state
        # changes the digest and forces a reapply.
      end
      d.update("\0")
    end
    d.hexdigest
  end

  def bundle_path
    Bundler.bundle_path.to_s
  rescue StandardError
    File.join(project_root, "vendor", "bundle")
  end

  def stamp_path
    File.join(bundle_path, STAMP_NAME)
  end

  def stamped?(digest)
    File.file?(stamp_path) && File.read(stamp_path).strip == digest
  rescue StandardError
    false
  end

  def write_stamp(digest)
    FileUtils.mkdir_p(File.dirname(stamp_path))
    File.write(stamp_path, digest)
  rescue StandardError
    # Best-effort: a missing/unwritable stamp just means we re-probe next time.
  end

  def fail!(message)
    raise(defined?(Bundler::BundlerError) ? Bundler::BundlerError.new(message) : message)
  end

  # Idempotent, missing-gem-tolerant. No manifest -> the project does not use
  # socket-patch, nothing to do. When `force` is false the digest stamp short-
  # circuits already-applied state; the after-install-all hook passes force:true
  # because the installer just changed the on-disk gem set.
  def apply!(force: false)
    return unless File.file?(manifest_path)

    digest = current_digest
    return if !force && stamped?(digest)

    ok = system(
      socket_bin, "apply",
      "--ecosystems", "gem", "--offline", "--silent",
      "--cwd", project_root
    )

    if ok.nil?
      fail!(
        "socket-patch: could not run `#{socket_bin} apply` to apply gem patches; " \
        "the socket-patch CLI is required. Install it or set #{BIN_ENV} to its path."
      )
    elsif !ok
      fail!(
        "socket-patch: `#{socket_bin} apply --ecosystems gem` failed; the gem patches " \
        "in .socket/manifest.json are NOT applied. The build was failed to avoid " \
        "shipping unpatched gems."
      )
    end

    write_stamp(digest)
  end
end

# Trigger 1 — load-time (covers the cached/no-op `bundle install`).
begin
  SocketPatch.apply!
rescue StandardError => e
  raise if defined?(Bundler::BundlerError) && e.is_a?(Bundler::BundlerError)
end

# Trigger 2 — after the installer finishes (covers the fresh install). Forced,
# because the install just changed the gem set; the applier is idempotent.
Bundler::Plugin.add_hook("after-install-all") do |_install|
  SocketPatch.apply!(force: true)
end
