# socket-patch Bundler plugin (published-gem form).
#
# Keeps the gem patches recorded in .socket/manifest.json applied by
# re-running the socket-patch CLI whenever Bundler touches the gem set. This
# is the Phase-2 published-gem counterpart of the in-tree plugin generated by
# `socket-patch setup` under .socket/bundler-plugin/; the applier logic is
# identical, but because a published plugin is loaded from the gem cache (not
# from inside the repo) it resolves the project root from the bundle context
# rather than relative to its own location.
#
# When each trigger actually runs (verified against bundler 2.7 and 4.0; hook
# subscriptions are recorded in .bundle/plugin/index at plugin REGISTRATION,
# and bundler evaluates this file whenever a subscribed event first fires in a
# bundle process):
#
#   * plugin registration — the FIRST `bundle install` evaluates this file
#     BEFORE any project gem is installed, so the load-time trigger is
#     bootstrap-gated (no patch target exists yet) and quietly no-ops there;
#     the install hooks below re-apply once the gems land.
#   * every `bundle install` — fresh AND fully cached — fires the per-gem
#     `after-install` events and then `after-install-all`; the forced
#     `after-install-all` re-apply is the actual patch point.
#   * `bundle pristine` fires ONLY the per-gem `after-install` events, so that
#     digest-gated hook is what catches pristine's patch reversion in the same
#     run. (A checkout registered by an older plugin version keeps its old
#     subscription set until it re-registers — fresh clones and CI always
#     re-register, a dev checkout can `rm -rf .bundle/plugin`.)
#   * nothing fires on `bundle exec` / `bundle check` / plain `ruby`, and
#     `gem pristine` bypasses bundler entirely — a reversion via those is only
#     healed at the NEXT `bundle install`.
#
# A digest of (manifest + every committed file under .socket/ + Gemfile.lock +
# the on-disk content of every gem-patch target file) gates the non-forced
# triggers. The stamp is a pure digest cache at .socket/gem-plugin-stamp —
# machine-local state, safe to gitignore or delete (deleting only forces one
# re-probe); a stale copy that reaches version control anyway is harmless on
# a fresh clone, because the bootstrap gate keys on the patch targets
# existing on disk, never on the stamp. Older plugin versions stamped a
# fixed-name file under Bundler.bundle_path (machine-global when no bundle
# path is configured); that legacy stamp is deleted best-effort when seen.
#
# A patch failure NEVER breaks `bundle install`: it prints a warning naming
# what failed and the remediation. Set SOCKET_PATCH_STRICT=1 to restore
# raise-on-failure (Bundler::BundlerError). The socket-patch CLI must be on
# PATH (or pointed at by SOCKET_PATCH_BIN).

require "digest"
require "fileutils"
require "json"

module SocketPatch
  # Bundler evaluates this file twice in a bootstrap install (registration +
  # first hook load), so constant assignments are guarded against re-runs.
  BIN_ENV = "SOCKET_PATCH_BIN".freeze unless defined?(BIN_ENV)
  STRICT_ENV = "SOCKET_PATCH_STRICT".freeze unless defined?(STRICT_ENV)
  STAMP_NAME = "gem-plugin-stamp".freeze unless defined?(STAMP_NAME)
  LEGACY_STAMP_NAME = ".socket-patch-gem-stamp".freeze unless defined?(LEGACY_STAMP_NAME)
  # Bundler's parallel installer can fire per-gem hooks from worker threads;
  # one applier runs at a time so a single bundle process never races
  # concurrent `socket-patch apply` children against each other.
  APPLY_LOCK = Mutex.new unless defined?(APPLY_LOCK)

  module_function

  # A published plugin is loaded from the gem cache, so the project root (where
  # the Gemfile / .socket/ live) is resolved from the bundle context: prefer
  # `Bundler.root` (the Gemfile's directory), then walk up from the working
  # directory to a dir containing .socket/manifest.json, else fall back to cwd.
  def project_root
    begin
      return Bundler.root.to_s if defined?(Bundler) && Bundler.respond_to?(:root) && Bundler.root
    rescue StandardError
      # Bundler.root raises outside a bundle context — fall through to the walk.
    end
    dir = Dir.pwd
    loop do
      return dir if File.file?(File.join(dir, ".socket", "manifest.json"))
      parent = File.dirname(dir)
      break if parent == dir
      dir = parent
    end
    Dir.pwd
  end

  def socket_dir
    File.join(project_root, ".socket")
  end

  def manifest_path
    File.join(socket_dir, "manifest.json")
  end

  def socket_bin
    env = ENV[BIN_ENV]
    env && !env.empty? ? env : "socket-patch"
  end

  def strict?
    %w[1 true].include?(ENV[STRICT_ENV].to_s)
  end

  def bundle_path
    Bundler.bundle_path.to_s
  rescue StandardError
    File.join(project_root, "vendor", "bundle")
  end

  def stamp_path
    File.join(socket_dir, STAMP_NAME)
  end

  # The on-disk files the manifest's gem patches target:
  # <bundle_path>/gems/<name>-<version>[-<platform>]/<file key sans package/>.
  # Paths are collected whether or not the file exists — `current_digest`
  # folds an absence marker, so a gem appearing or vanishing flips the digest.
  def patch_target_files
    records = begin
      JSON.parse(File.read(manifest_path)).fetch("patches", {})
    rescue StandardError
      return []
    end
    return [] unless records.is_a?(Hash)
    gems_dir = File.join(bundle_path, "gems")
    # Dir.glob treats `\` as an escape on EVERY platform, so a Windows-style
    # bundle path (Bundler.bundle_path carries backslash separators through
    # verbatim) would never match the platform-gem wildcard below: platform
    # installs (nokogiri-1.15.0-x64-mingw-ucrt) drop out of the digest and a
    # `bundle pristine` reversion of them leaves the stamp matching. Forward
    # slashes are valid separators on Windows, so normalize the GLOB BASE
    # only — the direct join below is not a pattern and stays byte-faithful.
    glob_gems_dir = gems_dir.tr("\\", "/")
    targets = []
    records.each do |purl, record|
      next unless purl.is_a?(String) && purl.start_with?("pkg:gem/")
      coordinate = purl.split("pkg:gem/", 2).last.split("?", 2).first
      name, at, version = coordinate.rpartition("@")
      next if at.empty? || name.empty? || version.empty?
      files = record.is_a?(Hash) ? record["files"] : nil
      next unless files.is_a?(Hash)
      files.each_key do |key|
        rel = key.to_s.sub(%r{\Apackage/}, "")
        targets << File.join(gems_dir, "#{name}-#{version}", rel)
        targets.concat(Dir.glob(File.join(glob_gems_dir, "#{name}-#{version}-*", rel)))
      end
    end
    targets.uniq.sort
  end

  # Files whose change must force a reapply: the manifest, every committed file
  # under .socket/ (patch blobs etc. — the stamp itself excluded, or each write
  # would invalidate the digest it records), Gemfile.lock, and the current
  # on-disk state of every patch target.
  def digest_inputs
    inputs = [manifest_path]
    lock = File.join(project_root, "Gemfile.lock")
    inputs << lock if File.file?(lock)
    if File.directory?(socket_dir)
      Dir.glob(File.join(socket_dir, "**", "*")).sort.each do |p|
        inputs << p if File.file?(p) && p != stamp_path
      end
    end
    inputs.concat(patch_target_files)
    inputs.uniq
  end

  def current_digest
    d = Digest::SHA256.new
    digest_inputs.each do |path|
      d.update(path)
      d.update("\0")
      d.update(File.file?(path) ? "+" : "-")
      begin
        d.update(File.binread(path))
      rescue StandardError
        # Unreadable now -> contributes only its path + absence marker; a later
        # readable state changes the digest and forces a reapply.
      end
      d.update("\0")
    end
    d.hexdigest
  end

  def stamped?(digest)
    File.file?(stamp_path) && File.read(stamp_path).strip == digest
  rescue StandardError
    false
  end

  def write_stamp(digest)
    FileUtils.mkdir_p(File.dirname(stamp_path))
    File.write(stamp_path, digest)
  rescue StandardError
    # Best-effort: a missing/unwritable stamp just means we re-probe next time.
  end

  # Older plugin versions stamped under Bundler.bundle_path. It is never read
  # anymore; delete it (best-effort, once per process) so it does not linger
  # as an orphan in a shared gem dir.
  def remove_legacy_stamp
    return if @legacy_stamp_checked
    @legacy_stamp_checked = true
    legacy = File.join(bundle_path, LEGACY_STAMP_NAME)
    File.delete(legacy) if File.file?(legacy)
  rescue StandardError
    # Best-effort cleanup only.
  end

  # Tolerant by default: a patch failure must never break `bundle install` —
  # the first install of a fresh checkout runs the applier before any project
  # gem exists, and raising there deadlocks the project on its own bootstrap
  # (plugin registration fails, so every retry fails identically). Warn once
  # per process with the remediation; SOCKET_PATCH_STRICT=1 restores the raise
  # for builds that must not proceed unpatched. The trailer states what the
  # ACTIVE mode does — the strict raise must not claim the install continues.
  def failure_trailer
    if strict?
      "Failing `bundle install` because #{STRICT_ENV} is set; unset it to " \
        "warn and continue instead."
    else
      "`bundle install` continues; set #{STRICT_ENV}=1 to make patch " \
        "failures fatal."
    end
  end

  def report_failure(message)
    message = "#{message} #{failure_trailer}"
    if strict?
      raise(defined?(Bundler::BundlerError) ? Bundler::BundlerError.new(message) : message)
    end
    return if @warned
    @warned = true
    warn(message)
  end

  # Idempotent applier behind every trigger. No manifest -> the project does
  # not use socket-patch, nothing to do.
  # force: skip the digest gate (the installer just changed the gem set).
  # bootstrap_gate: bail while NONE of the manifest's gem-patch targets exist
  # on disk. The load-time trigger and the per-gem after-install hook use it
  # so a bootstrap install's early evaluations (plugin REGISTRATION runs
  # before any project gem lands) never shell out, warn, or — in strict mode —
  # raise while there is nothing to patch; the forced after-install-all pass
  # does the first real apply once the gems exist. The gate reads only the
  # live gem tree, never the stamp: a stale stamp committed by mistake cannot
  # re-open the bootstrap deadlock on a fresh clone, and deleting the stamp
  # costs one re-probe instead of disabling these triggers.
  def apply!(force: false, bootstrap_gate: false)
    APPLY_LOCK.synchronize do
      return unless File.file?(manifest_path)
      remove_legacy_stamp
      return if bootstrap_gate && patch_target_files.none? { |t| File.file?(t) }
      return if !force && stamped?(current_digest)

      ok = system(
        socket_bin, "apply",
        "--ecosystems", "gem", "--offline", "--silent",
        "--cwd", project_root
      )

      if ok.nil?
        report_failure(
          "socket-patch: could not run `#{socket_bin} apply` — the gem patches in " \
          ".socket/manifest.json are NOT applied. Install the socket-patch CLI (or set " \
          "#{BIN_ENV} to its path), then run `socket-patch apply --ecosystems gem` " \
          "manually."
        )
        return
      elsif !ok
        report_failure(
          "socket-patch: `#{socket_bin} apply --ecosystems gem` failed — the gem patches " \
          "in .socket/manifest.json may NOT be applied. Run `socket-patch apply " \
          "--ecosystems gem` in #{project_root} to apply them manually."
        )
        return
      end

      if @warned
        @warned = false
        warn("socket-patch: gem patches applied; the earlier warning is resolved.")
      end
      # Recompute: the apply just rewrote the target files the digest folds in.
      write_stamp(current_digest)
    end
  end
end

# Trigger 1 — load time. Runs at plugin registration and whenever a subscribed
# hook event first loads the plugin in a bundle process. Bootstrap-gated on
# the patch targets existing on disk (never on the stamp — a committed stale
# stamp must not re-open the registration deadlock): on the bootstrap install
# no gems exist to patch, so this quietly defers to Trigger 3. In strict mode
# a genuine patch failure (Bundler::BundlerError) still propagates.
begin
  SocketPatch.apply!(bootstrap_gate: true)
rescue StandardError => e
  raise if defined?(Bundler::BundlerError) && e.is_a?(Bundler::BundlerError)
end

# Trigger 2 — after each individual gem (re)install. The only event bundler
# fires during `bundle pristine`, so this is what catches pristine's patch
# reversion in the same run — even when the stamp was deleted, since the gate
# reads the gem tree, not the stamp. Digest- and bootstrap-gated: on a fresh
# install's per-gem events the targets are only just landing and Trigger 3 is
# about to do the real work.
Bundler::Plugin.add_hook("after-install") do |_spec_install|
  SocketPatch.apply!(bootstrap_gate: true)
end

# Trigger 3 — after the installer finishes (fresh AND fully-cached installs).
# Forced, because the install just changed the gem set; the applier is
# idempotent so a redundant run on an already-patched tree is a cheap no-op.
Bundler::Plugin.add_hook("after-install-all") do |_install|
  SocketPatch.apply!(force: true)
end
