//! Shared `poetry.lock` rewriter for hosted (URL source) and vendored (file
//! source) patches across every lock generation Poetry has written:
//!
//! * format `"0"` — Poetry 0.12: no `lock-version`, hashes in `[metadata.hashes]`
//! * `"1.0"` / `"1.1"` — Poetry 1.0–1.2: per-package files in `[metadata.files]`
//! * `"2.x"` — Poetry 1.3+: `files = [...]` inside each `[[package]]`
//!
//! Every edit is computed on a parsed `toml_edit` document and then spliced
//! back into the ORIGINAL text as verbatim fragment replacements, so untouched
//! bytes (formatting, comments, line endings) survive and rollback can replay
//! the recorded fragments. A malformed lock (user-editable input) must never
//! panic: every table access here is guarded and degrades to an `Err`, which
//! callers surface as a refusal warning.

use toml_edit::{value, Array, DocumentMut, InlineTable, Item, Table, Value};

use crate::crawlers::python_crawler::canonicalize_pypi_name;

/// The lock generation: `"0"`, `"1.0"`, `"1.1"`, or any `"2.<minor>"` (Poetry
/// bumps the minor additively — 2.0 → 2.1 kept every shape we rewrite, and the
/// vendored loader already accepts newer minors with an advisory; the hosted
/// path must not refuse what the vendored path accepts).
pub fn lock_version(lock: &DocumentMut) -> Result<&str, String> {
    let metadata = lock
        .get("metadata")
        .filter(|item| item.is_table_like())
        .ok_or("missing Poetry lock metadata")?;
    match metadata.get("lock-version").and_then(Item::as_str) {
        Some(version @ ("1.0" | "1.1")) => Ok(version),
        Some(version) if is_2x(version) => Ok(version),
        Some(version) => Err(format!(
            "unsupported Poetry lock-version {version:?} (supported: legacy metadata.hashes, 1.0, \
             1.1 and 2.x)"
        )),
        None if metadata
            .get("hashes")
            .and_then(Item::as_table_like)
            .is_some() =>
        {
            Ok("0")
        }
        None => Err("poetry.lock has neither a [metadata] lock-version nor a [metadata.hashes] table".into()),
    }
}

fn is_2x(version: &str) -> bool {
    version
        .strip_prefix("2.")
        .is_some_and(|minor| !minor.is_empty() && minor.bytes().all(|b| b.is_ascii_digit()))
}

/// The `# This file is automatically @generated by Poetry X.Y.Z …` header
/// Poetry writes from 1.4 on (1.3 writes the sentence without a version).
/// Advisory only — a lock can be consumed by a different Poetry than the one
/// that wrote it — but it lets warnings about the WRITER's installer be
/// precise instead of blaming every lock-2.0 project for Poetry 1.3.
pub fn generated_by_version(lock_text: &str) -> Option<(u64, u64)> {
    let first = lock_text.lines().next()?;
    let rest = first.split("@generated by Poetry ").nth(1)?;
    let version = rest.split_whitespace().next()?;
    let mut parts = version.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    Some((major, minor))
}

/// Whether `existing` is an earlier hosted redirect of the SAME artifact:
/// same origin (`scheme://host[:port]`) and same trailing filename as the
/// current artifact URL, fragments ignored. Grant tokens and patch uuids live
/// in the path between them, so a rotated token or a republished patch is
/// superseded in place instead of stranding the pin on a URL that no longer
/// serves (the bun / requirements / cargo rewriters make the same call).
fn is_prior_hosted_url(existing: &str, current: &str) -> bool {
    fn origin_and_leaf(url: &str) -> Option<(&str, &str)> {
        if !url.starts_with("https://") && !url.starts_with("http://") {
            return None;
        }
        let url = url.split('#').next()?;
        let scheme_end = url.find("://")? + 3;
        let path_start = url[scheme_end..].find('/')? + scheme_end;
        let leaf = url[path_start..]
            .rsplit('/')
            .next()
            .filter(|leaf| !leaf.is_empty())?;
        Some((&url[..path_start], leaf))
    }
    match (origin_and_leaf(existing), origin_and_leaf(current)) {
        (Some(old), Some(new)) => old == new,
        _ => false,
    }
}

/// Rewrite the `[[package]]` for `name`@`version` to install the wheel at
/// `source_url` (`source_type` `"url"` for hosted, `"file"` for vendored),
/// pinning `sha256`. Returns `Ok(None)` when the lock has no such entry (or
/// resolves another version) — the caller decides whether that is a warning.
/// Returns `Err` for inputs the rewriter must refuse without writing.
pub fn rewrite_poetry_lock(
    text: &str,
    name: &str,
    version: &str,
    source_type: &str,
    source_url: &str,
    filename: &str,
    sha256: &str,
) -> Result<Option<String>, String> {
    if !matches!(source_type, "file" | "url")
        || sha256.len() != 64
        || !sha256.bytes().all(|byte| byte.is_ascii_hexdigit())
    {
        return Err("invalid Poetry artifact source or SHA-256".into());
    }
    // Poetry compares the lock's `sha256:<hex>` against `hashlib`'s lowercase
    // hexdigest as strings, so an uppercase digest would fail every install.
    let sha256 = sha256.to_ascii_lowercase();
    if filename.contains(['/', '\\']) || !filename.ends_with(".whl") {
        return Err("Poetry patch wheel does not match the locked package".into());
    }
    let parts: Vec<_> = filename.split('-').collect();
    if !matches!(parts.len(), 5 | 6)
        || canonicalize_pypi_name(parts[0]) != canonicalize_pypi_name(name)
        || parts[1] != version
    {
        return Err("Poetry patch wheel does not match the locked package".into());
    }
    let mut lock: DocumentMut = text
        .parse()
        .map_err(|e| format!("invalid Poetry lock: {e}"))?;
    let format = lock_version(&lock)?.to_string();
    if format == "0" && source_type == "url" {
        return Err("Poetry 0.x ignores URL sources; hosted patches require Poetry >= 1.0".into());
    }
    let effective_url = if format == "1.0" && source_type == "url" {
        // Poetry 1.0 hands pip `<url>#egg=<name>` unconditionally; the trailing
        // `&` keeps `sha256=<hex>` a complete fragment parameter when `#egg=`
        // is appended (pip >= 22 would otherwise read `<hex>#egg=<name>` as the
        // digest and hard-fail the install).
        format!("{source_url}#sha256={sha256}&")
    } else {
        source_url.to_string()
    };
    let packages = lock
        .get_mut("package")
        .and_then(Item::as_array_of_tables_mut)
        .ok_or("missing Poetry packages")?;
    let indices: Vec<_> = packages
        .iter()
        .enumerate()
        .filter(|(_, package)| {
            package
                .get("name")
                .and_then(Item::as_str)
                .is_some_and(|candidate| {
                    canonicalize_pypi_name(candidate) == canonicalize_pypi_name(name)
                })
        })
        .map(|(index, _)| index)
        .collect();
    if indices.is_empty() {
        return Ok(None);
    }
    if indices.len() != 1 {
        return Err("forked Poetry package requires an unambiguous source".into());
    }
    let package = packages
        .get_mut(indices[0])
        .ok_or("missing Poetry package")?;
    if package.get("version").and_then(Item::as_str) != Some(version) {
        return Ok(None);
    }
    let package_name = package
        .get("name")
        .and_then(Item::as_str)
        .unwrap_or(name)
        .to_string();
    if let Some(source) = package.get("source") {
        let existing_type = source.get("type").and_then(Item::as_str);
        let existing_url = source.get("url").and_then(Item::as_str).unwrap_or("");
        let same_target = existing_type == Some(source_type) && existing_url == effective_url;
        let prior_hosted = source_type == "url"
            && existing_type == Some("url")
            && is_prior_hosted_url(existing_url, &effective_url);
        if !same_target && !prior_hosted {
            return Err(format!(
                "refusing to replace an existing Poetry source ({} {}) for {package_name}",
                existing_type.unwrap_or("unknown"),
                existing_url
            ));
        }
    }
    let mut entry = InlineTable::new();
    entry.insert("file", Value::from(filename));
    entry.insert("hash", Value::from(format!("sha256:{sha256}")));
    let mut files = Array::new();
    files.push(entry);
    let mut source = Table::new();
    source.insert("type", value(source_type));
    source.insert("url", value(effective_url));
    if matches!(format.as_str(), "0" | "1.0") {
        // Poetry 0.12 / 1.0 read `source.reference` unconditionally (KeyError
        // without it), even for archive sources.
        source.insert("reference", value(""));
    }
    package.insert("source", Item::Table(source));
    if format == "1.1" && source_type == "url" {
        // Poetry 1.2 (a lock-1.1 writer) verifies url sources against the
        // package's own `files`, Poetry 1.1 against `metadata.files` — write
        // both so either installer enforces the patched hash.
        package.insert("files", value(files.clone()));
    }
    if format.starts_with('2') {
        package.insert("files", value(files));
    } else {
        let field = if format == "0" { "hashes" } else { "files" };
        let table = lock
            .get_mut("metadata")
            .and_then(Item::as_table_like_mut)
            .ok_or("missing Poetry lock metadata")?
            .get_mut(field)
            .ok_or_else(|| format!("missing Poetry integrity table [metadata.{field}]"))?
            .as_table_like_mut()
            .ok_or_else(|| format!("[metadata.{field}] is not a table"))?;
        if format == "0" {
            let mut hashes = Array::new();
            hashes.push(sha256.as_str());
            table.insert(&package_name, value(hashes));
        } else {
            table.insert(&package_name, value(files));
        }
    }
    let mut rewritten = lock.to_string();
    if text.contains("\r\n") {
        rewritten = rewritten.replace("\r\n", "\n").replace('\n', "\r\n");
    }
    let edits = poetry_lock_edits(text, &rewritten, name)?;
    let mut result = text.to_string();
    for (original, replacement) in edits {
        result = result.replacen(&original, &replacement, 1);
    }
    Ok(Some(result))
}

/// The verbatim `(original, replacement)` fragments that turn `original` into
/// `rewritten` for `name`: the package's `[[package]]` unit (with its
/// sub-tables) and, for legacy formats, its `[metadata.files]` /
/// `[metadata.hashes]` entry. Each fragment must occur exactly once on both
/// sides so a textual splice — and its rollback — can never hit the wrong
/// place.
pub fn poetry_lock_edits(
    original: &str,
    rewritten: &str,
    name: &str,
) -> Result<Vec<(String, String)>, String> {
    fn fragments(text: &str, name: &str) -> Result<Vec<String>, String> {
        let lock = toml_edit::Document::parse(text).map_err(|e| e.to_string())?;
        let package = lock
            .get("package")
            .and_then(Item::as_array_of_tables)
            .and_then(|packages| {
                packages.iter().find(|package| {
                    package
                        .get("name")
                        .and_then(Item::as_str)
                        .is_some_and(|value| {
                            canonicalize_pypi_name(value) == canonicalize_pypi_name(name)
                        })
                })
            })
            .ok_or("missing Poetry package")?;
        fn extend_span(table: &Table, span: &mut std::ops::Range<usize>) {
            if let Some(own) = table.span() {
                span.start = span.start.min(own.start);
                span.end = span.end.max(own.end);
            }
            for (_, item) in table.iter() {
                if let Some(own) = item.span() {
                    span.start = span.start.min(own.start);
                    span.end = span.end.max(own.end);
                }
                if let Some(child) = item.as_table() {
                    extend_span(child, span);
                }
            }
        }
        let mut span = package.span().ok_or("missing Poetry package span")?;
        extend_span(package, &mut span);
        span.end += text[span.end..]
            .find(['\r', '\n'])
            .unwrap_or(text.len() - span.end);
        let mut result = vec![text[span].to_string()];
        let metadata = lock
            .get("metadata")
            .filter(|item| item.is_table_like())
            .ok_or("missing Poetry metadata")?;
        let format = metadata
            .get("lock-version")
            .and_then(Item::as_str)
            .unwrap_or("0");
        if !format.starts_with('2') {
            let field = if format == "0" { "hashes" } else { "files" };
            let table = metadata
                .get(field)
                .and_then(Item::as_table)
                .ok_or_else(|| format!("missing Poetry integrity table [metadata.{field}]"))?;
            let package_name = package
                .get("name")
                .and_then(Item::as_str)
                .ok_or("missing package name")?;
            let key_start = table
                .key(package_name)
                .and_then(|key| key.span())
                .ok_or("missing Poetry integrity key")?
                .start;
            // Anchor the fragment at the preceding line break so a
            // suffix-named sibling entry (`pyurllib3 = […]` vs `urllib3 = […]`)
            // holding the same value can never contain it.
            let start = text[..key_start].rfind('\n').unwrap_or(key_start);
            let end = table
                .get(package_name)
                .and_then(Item::span)
                .ok_or("missing Poetry integrity span")?
                .end;
            result.push(text[start..end].to_string());
        }
        Ok(result)
    }
    let before = fragments(original, name)?;
    let after = fragments(rewritten, name)?;
    let mut edits = Vec::new();
    for (old, new) in before.into_iter().zip(after) {
        if old == new {
            continue;
        }
        if original.matches(&old).count() != 1 || rewritten.matches(&new).count() != 1 {
            return Err("ambiguous Poetry rollback fragment".into());
        }
        edits.push((old, new));
    }
    Ok(edits)
}

#[cfg(test)]
mod tests {
    use super::*;

    const WHEEL: &str = "urllib3-1.26.18-py2.py3-none-any.whl";
    const URL: &str = "https://patch.socket.dev/patch/pypi/urllib3/1.26.18/7e52b8b6-53f2-4dc8-860a-1ae7ebd8be0e/e828efa5-5c6d-43f3-9909-03f5ac232b98/urllib3-1.26.18-py2.py3-none-any.whl";

    fn fixture(version: &str) -> String {
        std::fs::read_to_string(format!(
            "{}/tests/fixtures/poetry/{version}/poetry.lock",
            env!("CARGO_MANIFEST_DIR")
        ))
        .unwrap()
        .replace("\r\n", "\n")
    }

    fn sha() -> String {
        "a".repeat(64)
    }

    fn hosted(text: &str) -> Result<Option<String>, String> {
        rewrite_poetry_lock(text, "urllib3", "1.26.18", "url", URL, WHEEL, &sha())
    }

    /// A user-editable lock with a malformed integrity table must be refused,
    /// never panic (it used to `IndexMut` straight into `metadata.files`).
    #[test]
    fn malformed_integrity_tables_are_refused_without_panicking() {
        let lock = fixture("1.2.2");
        let array_of_tables = lock.replace("[metadata.files]", "[[metadata.files]]");
        let scalar = {
            let start = lock.find("[metadata.files]").unwrap();
            format!("{}files = \"oops\"\n", &lock[..start])
        };
        let missing = {
            let start = lock.find("\n[metadata.files]").unwrap();
            lock[..start + 1].to_string()
        };
        let metadata_array = lock.replace("[metadata]", "[[metadata]]");
        for (label, text) in [
            ("array-of-tables", array_of_tables),
            ("scalar", scalar),
            ("missing", missing),
            ("metadata-array", metadata_array),
        ] {
            match hosted(&text) {
                Err(err) => assert!(!err.is_empty(), "{label}"),
                Ok(other) => panic!("{label}: expected a refusal, got {other:?}"),
            }
            // The vendored (file-source) spelling takes the same guarded path.
            match rewrite_poetry_lock(&text, "urllib3", "1.26.18", "file", ".socket/vendor/pypi/x/urllib3-1.26.18-py2.py3-none-any.whl", WHEEL, &sha()) {
                Err(err) => assert!(!err.is_empty(), "{label}"),
                Ok(other) => panic!("{label}: expected a refusal, got {other:?}"),
            }
        }
    }

    /// Poetry bumps the 2.x minor additively; the vendored loader accepts a
    /// newer minor with an advisory, so the shared rewriter must too — the
    /// same lock used to be applied (LF vendored), hard-failed (CRLF vendored)
    /// and silently skipped (hosted) depending only on the path taken.
    #[test]
    fn newer_2x_minor_is_rewritten_like_2_1() {
        let lock = fixture("2.4.3").replace("lock-version = \"2.1\"", "lock-version = \"2.2\"");
        let rewritten = hosted(&lock).unwrap().unwrap();
        assert!(rewritten.contains(URL));
        assert!(rewritten.contains("lock-version = \"2.2\""));
        for bad in ["3.0", "2", "2.x", "1.2"] {
            let lock = fixture("2.4.3").replace("lock-version = \"2.1\"", &format!("lock-version = \"{bad}\""));
            let err = hosted(&lock).unwrap_err();
            assert!(err.contains(bad), "{bad}: {err}");
        }
    }

    /// An earlier hosted redirect of the same wheel (rotated grant token,
    /// republished patch) is superseded in place; a foreign url source is not.
    #[test]
    fn prior_hosted_url_is_superseded_but_foreign_sources_are_refused() {
        let lock = fixture("2.4.3");
        let first = hosted(&lock).unwrap().unwrap();
        let rotated = URL.replace("7e52b8b6", "00000000");
        let second =
            rewrite_poetry_lock(&first, "urllib3", "1.26.18", "url", &rotated, WHEEL, &sha())
                .unwrap()
                .unwrap();
        assert!(second.contains(&rotated) && !second.contains(URL));
        // Idempotent: the same URL again changes nothing.
        assert_eq!(hosted(&first).unwrap().unwrap(), first);
        // Poetry 1.0 carries a `#sha256=…&` fragment; the comparison ignores it.
        let lock10 = fixture("1.0.10");
        let first10 = hosted(&lock10).unwrap().unwrap();
        let second10 = rewrite_poetry_lock(&first10, "urllib3", "1.26.18", "url", &rotated, WHEEL, &"b".repeat(64))
            .unwrap()
            .unwrap();
        assert!(second10.contains(&format!("{rotated}#sha256={}&", "b".repeat(64))));
        // A user's own url source on another origin stays untouched.
        let foreign = first.replace("https://patch.socket.dev", "https://mirror.example");
        assert!(hosted(&foreign).unwrap_err().contains("existing Poetry source"));
        // A vendored file source is never taken over by the hosted path here.
        let vendored = rewrite_poetry_lock(&lock, "urllib3", "1.26.18", "file", ".socket/vendor/pypi/x/urllib3-1.26.18-py2.py3-none-any.whl", WHEEL, &sha())
            .unwrap()
            .unwrap();
        assert!(hosted(&vendored).unwrap_err().contains("existing Poetry source"));
    }

    #[test]
    fn sha256_is_written_lowercase() {
        let lock = fixture("2.4.3");
        let upper = "A".repeat(64);
        let rewritten =
            rewrite_poetry_lock(&lock, "urllib3", "1.26.18", "url", URL, WHEEL, &upper)
                .unwrap()
                .unwrap();
        assert!(rewritten.contains(&format!("sha256:{}", "a".repeat(64))));
        assert!(!rewritten.contains(&upper));
    }

    /// The `[metadata.files]` fragment is anchored at its line break, so a
    /// sibling whose key ends in the same characters and holds the same value
    /// cannot make the splice ambiguous.
    #[test]
    fn suffix_named_sibling_with_identical_integrity_does_not_refuse() {
        let lock = fixture("1.2.2");
        let files_entry = {
            let start = lock.find("urllib3 = [\n").unwrap();
            let end = lock[start..].find("\n]\n").unwrap() + start + 3;
            lock[start..end].to_string()
        };
        let sibling = files_entry.replacen("urllib3 = [", "pyurllib3 = [", 1);
        let lock = format!("{lock}{sibling}");
        let rewritten = hosted(&lock).unwrap().unwrap();
        assert!(rewritten.contains(URL));
        assert!(rewritten.contains(&sibling), "sibling entry must survive verbatim");
        let edits = poetry_lock_edits(&lock, &rewritten, "urllib3").unwrap();
        assert_eq!(edits.len(), 2);
        assert!(edits[1].0.starts_with('\n'));
    }

    #[test]
    fn absent_or_other_version_yields_none_not_error() {
        let lock = fixture("2.4.3");
        assert_eq!(
            rewrite_poetry_lock(&lock, "six", "1.16.0", "url", &URL.replace("urllib3", "six").replace("1.26.18", "1.16.0"), "six-1.16.0-py2.py3-none-any.whl", &sha()).unwrap(),
            None
        );
        assert_eq!(
            rewrite_poetry_lock(&lock, "urllib3", "1.26.17", "url", &URL.replace("1.26.18", "1.26.17"), "urllib3-1.26.17-py2.py3-none-any.whl", &sha()).unwrap(),
            None
        );
    }

    #[test]
    fn generated_by_header_is_parsed_when_present() {
        assert_eq!(generated_by_version(&fixture("1.8.5")), Some((1, 8)));
        assert_eq!(generated_by_version(&fixture("2.4.3")), Some((2, 4)));
        assert_eq!(generated_by_version(&fixture("1.3.2")), None);
        assert_eq!(generated_by_version(&fixture("1.2.2")), None);
    }
}
