//! Gem (Bundler) `setup` support: wire a Ruby project for automatic patching.
//!
//! Bundler loads a declared **plugin** whenever one of its subscribed hook
//! events fires — on every `bundle install`, fresh AND fully cached (verified
//! against bundler 2.7 and 4.0). So setup delivers the gate as a generated,
//! git-committed Bundler plugin plus a `plugin` directive in the Gemfile:
//!
//!   * `.socket/bundler-plugin/{plugins.rb, socket-patch.gemspec}` — a generated
//!     plugin whose `plugins.rb` re-runs `socket-patch apply --ecosystems gem`
//!     on every `bundle install` (digest-gated load-time + per-gem
//!     `after-install` triggers, forced `after-install-all` re-apply). A patch
//!     failure warns with a remediation and lets the install continue —
//!     bundler evaluates `plugins.rb` at plugin REGISTRATION, before any
//!     project gem is installed, so raising there would deadlock a fresh
//!     clone on its own first `bundle install` (plugin registration fails and
//!     every retry fails identically). `SOCKET_PATCH_STRICT=1` restores
//!     raise-on-failure (`Bundler::BundlerError`);
//!   * a managed block appended to the `Gemfile` that references the plugin via
//!     `plugin "socket-patch", path: File.expand_path(".socket/bundler-plugin",
//!     __dir__)`. The source must be `path:` — Bundler fetches `git:` plugin
//!     sources with `git clone`, and the generated dir is a plain directory
//!     (committing it to the parent repo does not give it a `.git`), so `git:`
//!     fails every `bundle install`. The directory still must be committed so
//!     clones and CI have the plugin on disk;
//!   * a `.socket/.gitignore` entry for the plugin's digest stamp
//!     (`gem-plugin-stamp`) — everything else under `.socket/` is meant to be
//!     committed, and an untracked stamp in every wired repo's `git status`
//!     invites a `git add .socket` that ships one machine's digest to every
//!     clone.
//!
//! The actual gem patching is done by `apply` (unchanged); this module only
//! manages the setup wiring. Phase 2 (follow-up) replaces the in-tree plugin
//! with a published `socket-patch-bundler` gem.

mod update;

use std::path::{Path, PathBuf};

use tokio::fs;

pub use update::{
    add_plugin_directive, is_plugin_directive_present, remove_plugin_directive, GemEditResult,
    GemSetupStatus,
};

/// The in-tree plugin directory, relative to the project root.
const PLUGIN_DIR: &str = ".socket/bundler-plugin";
/// First line of every generated plugin file — the ownership signal for removal
/// (we never delete a file that lacks it).
const GENERATED_MARKER: &str = "# Code generated by `socket-patch setup`. DO NOT EDIT.";
/// The generated plugin's digest stamp, relative to the project root
/// (machine-local state; the plugin owns its content, setup owns its lifecycle).
const STAMP_REL: &str = ".socket/gem-plugin-stamp";
/// The `.socket/.gitignore` line that keeps the stamp out of version control.
/// Everything else under `.socket/` is meant to be committed, so without this
/// line every install drops an untracked stamp into `git status` — and a stamp
/// committed by a blanket `git add .socket` ships one machine's digest to
/// every clone.
const STAMP_IGNORE_LINE: &str = "/gem-plugin-stamp";

/// The generated `plugins.rb` body (the two-trigger idempotent applier).
const PLUGINS_RB: &str = include_str!("templates/plugins.rb.tmpl");
/// The generated plugin gemspec.
const GEMSPEC: &str = include_str!("templates/gemspec.tmpl");

/// A discovered Bundler project.
#[derive(Debug, Clone)]
pub struct BundlerProject {
    /// Directory containing the Gemfile (the project root). The plugin dir and
    /// `.socket/manifest.json` live here.
    pub root: PathBuf,
    /// The Bundler manifest to edit (`Gemfile` or `gems.rb`).
    pub gemfile: PathBuf,
}

/// Find the Bundler project that `cwd` belongs to by walking up to the nearest
/// directory holding Bundler's alternate `gems.rb` or a `Gemfile` — exactly
/// how `bundle` itself resolves the manifest. The discovered
/// directory (not `cwd`) becomes the project `root`, so `.socket/` and the
/// plugin dir land next to the manifest even when `setup` is run from a
/// subdirectory. Returns `None` when no ancestor has one — a `Gemfile.lock`
/// alone is not editable, so it does not count.
///
/// The name order is Bundler's own: `Bundler::SharedHelpers.gemfile_names` is
/// `["gems.rb", "Gemfile"]`, and both names are tried in each directory before
/// ascending (`search_up`), so `gems.rb` only wins within a single directory —
/// a nearer `Gemfile` still beats a farther `gems.rb`. Getting this backwards
/// wires the `plugin` directive into the file `bundle` *ignores* (it even warns
/// "Multiple gemfiles (gems.rb and Gemfile) detected ... bundler is ignoring
/// them in favor of gems.rb and gems.locked"), so the plugin never loads and
/// every `bundle install` silently reverts the gem patches.
pub async fn discover_bundler_project(cwd: &Path) -> Option<BundlerProject> {
    let mut dir = cwd.to_path_buf();
    loop {
        for name in ["gems.rb", "Gemfile"] {
            let candidate = dir.join(name);
            if fs::metadata(&candidate).await.is_ok() {
                return Some(BundlerProject {
                    root: dir,
                    gemfile: candidate,
                });
            }
        }
        dir = if matches!(
            dir.components().next_back(),
            Some(std::path::Component::ParentDir)
        ) {
            // `Path::parent` is lexical: it strips a trailing `..`, stepping
            // the walk back DOWN into the directory the `..` just escaped
            // (parent of `a/b/..` is `a/b`) and probing descendants outside
            // the real ancestry. Resolve the position against the filesystem —
            // the same way the kernel resolved this iteration's metadata
            // probes — and continue from its real parent.
            fs::canonicalize(&dir).await.ok()?.parent()?.to_path_buf()
        } else {
            match dir.parent() {
                Some(parent) if !parent.as_os_str().is_empty() => parent.to_path_buf(),
                // A relative `cwd` (e.g. the CLI's default `--cwd .`) exhausts its
                // lexical components here (`Path::parent` of `.` is `Some("")`,
                // then `None`) without ever reaching the real parent directories.
                // Re-root the walk on the process cwd so the true ancestry is
                // still probed — `bundle` resolves the Gemfile from the invocation
                // dir's real ancestors, wherever it is run from.
                _ if dir.is_relative() => std::env::current_dir()
                    .ok()?
                    .join(&dir)
                    .parent()?
                    .to_path_buf(),
                _ => return None,
            }
        };
    }
}

/// Absolute path to the generated plugin directory for a project root.
pub fn plugin_dir(root: &Path) -> PathBuf {
    root.join(PLUGIN_DIR)
}

fn plugins_rb_path(root: &Path) -> PathBuf {
    plugin_dir(root).join("plugins.rb")
}

fn gemspec_path(root: &Path) -> PathBuf {
    plugin_dir(root).join("socket-patch.gemspec")
}

fn stamp_path(root: &Path) -> PathBuf {
    root.join(STAMP_REL)
}

fn stamp_gitignore_path(root: &Path) -> PathBuf {
    root.join(".socket").join(".gitignore")
}

/// Whether `.socket/.gitignore` is missing the stamp entry (so `setup` still
/// has a write to make). Shared by [`add_plugin_files`] and
/// [`plugin_files_present`] to keep `setup` and `--check` in agreement.
async fn stamp_ignore_missing(root: &Path) -> bool {
    match fs::read_to_string(stamp_gitignore_path(root)).await {
        Ok(c) => !c.lines().any(|l| l.trim() == STAMP_IGNORE_LINE),
        Err(_) => true,
    }
}

/// Append the stamp entry to `.socket/.gitignore`, preserving any existing
/// (user or other-tool) lines. Creates the file when absent.
async fn add_stamp_gitignore(root: &Path) -> Result<(), String> {
    let path = stamp_gitignore_path(root);
    let existing = fs::read_to_string(&path).await.unwrap_or_default();
    let mut body = existing;
    if !body.is_empty() && !body.ends_with('\n') {
        body.push('\n');
    }
    body.push_str(STAMP_IGNORE_LINE);
    body.push('\n');
    write_file(&path, &body).await
}

/// Best-effort cleanup of the stamp artifacts on `--remove`: delete the stamp
/// itself and strip our line from `.socket/.gitignore` (deleting the file when
/// nothing else is left, sparing any other lines). Best-effort by design — a
/// leftover stamp is inert machine-local state, not worth failing an
/// otherwise-successful unwire over.
async fn remove_stamp_artifacts(root: &Path) {
    let _ = fs::remove_file(stamp_path(root)).await;
    let path = stamp_gitignore_path(root);
    let Ok(content) = fs::read_to_string(&path).await else {
        return;
    };
    let kept: Vec<&str> = content
        .lines()
        .filter(|l| l.trim() != STAMP_IGNORE_LINE)
        .collect();
    if kept.len() == content.lines().count() {
        return;
    }
    if kept.iter().all(|l| l.trim().is_empty()) {
        let _ = fs::remove_file(&path).await;
    } else {
        let _ = fs::write(&path, format!("{}\n", kept.join("\n"))).await;
    }
}

/// Whether the generated plugin files are present *and* match the templates the
/// current CLI generates (the `setup --check` "configured" signal, paired with
/// the Gemfile directive check).
///
/// Mere presence is not enough. A plugin dir generated by an older CLI is on
/// disk but stale, and stale content is not cosmetic: a gemspec predating
/// `s.require_paths = ["."]` makes Bundler refuse to load the plugin ("The
/// following plugin paths don't exist: .../lib ... Continuing without installing
/// plugin"), so `bundle install` silently reverts the gem patches while
/// `--check` reported "configured" and the CI gate went green. Keying on the
/// same [`needs_write`] predicate [`add_plugin_files`] uses keeps the two in
/// agreement: whenever `setup` would rewrite a file, `--check` says
/// needs-configuration.
pub async fn plugin_files_present(root: &Path) -> bool {
    !needs_write(&plugins_rb_path(root), PLUGINS_RB).await
        && !needs_write(&gemspec_path(root), GEMSPEC).await
        && !stamp_ignore_missing(root).await
}

/// True if the file is absent or its content differs from `desired`.
async fn needs_write(path: &Path, desired: &str) -> bool {
    match fs::read_to_string(path).await {
        Ok(c) => c != desired,
        Err(_) => true,
    }
}

async fn write_file(path: &Path, body: &str) -> Result<(), String> {
    if let Some(p) = path.parent() {
        fs::create_dir_all(p)
            .await
            .map_err(|e| format!("create {}: {e}", p.display()))?;
    }
    fs::write(path, body)
        .await
        .map_err(|e| format!("write {}: {e}", path.display()))
}

/// Generate `.socket/bundler-plugin/{plugins.rb, socket-patch.gemspec}` and
/// make sure `.socket/.gitignore` keeps the plugin's digest stamp untracked.
/// Idempotent: `AlreadyConfigured` when everything already matches. `kind =
/// "gem_plugin"`.
async fn add_plugin_files(root: &Path, dry_run: bool) -> GemEditResult {
    let dir = plugin_dir(root);
    let result = async {
        let rb_changed = needs_write(&plugins_rb_path(root), PLUGINS_RB).await;
        let spec_changed = needs_write(&gemspec_path(root), GEMSPEC).await;
        let ignore_missing = stamp_ignore_missing(root).await;
        if !rb_changed && !spec_changed && !ignore_missing {
            return Ok(false);
        }
        if !dry_run {
            if rb_changed {
                write_file(&plugins_rb_path(root), PLUGINS_RB).await?;
            }
            if spec_changed {
                write_file(&gemspec_path(root), GEMSPEC).await?;
            }
            if ignore_missing {
                add_stamp_gitignore(root).await?;
            }
        }
        Ok(true)
    }
    .await;
    GemEditResult::from_result("gem_plugin", dir.display().to_string(), result)
}

/// Whether the file at `path` carries our [`GENERATED_MARKER`] as its first
/// line — the per-file ownership test for removal.
async fn is_generated(path: &Path) -> bool {
    match fs::read_to_string(path).await {
        Ok(content) => content.starts_with(GENERATED_MARKER),
        Err(_) => false,
    }
}

/// Delete a generated file, tolerating it already being gone but surfacing
/// any other failure (a swallowed error here would report a false "removed").
async fn remove_generated(path: &Path) -> Result<(), String> {
    match fs::remove_file(path).await {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(format!("remove {}: {e}", path.display())),
    }
}

/// Remove the generated plugin files — each only when it carries our
/// [`GENERATED_MARKER`], so a user-authored file at either path is never
/// deleted (and an orphaned generated file is still cleaned up) — plus the
/// plugin's digest stamp and its `.socket/.gitignore` entry (the plugin that
/// maintained them is being unwired; leaving the stamp behind would orphan it
/// in the otherwise-committed `.socket/`). Idempotent: `AlreadyConfigured`
/// when nothing of ours is there.
async fn remove_plugin_files(root: &Path, dry_run: bool) -> GemEditResult {
    let dir = plugin_dir(root);
    let result = async {
        let rb_ours = is_generated(&plugins_rb_path(root)).await;
        let spec_ours = is_generated(&gemspec_path(root)).await;
        if !rb_ours && !spec_ours {
            return Ok(false);
        }
        if !dry_run {
            if rb_ours {
                remove_generated(&plugins_rb_path(root)).await?;
            }
            if spec_ours {
                remove_generated(&gemspec_path(root)).await?;
            }
            remove_stamp_artifacts(root).await;
            // Prune the now-empty plugin dir (leave .socket/ — apply uses it).
            let _ = fs::remove_dir(&dir).await;
        }
        Ok(true)
    }
    .await;
    GemEditResult::from_result("gem_plugin", dir.display().to_string(), result)
}

#[cfg(test)]
mod tests {
    use super::*;

    async fn write(path: &Path, body: &str) {
        if let Some(p) = path.parent() {
            fs::create_dir_all(p).await.unwrap();
        }
        fs::write(path, body).await.unwrap();
    }

    #[tokio::test]
    async fn test_discover_finds_gemfile() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("Gemfile"), "source 'https://rubygems.org'\n").await;
        let proj = discover_bundler_project(root).await.unwrap();
        assert_eq!(proj.root, root);
        assert_eq!(proj.gemfile, root.join("Gemfile"));
    }

    #[tokio::test]
    async fn test_discover_finds_gems_rb() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("gems.rb"), "source 'https://rubygems.org'\n").await;
        let proj = discover_bundler_project(root).await.unwrap();
        assert_eq!(proj.gemfile, root.join("gems.rb"));
    }

    #[tokio::test]
    async fn test_discover_none_for_lock_only() {
        let dir = tempfile::tempdir().unwrap();
        write(&dir.path().join("Gemfile.lock"), "GEM\n").await;
        assert!(discover_bundler_project(dir.path()).await.is_none());
    }

    #[tokio::test]
    async fn test_discover_none_without_gemfile() {
        let dir = tempfile::tempdir().unwrap();
        assert!(discover_bundler_project(dir.path()).await.is_none());
    }

    #[tokio::test]
    async fn test_discover_walks_up_from_subdirectory() {
        // A Gemfile at the project root, `setup` invoked from a nested subdir —
        // `bundle` resolves the Gemfile by walking up, so discovery must too,
        // and the project root must be the Gemfile's dir (where `.socket/` and
        // the plugin dir live), NOT the invocation cwd.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("Gemfile"), "source 'https://rubygems.org'\n").await;
        let nested = root.join("lib").join("widgets");
        fs::create_dir_all(&nested).await.unwrap();

        let proj = discover_bundler_project(&nested)
            .await
            .expect("Bundler project must be found from a subdirectory");
        assert_eq!(proj.root, root, "root is the Gemfile's dir, not the cwd");
        assert_eq!(proj.gemfile, root.join("Gemfile"));
        // The plugin dir resolves under the real root, not the subdir.
        assert_eq!(plugin_dir(&proj.root), root.join(PLUGIN_DIR));
    }

    #[tokio::test]
    async fn test_discover_walks_up_finds_gems_rb() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("gems.rb"), "source 'https://rubygems.org'\n").await;
        let nested = root.join("app");
        fs::create_dir_all(&nested).await.unwrap();
        let proj = discover_bundler_project(&nested).await.unwrap();
        assert_eq!(proj.root, root);
        assert_eq!(proj.gemfile, root.join("gems.rb"));
    }

    #[tokio::test]
    async fn test_discover_prefers_gems_rb_over_gemfile_in_same_dir() {
        // When both names sit in one directory, `gems.rb` wins — that is
        // Bundler's own precedence (`Bundler::SharedHelpers.gemfile_names ==
        // ["gems.rb", "Gemfile"]`, verified on bundler 4.0.15, which also warns
        // "Multiple gemfiles (gems.rb and Gemfile) detected ... bundler is
        // ignoring them in favor of gems.rb and gems.locked").
        //
        // Wiring the `plugin` directive into the file bundler ignores means the
        // plugin never loads: every `bundle install` silently reverts the gem
        // patches while `setup` and `setup --check` both report success.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("Gemfile"), "gemfile\n").await;
        write(&root.join("gems.rb"), "gemsrb\n").await;
        let proj = discover_bundler_project(root).await.unwrap();
        assert_eq!(
            proj.gemfile,
            root.join("gems.rb"),
            "the wired manifest must be the one `bundle` actually loads"
        );
    }

    #[tokio::test]
    async fn test_discover_nearest_dir_gemfile_beats_ancestor_gems_rb() {
        // Bundler's `search_up` tries BOTH names in each directory before
        // ascending, so the name precedence is per-directory only: a child's
        // `Gemfile` beats an ancestor's `gems.rb` (verified with
        // `Bundler.default_gemfile` on bundler 4.0.15). Guards the gems.rb-first
        // ordering against degrading into "gems.rb anywhere in the ancestry
        // wins".
        let dir = tempfile::tempdir().unwrap();
        let outer = dir.path();
        write(&outer.join("gems.rb"), "outer gems.rb\n").await;
        let inner = outer.join("child");
        fs::create_dir_all(&inner).await.unwrap();
        write(&inner.join("Gemfile"), "inner Gemfile\n").await;

        let proj = discover_bundler_project(&inner).await.unwrap();
        assert_eq!(proj.root, inner, "nearest directory still wins");
        assert_eq!(proj.gemfile, inner.join("Gemfile"));
    }

    #[tokio::test]
    async fn test_discover_returns_nearest_ancestor_gemfile() {
        // Two Gemfiles in the ancestry: the NEAREST one (the inner project)
        // must win, never a far-up parent.
        let dir = tempfile::tempdir().unwrap();
        let outer = dir.path();
        write(&outer.join("Gemfile"), "outer\n").await;
        let inner = outer.join("subproject");
        fs::create_dir_all(&inner).await.unwrap();
        write(&inner.join("Gemfile"), "inner\n").await;
        let nested = inner.join("lib");
        fs::create_dir_all(&nested).await.unwrap();

        let proj = discover_bundler_project(&nested).await.unwrap();
        assert_eq!(proj.root, inner, "nearest ancestor Gemfile wins");
        assert_eq!(fs::read_to_string(&proj.gemfile).await.unwrap(), "inner\n");
    }

    #[tokio::test]
    async fn test_discover_dot_dot_cwd_walks_real_ancestry_not_back_down() {
        // `--cwd`/SOCKET_CWD may carry `..` components (`--cwd ..`, `$PWD/..`).
        // The metadata probes resolve them against the real filesystem, but
        // `Path::parent` strips components lexically — the parent of
        // `up/mid/b/..` is `up/mid/b`, the very directory the `..` just
        // escaped. The walk must continue UP the real ancestry
        // (`up/mid` → `up`), never back down into a descendant that `bundle`
        // itself would not consult.
        let dir = tempfile::tempdir().unwrap();
        // Canonicalize so the expected root compares path-exactly (macOS
        // tempdirs live behind the /var → /private/var symlink).
        let base = std::fs::canonicalize(dir.path()).unwrap();
        let up = base.join("up");
        let b = up.join("mid").join("b");
        fs::create_dir_all(&b).await.unwrap();
        write(&up.join("Gemfile"), "real ancestor\n").await;
        write(&b.join("Gemfile"), "descendant, not in the ancestry\n").await;

        let proj = discover_bundler_project(&b.join("..")).await.unwrap();
        assert_eq!(
            proj.root, up,
            "walk from up/mid (= up/mid/b/..) must reach the ancestor `up`, \
             not fall back down into up/mid/b"
        );
        assert_eq!(
            fs::read_to_string(&proj.gemfile).await.unwrap(),
            "real ancestor\n"
        );
    }

    #[test]
    fn test_templates_are_well_formed() {
        // The plugin must carry the ownership marker and all three triggers.
        assert!(PLUGINS_RB.starts_with(GENERATED_MARKER));
        assert!(PLUGINS_RB.contains("def apply!"));
        // Load-time trigger + the per-gem after-install hook (the only event
        // bundler fires during `bundle pristine`) + after-install-all hook.
        assert!(PLUGINS_RB.contains("SocketPatch.apply!"));
        assert!(PLUGINS_RB.contains("Bundler::Plugin.add_hook(\"after-install\")"));
        assert!(PLUGINS_RB.contains("Bundler::Plugin.add_hook(\"after-install-all\")"));
        // The applier shells the gem-scoped offline apply.
        assert!(PLUGINS_RB.contains("\"apply\""));
        assert!(PLUGINS_RB.contains("\"--ecosystems\", \"gem\", \"--offline\""));
        // Digest folds in Gemfile.lock + the manifest + the on-disk state of
        // the patch target files (so an out-of-band reversion is detected).
        assert!(PLUGINS_RB.contains("Gemfile.lock"));
        assert!(PLUGINS_RB.contains("manifest.json"));
        assert!(PLUGINS_RB.contains("def patch_target_files"));
        // The platform-gem wildcard must glob a forward-slash base: Dir.glob
        // treats `\` as an escape on every platform, so a Windows bundle path
        // (backslash separators) would otherwise never match platform installs
        // and they would silently drop out of the digest.
        assert!(PLUGINS_RB.contains(r#"glob_gems_dir = gems_dir.tr("\\", "/")"#));
        // The gemspec names the plugin the Gemfile directive references.
        assert!(GEMSPEC.starts_with(GENERATED_MARKER));
        assert!(GEMSPEC.contains("\"socket-patch\""));
        assert!(GEMSPEC.contains("plugins.rb"));
        // The flat plugin dir has no lib/; without this override Bundler
        // refuses to load the plugin ("plugin paths don't exist: .../lib")
        // and silently continues without it.
        assert!(GEMSPEC.contains("s.require_paths = [\".\"]"));
    }

    #[test]
    fn test_plugin_template_failure_policy_and_stamp_location() {
        // Failure policy: tolerant by default — a patch failure WARNS (with
        // the manual-apply remediation) and lets `bundle install` continue.
        // Bundler evaluates plugins.rb at plugin REGISTRATION, before any
        // project gem is installed; a raise there deadlocks a fresh clone on
        // its own first `bundle install` (plugin registration fails, every
        // retry fails identically — reproduced against bundler 2.7 and 4.0).
        assert!(
            PLUGINS_RB.contains("def report_failure"),
            "the applier must route failures through the tolerant reporter"
        );
        assert!(
            !PLUGINS_RB.contains("def fail!"),
            "the unconditional raise helper must be gone — it is what \
             deadlocked bootstrap installs"
        );
        assert!(
            PLUGINS_RB.contains("warn(message)"),
            "tolerant mode must surface the failure as a stderr warning"
        );
        assert!(
            PLUGINS_RB.contains("socket-patch apply --ecosystems gem"),
            "the warning must name the manual remediation command"
        );
        // Strict escape hatch: SOCKET_PATCH_STRICT=1 restores raise-on-failure.
        assert!(PLUGINS_RB.contains("SOCKET_PATCH_STRICT"));
        assert!(
            PLUGINS_RB.contains("BundlerError"),
            "strict mode must still raise Bundler::BundlerError"
        );
        // The strict raise must carry a strict trailer, not the tolerant
        // "`bundle install` continues" text (which is false mid-raise).
        assert!(PLUGINS_RB.contains("def failure_trailer"));
        // Stamp location: project-scoped under .socket/, NOT a fixed-name file
        // in Bundler.bundle_path (machine-global with no bundle path
        // configured, shared and clobbered across every project on the host).
        assert!(PLUGINS_RB.contains("STAMP_NAME = \"gem-plugin-stamp\""));
        assert!(PLUGINS_RB.contains("File.join(socket_dir, STAMP_NAME)"));
        // The legacy global stamp is cleaned up, never read.
        assert!(PLUGINS_RB.contains("LEGACY_STAMP_NAME = \".socket-patch-gem-stamp\""));
        assert!(PLUGINS_RB.contains("def remove_legacy_stamp"));
        // The stamp must be excluded from its own digest inputs, or every
        // write would invalidate the digest it records.
        assert!(PLUGINS_RB.contains("p != stamp_path"));
        // The bootstrap gate keys on the patch targets existing on disk, NEVER
        // on the stamp: `.socket/` is a committed directory, so a stale stamp
        // that reaches version control would otherwise pass the gate at plugin
        // REGISTRATION on a fresh clone and resurrect the strict-mode
        // bootstrap deadlock this plugin exists to avoid.
        assert!(PLUGINS_RB.contains("bootstrap_gate && patch_target_files.none?"));
        assert!(
            !PLUGINS_RB.contains("require_stamp"),
            "the stamp-existence gate must be gone — a committed stamp made it \
             a remote-controlled registration deadlock"
        );

        // The published-gem twin must carry the same applier contract.
        let published = include_str!("../../../../../gem/socket-patch-bundler/plugins.rb");
        for needle in [
            "def report_failure",
            "def failure_trailer",
            "SOCKET_PATCH_STRICT",
            "STAMP_NAME = \"gem-plugin-stamp\"",
            "def remove_legacy_stamp",
            "def patch_target_files",
            r#"glob_gems_dir = gems_dir.tr("\\", "/")"#,
            "bootstrap_gate && patch_target_files.none?",
            "Bundler::Plugin.add_hook(\"after-install\")",
            "Bundler::Plugin.add_hook(\"after-install-all\")",
        ] {
            assert!(
                published.contains(needle),
                "published plugins.rb drifted from the template: missing {needle:?}"
            );
        }
        assert!(!published.contains("def fail!"));
        assert!(!published.contains("require_stamp"));
    }

    #[tokio::test]
    async fn test_add_then_remove_plugin_files_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let r = add_plugin_files(root, false).await;
        assert_eq!(r.status, GemSetupStatus::Updated);
        assert!(plugin_files_present(root).await);
        assert_eq!(
            fs::read_to_string(plugins_rb_path(root)).await.unwrap(),
            PLUGINS_RB
        );
        // The stamp is gitignored: everything else under .socket/ is committed,
        // so without this line every install litters `git status` and a blanket
        // `git add .socket` commits one machine's stamp to every clone.
        assert_eq!(
            fs::read_to_string(stamp_gitignore_path(root))
                .await
                .unwrap(),
            "/gem-plugin-stamp\n"
        );
        // Idempotent.
        assert_eq!(
            add_plugin_files(root, false).await.status,
            GemSetupStatus::AlreadyConfigured
        );
        // Remove — including the stamp a previous apply left behind, which
        // would otherwise be orphaned in the committed .socket/ dir.
        fs::write(stamp_path(root), "f".repeat(64)).await.unwrap();
        let rr = remove_plugin_files(root, false).await;
        assert_eq!(rr.status, GemSetupStatus::Updated);
        assert!(!plugin_files_present(root).await);
        assert!(!plugin_dir(root).exists(), "empty plugin dir pruned");
        assert!(!stamp_path(root).exists(), "stamp removed with the plugin");
        assert!(
            !stamp_gitignore_path(root).exists(),
            "the .gitignore we created (nothing but our line) is removed too"
        );
        // Remove again → already gone.
        assert_eq!(
            remove_plugin_files(root, false).await.status,
            GemSetupStatus::AlreadyConfigured
        );
    }

    #[tokio::test]
    async fn test_add_plugin_files_dry_run_writes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let r = add_plugin_files(root, true).await;
        assert_eq!(
            r.status,
            GemSetupStatus::Updated,
            "dry-run reports the change"
        );
        assert!(!plugin_files_present(root).await, "dry-run wrote nothing");
    }

    #[tokio::test]
    async fn test_remove_spares_user_authored_dir() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        // A user file at the generated path WITHOUT our marker.
        write(&plugins_rb_path(root), "# my own plugin\n").await;
        let r = remove_plugin_files(root, false).await;
        assert_eq!(r.status, GemSetupStatus::AlreadyConfigured);
        assert!(
            plugins_rb_path(root).exists(),
            "user file must be left alone"
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn test_remove_surfaces_removal_failure_as_error() {
        // Deleting a file requires write permission on its directory. With the
        // plugin dir read-only, the removes fail — that failure must surface as
        // `Error`, not be swallowed into a false "removed" success while the
        // files are in fact still there.
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        add_plugin_files(root, false).await;
        fs::set_permissions(&plugin_dir(root), std::fs::Permissions::from_mode(0o555))
            .await
            .unwrap();

        let r = remove_plugin_files(root, false).await;

        // Restore so the tempdir can be cleaned up regardless of the outcome.
        fs::set_permissions(&plugin_dir(root), std::fs::Permissions::from_mode(0o755))
            .await
            .unwrap();

        assert!(
            plugin_files_present(root).await,
            "the read-only dir means nothing was actually removed"
        );
        assert_eq!(
            r.status,
            GemSetupStatus::Error,
            "a failed removal must report Error, not a false success"
        );
        assert!(
            r.error.is_some(),
            "the failure carries the io error message"
        );
    }

    #[tokio::test]
    async fn test_remove_cleans_orphaned_gemspec() {
        // plugins.rb gone (crash between the two removes, or a manual delete)
        // but our generated gemspec is still there. Remove must clean the
        // orphan — not report not_configured forever while a generated file
        // lingers in the repo.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&gemspec_path(root), GEMSPEC).await;

        let r = remove_plugin_files(root, false).await;
        assert_eq!(
            r.status,
            GemSetupStatus::Updated,
            "an orphaned generated gemspec is ours to remove"
        );
        assert!(!gemspec_path(root).exists(), "orphan gemspec removed");
        assert!(!plugin_dir(root).exists(), "emptied plugin dir pruned");
    }

    #[tokio::test]
    async fn test_remove_spares_user_authored_gemspec() {
        // Ownership is per file: our plugins.rb is removed, but a user-authored
        // (marker-less) file at the gemspec path must never be deleted on the
        // strength of plugins.rb's marker alone.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&plugins_rb_path(root), PLUGINS_RB).await;
        write(&gemspec_path(root), "# my own gemspec\n").await;

        let r = remove_plugin_files(root, false).await;
        assert_eq!(r.status, GemSetupStatus::Updated);
        assert!(!plugins_rb_path(root).exists(), "our plugins.rb removed");
        assert!(
            gemspec_path(root).exists(),
            "marker-less user file at the gemspec path must be left alone"
        );
        assert_eq!(
            fs::read_to_string(gemspec_path(root)).await.unwrap(),
            "# my own gemspec\n"
        );
    }

    #[tokio::test]
    async fn test_add_plugin_files_writes_each_template_to_its_own_path() {
        // Guards the path↔content mapping: plugins.rb must get PLUGINS_RB and the
        // gemspec must get GEMSPEC (not swapped). A swap would leave each file
        // failing its own `starts_with(GENERATED_MARKER)` content expectations.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        add_plugin_files(root, false).await;
        assert_eq!(
            fs::read_to_string(plugins_rb_path(root)).await.unwrap(),
            PLUGINS_RB,
            "plugins.rb must receive the plugins.rb template"
        );
        assert_eq!(
            fs::read_to_string(gemspec_path(root)).await.unwrap(),
            GEMSPEC,
            "gemspec must receive the gemspec template"
        );
    }

    #[tokio::test]
    async fn test_add_plugin_files_rewrites_stale_content() {
        // A drifted (hand-edited or older-version) plugins.rb must be re-synced to
        // the current template, and the call must report `Updated` — not silently
        // accept the stale bytes as already-configured.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(
            &plugins_rb_path(root),
            "# Code generated by stale\nold body\n",
        )
        .await;
        write(&gemspec_path(root), GEMSPEC).await;
        let r = add_plugin_files(root, false).await;
        assert_eq!(
            r.status,
            GemSetupStatus::Updated,
            "stale plugins.rb is re-synced"
        );
        assert_eq!(
            fs::read_to_string(plugins_rb_path(root)).await.unwrap(),
            PLUGINS_RB
        );
    }

    #[tokio::test]
    async fn test_add_plugin_files_syncs_only_the_drifted_file() {
        // plugins.rb already matches; only the gemspec drifted. The call rewrites
        // the gemspec, reports Updated, and leaves the matching plugins.rb intact.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&plugins_rb_path(root), PLUGINS_RB).await;
        write(&gemspec_path(root), "# drifted gemspec\n").await;
        let r = add_plugin_files(root, false).await;
        assert_eq!(r.status, GemSetupStatus::Updated);
        assert_eq!(
            fs::read_to_string(gemspec_path(root)).await.unwrap(),
            GEMSPEC
        );
        assert_eq!(
            fs::read_to_string(plugins_rb_path(root)).await.unwrap(),
            PLUGINS_RB
        );
    }

    #[tokio::test]
    async fn test_remove_plugin_files_dry_run_keeps_files() {
        // Dry-run remove reports the change but must not delete anything.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        add_plugin_files(root, false).await;
        let r = remove_plugin_files(root, true).await;
        assert_eq!(
            r.status,
            GemSetupStatus::Updated,
            "dry-run reports the removal"
        );
        assert!(
            plugin_files_present(root).await,
            "dry-run remove must not delete the plugin files"
        );
    }

    #[tokio::test]
    async fn test_stale_plugin_files_are_not_reported_as_configured() {
        // `setup --check`'s gem_plugin verdict must agree with what `setup`
        // itself would do. A plugin dir generated by an OLDER CLI is present but
        // stale, and a stale gemspec is not cosmetic: without the current
        // template's `s.require_paths = ["."]` Bundler refuses to load the
        // plugin ("The following plugin paths don't exist: .../lib ...
        // Continuing without installing plugin") and every `bundle install`
        // silently reverts the gem patches — while `--check` reported
        // "configured" and the CI gate went green.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&plugins_rb_path(root), PLUGINS_RB).await;
        // An older generated gemspec: carries our marker, but predates the
        // require_paths override.
        write(
            &gemspec_path(root),
            &format!(
                "{GENERATED_MARKER}\nGem::Specification.new do |s|\n  \
                 s.name = \"socket-patch\"\nend\n"
            ),
        )
        .await;

        assert!(
            !plugin_files_present(root).await,
            "a stale generated gemspec is not 'configured' — Bundler would not \
             load the plugin"
        );
        assert_eq!(
            add_plugin_files(root, true).await.status,
            GemSetupStatus::Updated,
            "check and setup must agree: setup would rewrite the stale file"
        );
    }

    #[tokio::test]
    async fn test_plugin_files_present_requires_all_three() {
        // The "configured" signal must demand BOTH generated files AND the
        // stamp's .gitignore entry, not any subset.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&plugins_rb_path(root), PLUGINS_RB).await;
        assert!(
            !plugin_files_present(root).await,
            "plugins.rb alone is not 'configured' — the gemspec is required too"
        );
        write(&gemspec_path(root), GEMSPEC).await;
        assert!(
            !plugin_files_present(root).await,
            "check and setup must agree: setup would still write the stamp's \
             .gitignore entry, so this is not 'configured' yet"
        );
        assert_eq!(
            add_plugin_files(root, true).await.status,
            GemSetupStatus::Updated,
            "setup agrees it still has the .gitignore write to make"
        );
        write(&stamp_gitignore_path(root), "/gem-plugin-stamp\n").await;
        assert!(plugin_files_present(root).await);
    }

    #[tokio::test]
    async fn test_stamp_gitignore_add_and_remove_spare_user_lines() {
        // A user's own .socket/.gitignore entries must survive both the add
        // (line appended, not the file clobbered) and the remove (only our
        // line stripped, file kept).
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&stamp_gitignore_path(root), "my-scratch-dir/\n").await;

        add_plugin_files(root, false).await;
        assert_eq!(
            fs::read_to_string(stamp_gitignore_path(root))
                .await
                .unwrap(),
            "my-scratch-dir/\n/gem-plugin-stamp\n",
            "our line is appended after the user's"
        );

        remove_plugin_files(root, false).await;
        assert_eq!(
            fs::read_to_string(stamp_gitignore_path(root))
                .await
                .unwrap(),
            "my-scratch-dir/\n",
            "only our line is stripped; the user's file survives"
        );
    }

    #[tokio::test]
    async fn test_add_appends_gitignore_line_to_unterminated_file() {
        // A .gitignore whose last line has no trailing newline must not have
        // our entry glued onto it ("vendor//gem-plugin-stamp" ignores nothing).
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&stamp_gitignore_path(root), "vendor/").await;
        add_plugin_files(root, false).await;
        assert_eq!(
            fs::read_to_string(stamp_gitignore_path(root))
                .await
                .unwrap(),
            "vendor/\n/gem-plugin-stamp\n"
        );
        assert!(plugin_files_present(root).await);
    }
}
