//! Gem (Bundler) `setup` support: wire a Ruby project for automatic patching.
//!
//! Bundler has no after-each-install hook that survives a cached/no-op
//! `bundle install`, but it loads any declared **plugin** during the Gemfile
//! pass on every `bundle` invocation. So setup delivers the gate as a
//! generated, git-committed Bundler plugin plus a `plugin` directive in the
//! Gemfile:
//!
//!   * `.socket/bundler-plugin/{plugins.rb, socket-patch.gemspec}` — a generated
//!     plugin whose `plugins.rb` re-runs `socket-patch apply --ecosystems gem`
//!     on every `bundle install` (load-time digest gate + `after-install-all`
//!     hook), failing the build loudly on a patch failure;
//!   * a managed block appended to the `Gemfile` that references the plugin via
//!     `plugin "socket-patch", path: File.expand_path(".socket/bundler-plugin",
//!     __dir__)`. The source must be `path:` — Bundler fetches `git:` plugin
//!     sources with `git clone`, and the generated dir is a plain directory
//!     (committing it to the parent repo does not give it a `.git`), so `git:`
//!     fails every `bundle install`. The directory still must be committed so
//!     clones and CI have the plugin on disk.
//!
//! The actual gem patching is done by `apply` (unchanged); this module only
//! manages the setup wiring. Phase 2 (follow-up) replaces the in-tree plugin
//! with a published `socket-patch-bundler` gem.

mod update;

use std::path::{Path, PathBuf};

use tokio::fs;

pub use update::{
    add_plugin_directive, is_plugin_directive_present, remove_plugin_directive, GemEditResult,
    GemSetupStatus,
};

/// The in-tree plugin directory, relative to the project root.
const PLUGIN_DIR: &str = ".socket/bundler-plugin";
/// First line of every generated plugin file — the ownership signal for removal
/// (we never delete a file that lacks it).
const GENERATED_MARKER: &str = "# Code generated by `socket-patch setup`. DO NOT EDIT.";

/// The generated `plugins.rb` body (the two-trigger idempotent applier).
const PLUGINS_RB: &str = include_str!("templates/plugins.rb.tmpl");
/// The generated plugin gemspec.
const GEMSPEC: &str = include_str!("templates/gemspec.tmpl");

/// A discovered Bundler project.
#[derive(Debug, Clone)]
pub struct BundlerProject {
    /// Directory containing the Gemfile (the project root). The plugin dir and
    /// `.socket/manifest.json` live here.
    pub root: PathBuf,
    /// The Bundler manifest to edit (`Gemfile` or `gems.rb`).
    pub gemfile: PathBuf,
}

/// Find the Bundler project that `cwd` belongs to by walking up to the nearest
/// directory holding a `Gemfile` (or Bundler's alternate `gems.rb`) — exactly
/// how `bundle` itself resolves the manifest. The discovered
/// directory (not `cwd`) becomes the project `root`, so `.socket/` and the
/// plugin dir land next to the Gemfile even when `setup` is run from a
/// subdirectory. Returns `None` when no ancestor has one — a `Gemfile.lock`
/// alone is not editable, so it does not count.
pub async fn discover_bundler_project(cwd: &Path) -> Option<BundlerProject> {
    let mut dir = cwd.to_path_buf();
    loop {
        for name in ["Gemfile", "gems.rb"] {
            let candidate = dir.join(name);
            if fs::metadata(&candidate).await.is_ok() {
                return Some(BundlerProject {
                    root: dir,
                    gemfile: candidate,
                });
            }
        }
        dir = if matches!(
            dir.components().next_back(),
            Some(std::path::Component::ParentDir)
        ) {
            // `Path::parent` is lexical: it strips a trailing `..`, stepping
            // the walk back DOWN into the directory the `..` just escaped
            // (parent of `a/b/..` is `a/b`) and probing descendants outside
            // the real ancestry. Resolve the position against the filesystem —
            // the same way the kernel resolved this iteration's metadata
            // probes — and continue from its real parent.
            fs::canonicalize(&dir).await.ok()?.parent()?.to_path_buf()
        } else {
            match dir.parent() {
                Some(parent) if !parent.as_os_str().is_empty() => parent.to_path_buf(),
                // A relative `cwd` (e.g. the CLI's default `--cwd .`) exhausts its
                // lexical components here (`Path::parent` of `.` is `Some("")`,
                // then `None`) without ever reaching the real parent directories.
                // Re-root the walk on the process cwd so the true ancestry is
                // still probed — `bundle` resolves the Gemfile from the invocation
                // dir's real ancestors, wherever it is run from.
                _ if dir.is_relative() => std::env::current_dir()
                    .ok()?
                    .join(&dir)
                    .parent()?
                    .to_path_buf(),
                _ => return None,
            }
        };
    }
}

/// Absolute path to the generated plugin directory for a project root.
pub fn plugin_dir(root: &Path) -> PathBuf {
    root.join(PLUGIN_DIR)
}

fn plugins_rb_path(root: &Path) -> PathBuf {
    plugin_dir(root).join("plugins.rb")
}

fn gemspec_path(root: &Path) -> PathBuf {
    plugin_dir(root).join("socket-patch.gemspec")
}

/// Whether the generated plugin files are present (the `setup --check`
/// "configured" signal, paired with the Gemfile directive check).
pub async fn plugin_files_present(root: &Path) -> bool {
    fs::metadata(plugins_rb_path(root)).await.is_ok()
        && fs::metadata(gemspec_path(root)).await.is_ok()
}

/// True if the file is absent or its content differs from `desired`.
async fn needs_write(path: &Path, desired: &str) -> bool {
    match fs::read_to_string(path).await {
        Ok(c) => c != desired,
        Err(_) => true,
    }
}

async fn write_file(path: &Path, body: &str) -> Result<(), String> {
    if let Some(p) = path.parent() {
        fs::create_dir_all(p)
            .await
            .map_err(|e| format!("create {}: {e}", p.display()))?;
    }
    fs::write(path, body)
        .await
        .map_err(|e| format!("write {}: {e}", path.display()))
}

/// Generate `.socket/bundler-plugin/{plugins.rb, socket-patch.gemspec}`.
/// Idempotent: `AlreadyConfigured` when both already match the templates byte
/// for byte. `kind = "gem_plugin"`.
async fn add_plugin_files(root: &Path, dry_run: bool) -> GemEditResult {
    let dir = plugin_dir(root);
    let result = async {
        let rb_changed = needs_write(&plugins_rb_path(root), PLUGINS_RB).await;
        let spec_changed = needs_write(&gemspec_path(root), GEMSPEC).await;
        if !rb_changed && !spec_changed {
            return Ok(false);
        }
        if !dry_run {
            if rb_changed {
                write_file(&plugins_rb_path(root), PLUGINS_RB).await?;
            }
            if spec_changed {
                write_file(&gemspec_path(root), GEMSPEC).await?;
            }
        }
        Ok(true)
    }
    .await;
    GemEditResult::from_result("gem_plugin", dir.display().to_string(), result)
}

/// Whether the file at `path` carries our [`GENERATED_MARKER`] as its first
/// line — the per-file ownership test for removal.
async fn is_generated(path: &Path) -> bool {
    match fs::read_to_string(path).await {
        Ok(content) => content.starts_with(GENERATED_MARKER),
        Err(_) => false,
    }
}

/// Delete a generated file, tolerating it already being gone but surfacing
/// any other failure (a swallowed error here would report a false "removed").
async fn remove_generated(path: &Path) -> Result<(), String> {
    match fs::remove_file(path).await {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(format!("remove {}: {e}", path.display())),
    }
}

/// Remove the generated plugin files — each only when it carries our
/// [`GENERATED_MARKER`], so a user-authored file at either path is never
/// deleted (and an orphaned generated file is still cleaned up). Idempotent:
/// `AlreadyConfigured` when nothing of ours is there.
async fn remove_plugin_files(root: &Path, dry_run: bool) -> GemEditResult {
    let dir = plugin_dir(root);
    let result = async {
        let rb_ours = is_generated(&plugins_rb_path(root)).await;
        let spec_ours = is_generated(&gemspec_path(root)).await;
        if !rb_ours && !spec_ours {
            return Ok(false);
        }
        if !dry_run {
            if rb_ours {
                remove_generated(&plugins_rb_path(root)).await?;
            }
            if spec_ours {
                remove_generated(&gemspec_path(root)).await?;
            }
            // Prune the now-empty plugin dir (leave .socket/ — apply uses it).
            let _ = fs::remove_dir(&dir).await;
        }
        Ok(true)
    }
    .await;
    GemEditResult::from_result("gem_plugin", dir.display().to_string(), result)
}

#[cfg(test)]
mod tests {
    use super::*;

    async fn write(path: &Path, body: &str) {
        if let Some(p) = path.parent() {
            fs::create_dir_all(p).await.unwrap();
        }
        fs::write(path, body).await.unwrap();
    }

    #[tokio::test]
    async fn test_discover_finds_gemfile() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("Gemfile"), "source 'https://rubygems.org'\n").await;
        let proj = discover_bundler_project(root).await.unwrap();
        assert_eq!(proj.root, root);
        assert_eq!(proj.gemfile, root.join("Gemfile"));
    }

    #[tokio::test]
    async fn test_discover_finds_gems_rb() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("gems.rb"), "source 'https://rubygems.org'\n").await;
        let proj = discover_bundler_project(root).await.unwrap();
        assert_eq!(proj.gemfile, root.join("gems.rb"));
    }

    #[tokio::test]
    async fn test_discover_none_for_lock_only() {
        let dir = tempfile::tempdir().unwrap();
        write(&dir.path().join("Gemfile.lock"), "GEM\n").await;
        assert!(discover_bundler_project(dir.path()).await.is_none());
    }

    #[tokio::test]
    async fn test_discover_none_without_gemfile() {
        let dir = tempfile::tempdir().unwrap();
        assert!(discover_bundler_project(dir.path()).await.is_none());
    }

    #[tokio::test]
    async fn test_discover_walks_up_from_subdirectory() {
        // A Gemfile at the project root, `setup` invoked from a nested subdir —
        // `bundle` resolves the Gemfile by walking up, so discovery must too,
        // and the project root must be the Gemfile's dir (where `.socket/` and
        // the plugin dir live), NOT the invocation cwd.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("Gemfile"), "source 'https://rubygems.org'\n").await;
        let nested = root.join("lib").join("widgets");
        fs::create_dir_all(&nested).await.unwrap();

        let proj = discover_bundler_project(&nested)
            .await
            .expect("Bundler project must be found from a subdirectory");
        assert_eq!(proj.root, root, "root is the Gemfile's dir, not the cwd");
        assert_eq!(proj.gemfile, root.join("Gemfile"));
        // The plugin dir resolves under the real root, not the subdir.
        assert_eq!(plugin_dir(&proj.root), root.join(PLUGIN_DIR));
    }

    #[tokio::test]
    async fn test_discover_walks_up_finds_gems_rb() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("gems.rb"), "source 'https://rubygems.org'\n").await;
        let nested = root.join("app");
        fs::create_dir_all(&nested).await.unwrap();
        let proj = discover_bundler_project(&nested).await.unwrap();
        assert_eq!(proj.root, root);
        assert_eq!(proj.gemfile, root.join("gems.rb"));
    }

    #[tokio::test]
    async fn test_discover_prefers_gemfile_over_gems_rb_in_same_dir() {
        // When both names sit in one directory, `Gemfile` wins (Bundler's own
        // precedence). The walk-up must not let a `gems.rb` deeper down or the
        // iteration order flip this.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("Gemfile"), "gemfile\n").await;
        write(&root.join("gems.rb"), "gemsrb\n").await;
        let proj = discover_bundler_project(root).await.unwrap();
        assert_eq!(proj.gemfile, root.join("Gemfile"));
    }

    #[tokio::test]
    async fn test_discover_returns_nearest_ancestor_gemfile() {
        // Two Gemfiles in the ancestry: the NEAREST one (the inner project)
        // must win, never a far-up parent.
        let dir = tempfile::tempdir().unwrap();
        let outer = dir.path();
        write(&outer.join("Gemfile"), "outer\n").await;
        let inner = outer.join("subproject");
        fs::create_dir_all(&inner).await.unwrap();
        write(&inner.join("Gemfile"), "inner\n").await;
        let nested = inner.join("lib");
        fs::create_dir_all(&nested).await.unwrap();

        let proj = discover_bundler_project(&nested).await.unwrap();
        assert_eq!(proj.root, inner, "nearest ancestor Gemfile wins");
        assert_eq!(fs::read_to_string(&proj.gemfile).await.unwrap(), "inner\n");
    }

    #[tokio::test]
    async fn test_discover_dot_dot_cwd_walks_real_ancestry_not_back_down() {
        // `--cwd`/SOCKET_CWD may carry `..` components (`--cwd ..`, `$PWD/..`).
        // The metadata probes resolve them against the real filesystem, but
        // `Path::parent` strips components lexically — the parent of
        // `up/mid/b/..` is `up/mid/b`, the very directory the `..` just
        // escaped. The walk must continue UP the real ancestry
        // (`up/mid` → `up`), never back down into a descendant that `bundle`
        // itself would not consult.
        let dir = tempfile::tempdir().unwrap();
        // Canonicalize so the expected root compares path-exactly (macOS
        // tempdirs live behind the /var → /private/var symlink).
        let base = std::fs::canonicalize(dir.path()).unwrap();
        let up = base.join("up");
        let b = up.join("mid").join("b");
        fs::create_dir_all(&b).await.unwrap();
        write(&up.join("Gemfile"), "real ancestor\n").await;
        write(&b.join("Gemfile"), "descendant, not in the ancestry\n").await;

        let proj = discover_bundler_project(&b.join("..")).await.unwrap();
        assert_eq!(
            proj.root, up,
            "walk from up/mid (= up/mid/b/..) must reach the ancestor `up`, \
             not fall back down into up/mid/b"
        );
        assert_eq!(
            fs::read_to_string(&proj.gemfile).await.unwrap(),
            "real ancestor\n"
        );
    }

    #[test]
    fn test_templates_are_well_formed() {
        // The plugin must carry the ownership marker and both triggers.
        assert!(PLUGINS_RB.starts_with(GENERATED_MARKER));
        assert!(PLUGINS_RB.contains("def apply!"));
        // Load-time trigger + after-install-all hook.
        assert!(PLUGINS_RB.contains("SocketPatch.apply!"));
        assert!(PLUGINS_RB.contains("Bundler::Plugin.add_hook(\"after-install-all\")"));
        // The applier shells the gem-scoped offline apply and fails loud.
        assert!(PLUGINS_RB.contains("\"apply\""));
        assert!(PLUGINS_RB.contains("\"--ecosystems\", \"gem\", \"--offline\""));
        assert!(PLUGINS_RB.contains("BundlerError"));
        // Stamp travels with the gems (under Bundler.bundle_path).
        assert!(PLUGINS_RB.contains("Bundler.bundle_path"));
        // Digest folds in Gemfile.lock + the manifest.
        assert!(PLUGINS_RB.contains("Gemfile.lock"));
        assert!(PLUGINS_RB.contains("manifest.json"));
        // The gemspec names the plugin the Gemfile directive references.
        assert!(GEMSPEC.starts_with(GENERATED_MARKER));
        assert!(GEMSPEC.contains("\"socket-patch\""));
        assert!(GEMSPEC.contains("plugins.rb"));
        // The flat plugin dir has no lib/; without this override Bundler
        // refuses to load the plugin ("plugin paths don't exist: .../lib")
        // and silently continues without it.
        assert!(GEMSPEC.contains("s.require_paths = [\".\"]"));
    }

    #[tokio::test]
    async fn test_add_then_remove_plugin_files_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let r = add_plugin_files(root, false).await;
        assert_eq!(r.status, GemSetupStatus::Updated);
        assert!(plugin_files_present(root).await);
        assert_eq!(
            fs::read_to_string(plugins_rb_path(root)).await.unwrap(),
            PLUGINS_RB
        );
        // Idempotent.
        assert_eq!(
            add_plugin_files(root, false).await.status,
            GemSetupStatus::AlreadyConfigured
        );
        // Remove.
        let rr = remove_plugin_files(root, false).await;
        assert_eq!(rr.status, GemSetupStatus::Updated);
        assert!(!plugin_files_present(root).await);
        assert!(!plugin_dir(root).exists(), "empty plugin dir pruned");
        // Remove again → already gone.
        assert_eq!(
            remove_plugin_files(root, false).await.status,
            GemSetupStatus::AlreadyConfigured
        );
    }

    #[tokio::test]
    async fn test_add_plugin_files_dry_run_writes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let r = add_plugin_files(root, true).await;
        assert_eq!(
            r.status,
            GemSetupStatus::Updated,
            "dry-run reports the change"
        );
        assert!(!plugin_files_present(root).await, "dry-run wrote nothing");
    }

    #[tokio::test]
    async fn test_remove_spares_user_authored_dir() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        // A user file at the generated path WITHOUT our marker.
        write(&plugins_rb_path(root), "# my own plugin\n").await;
        let r = remove_plugin_files(root, false).await;
        assert_eq!(r.status, GemSetupStatus::AlreadyConfigured);
        assert!(
            plugins_rb_path(root).exists(),
            "user file must be left alone"
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn test_remove_surfaces_removal_failure_as_error() {
        // Deleting a file requires write permission on its directory. With the
        // plugin dir read-only, the removes fail — that failure must surface as
        // `Error`, not be swallowed into a false "removed" success while the
        // files are in fact still there.
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        add_plugin_files(root, false).await;
        fs::set_permissions(&plugin_dir(root), std::fs::Permissions::from_mode(0o555))
            .await
            .unwrap();

        let r = remove_plugin_files(root, false).await;

        // Restore so the tempdir can be cleaned up regardless of the outcome.
        fs::set_permissions(&plugin_dir(root), std::fs::Permissions::from_mode(0o755))
            .await
            .unwrap();

        assert!(
            plugin_files_present(root).await,
            "the read-only dir means nothing was actually removed"
        );
        assert_eq!(
            r.status,
            GemSetupStatus::Error,
            "a failed removal must report Error, not a false success"
        );
        assert!(
            r.error.is_some(),
            "the failure carries the io error message"
        );
    }

    #[tokio::test]
    async fn test_remove_cleans_orphaned_gemspec() {
        // plugins.rb gone (crash between the two removes, or a manual delete)
        // but our generated gemspec is still there. Remove must clean the
        // orphan — not report not_configured forever while a generated file
        // lingers in the repo.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&gemspec_path(root), GEMSPEC).await;

        let r = remove_plugin_files(root, false).await;
        assert_eq!(
            r.status,
            GemSetupStatus::Updated,
            "an orphaned generated gemspec is ours to remove"
        );
        assert!(!gemspec_path(root).exists(), "orphan gemspec removed");
        assert!(!plugin_dir(root).exists(), "emptied plugin dir pruned");
    }

    #[tokio::test]
    async fn test_remove_spares_user_authored_gemspec() {
        // Ownership is per file: our plugins.rb is removed, but a user-authored
        // (marker-less) file at the gemspec path must never be deleted on the
        // strength of plugins.rb's marker alone.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&plugins_rb_path(root), PLUGINS_RB).await;
        write(&gemspec_path(root), "# my own gemspec\n").await;

        let r = remove_plugin_files(root, false).await;
        assert_eq!(r.status, GemSetupStatus::Updated);
        assert!(!plugins_rb_path(root).exists(), "our plugins.rb removed");
        assert!(
            gemspec_path(root).exists(),
            "marker-less user file at the gemspec path must be left alone"
        );
        assert_eq!(
            fs::read_to_string(gemspec_path(root)).await.unwrap(),
            "# my own gemspec\n"
        );
    }

    #[tokio::test]
    async fn test_add_plugin_files_writes_each_template_to_its_own_path() {
        // Guards the path↔content mapping: plugins.rb must get PLUGINS_RB and the
        // gemspec must get GEMSPEC (not swapped). A swap would leave each file
        // failing its own `starts_with(GENERATED_MARKER)` content expectations.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        add_plugin_files(root, false).await;
        assert_eq!(
            fs::read_to_string(plugins_rb_path(root)).await.unwrap(),
            PLUGINS_RB,
            "plugins.rb must receive the plugins.rb template"
        );
        assert_eq!(
            fs::read_to_string(gemspec_path(root)).await.unwrap(),
            GEMSPEC,
            "gemspec must receive the gemspec template"
        );
    }

    #[tokio::test]
    async fn test_add_plugin_files_rewrites_stale_content() {
        // A drifted (hand-edited or older-version) plugins.rb must be re-synced to
        // the current template, and the call must report `Updated` — not silently
        // accept the stale bytes as already-configured.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(
            &plugins_rb_path(root),
            "# Code generated by stale\nold body\n",
        )
        .await;
        write(&gemspec_path(root), GEMSPEC).await;
        let r = add_plugin_files(root, false).await;
        assert_eq!(
            r.status,
            GemSetupStatus::Updated,
            "stale plugins.rb is re-synced"
        );
        assert_eq!(
            fs::read_to_string(plugins_rb_path(root)).await.unwrap(),
            PLUGINS_RB
        );
    }

    #[tokio::test]
    async fn test_add_plugin_files_syncs_only_the_drifted_file() {
        // plugins.rb already matches; only the gemspec drifted. The call rewrites
        // the gemspec, reports Updated, and leaves the matching plugins.rb intact.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&plugins_rb_path(root), PLUGINS_RB).await;
        write(&gemspec_path(root), "# drifted gemspec\n").await;
        let r = add_plugin_files(root, false).await;
        assert_eq!(r.status, GemSetupStatus::Updated);
        assert_eq!(
            fs::read_to_string(gemspec_path(root)).await.unwrap(),
            GEMSPEC
        );
        assert_eq!(
            fs::read_to_string(plugins_rb_path(root)).await.unwrap(),
            PLUGINS_RB
        );
    }

    #[tokio::test]
    async fn test_remove_plugin_files_dry_run_keeps_files() {
        // Dry-run remove reports the change but must not delete anything.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        add_plugin_files(root, false).await;
        let r = remove_plugin_files(root, true).await;
        assert_eq!(
            r.status,
            GemSetupStatus::Updated,
            "dry-run reports the removal"
        );
        assert!(
            plugin_files_present(root).await,
            "dry-run remove must not delete the plugin files"
        );
    }

    #[tokio::test]
    async fn test_plugin_files_present_requires_both() {
        // The "configured" signal must demand BOTH files, not either one.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&plugins_rb_path(root), PLUGINS_RB).await;
        assert!(
            !plugin_files_present(root).await,
            "plugins.rb alone is not 'configured' — the gemspec is required too"
        );
        write(&gemspec_path(root), GEMSPEC).await;
        assert!(plugin_files_present(root).await);
    }
}
