//! The generated sbt files: `socket-patch.sbt` (hosted, `get`) and
//! `socket-patch-vendor.sbt` (vendored, `vendor`), one model for both.
//!
//! Each file holds:
//! - a `@ID@Pins` table, two rows per pin (pom, then jar): coordinates, the
//!   suffixed version, the repo-relative path, the sha256 and the source URL
//!   (`""` when vendored);
//! - the shared helpers (`@ID@Fail`, `@ID@Sha256`, `@ID@Verify`), all carrying
//!   the `@ID@` prefix because top-level names are shared across a project's
//!   `.sbt` files; `@ID@Newer` compares two versions by their leading
//!   numbers, as `formats::sbt::build::numeric_newer` does;
//! - `Global / @ID@Rows`, publishing the table to the other file's installer;
//! - inside `inThisBuild(…)`, a resolver for the pin repository
//!   (`.socket/sbt-hosted/maven2`, which the hosted file fills at load from
//!   the pinned URLs and gitignores, or the committed `.socket/vendor/maven2`
//!   tree) and one `dependencyOverrides +=` per pin forcing
//!   `<base>-socket.<hex8>`;
//! - a `Global / onLoad` installer wrapping every project's `update` with the
//!   verifier V: no project may declare a pinned GA at a version newer than
//!   the pin's base (the override would force it back down; a dynamic
//!   version is not compared), each non-evicted pinned module must resolve
//!   the pinned version, and each of its artifacts must hash to one of that
//!   GA's pinned sha256s. Both files share the marker label `socketPatchApplied`, so
//!   whichever loads first installs one V over both files' rows.
//!
//! The bytes are frozen by the sbt template probe
//! (`docs/design/sbt-template-probe.md`, six sbt versions); [`render`] is
//! byte-identical to the probe's reference renderer, and the golden fixtures
//! under `tests/fixtures/sbt/owned_file/` are the probe's own renders. The
//! three syntax lines ([`SbtLine`]) differ only in the `@ID@Rows` setting
//! line and the installer.
//!
//! [`parse`] is strict: anything but bytes [`render`] would write, modulo
//! CRLF, is [`OwnedFileError::Modified`]. A file without the socket-patch
//! header is [`OwnedFileError::Foreign`].
//!
//! [`validate_values`] guards every value written into the template's Scala
//! string literals (always plain `"…"`, never `s"…"`), so each must be safe
//! there unescaped.

use std::collections::{BTreeMap, BTreeSet};
use std::sync::LazyLock;

use regex::Regex;

pub use super::build::SbtLine;
use crate::utils::digest::is_hex64_lower;
use crate::vendor::jvm::layout;

/// The hosted file, at the build root.
pub const HOSTED_FILE: &str = "socket-patch.sbt";
/// The vendored file, at the build root.
pub const VENDORED_FILE: &str = "socket-patch-vendor.sbt";
/// Where the hosted file downloads its pins (gitignored by the file itself).
pub const HOSTED_REPO_REL: &str = ".socket/sbt-hosted/maven2";
/// The vendored (committed, suffixed) tree.
pub const VENDORED_REPO_REL: &str = layout::MAVEN2_TREE;
/// The first line of every generated file (and the ownership test).
pub const HEADER_PREFIX: &str = "// Generated by socket-patch";

/// Which command owns the file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SbtFileMode {
    Hosted,
    Vendored,
}

impl SbtFileMode {
    /// The file's root-relative path.
    pub fn file(self) -> &'static str {
        match self {
            SbtFileMode::Hosted => HOSTED_FILE,
            SbtFileMode::Vendored => VENDORED_FILE,
        }
    }

    /// The pin repository, root-relative.
    pub fn repo_rel(self) -> &'static str {
        match self {
            SbtFileMode::Hosted => HOSTED_REPO_REL,
            SbtFileMode::Vendored => VENDORED_REPO_REL,
        }
    }

    /// The template constants: (command, identifier prefix, `.socket/` dir,
    /// resolver name).
    fn consts(self) -> (&'static str, &'static str, &'static str, &'static str) {
        match self {
            SbtFileMode::Hosted => ("get", "socketPatchHosted", "sbt-hosted", "socket-patch"),
            SbtFileMode::Vendored => (
                "vendor",
                "socketPatchVendor",
                "vendor",
                "socket-patch-vendor",
            ),
        }
    }
}

/// One pinned patch: two rows (pom, jar) and one override in the file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SbtPin {
    pub uuid: String,
    pub group: String,
    pub artifact: String,
    /// The upstream version the patch applies to.
    pub base: String,
    /// `<base>-socket.<first 8 hex of the uuid>`.
    pub sv: String,
    /// Bare lowercase sha256 hex of the served pom / jar (a `sha256-` /
    /// `sha256:` prefix is accepted and dropped on render).
    pub pom_sha256: String,
    pub jar_sha256: String,
    /// [`super::build::deps_digest`] when the pin was written.
    pub deps_digest: String,
    /// The hosted maven2 index URL the rows' sources live under; `None` for
    /// a vendored pin.
    pub index_url: Option<String>,
}

impl SbtPin {
    /// The pom (`ext == "pom"`) or jar path of this pin, relative to the pin
    /// repository.
    pub fn repo_path(&self, ext: &str) -> String {
        layout::artifact_path(&self.group, &self.artifact, &self.sv, None, ext)
    }
}

/// A parsed (or to-be-rendered) generated file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SbtOwnedFile {
    pub mode: SbtFileMode,
    pub line: SbtLine,
    /// The file uses `\r\n` line endings (kept on re-render).
    pub crlf: bool,
    /// Pins by uuid.
    pub pins: BTreeMap<String, SbtPin>,
}

/// Why a generated-file path does not hold a file socket-patch can own.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OwnedFileError {
    /// The header is socket-patch's, the rest is not what it writes.
    Modified(String),
    /// No socket-patch header: a user's own file under our name (the
    /// remedy is to rename it, never `git checkout`).
    Foreign,
}

/// Why [`render`] refused a model. Callers validate first; this is the
/// last guard before bytes reach a Scala file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenderError {
    /// Zero pins are never rendered (the last-out path deletes the file;
    /// an empty `Seq(…)` tail is invalid Scala 2.10).
    NoPins,
    /// A pin is unsafe or inconsistent with the file's mode.
    Invalid { uuid: String, reason: &'static str },
}

/// The shared body. `@ROWS@` / `@OVERRIDES@` are filled per file;
/// `@ROWS_SETTING@`, `@GITIGNORE@` and the constants per mode and line.
/// `@GITIGNORE@` is the whole hosted line (with its newline) or nothing.
const BODY: &str = r##"// Generated by socket-patch. Do not edit; re-run `socket-patch @CMD@`.
val @ID@Pins = Seq[(String, String, String, String, String, String)](
  // (group, artifact, socket version, repo-relative path, sha256, source URL; "" = vendored)
@ROWS@
)
val @ID@Rows = SettingKey[Seq[(String, String, String, String, String, String)]]("@ID@Rows")
val @ID@Applied = SettingKey[Boolean]("socketPatchApplied")
def @ID@Fail(m: String): Nothing = sys.error("socket-patch: " + m + ". Re-run `socket-patch @CMD@`.")
def @ID@Sha256(f: java.io.File): String = java.security.MessageDigest.getInstance("SHA-256")
  .digest(java.nio.file.Files.readAllBytes(f.toPath)).map(b => "%02x".format(b & 0xff)).mkString
def @ID@Newer(v: String, base: String): Boolean = {
  def nums(s: String): Seq[BigInt] = "^[0-9]+(\\.[0-9]+)*".r.findFirstIn(s.trim).toSeq.flatMap(_.split('.')).map(n => BigInt(n))
  nums(v).zipAll(nums(base), BigInt(0), BigInt(0)).find(t => t._1 != t._2).exists(t => t._1 > t._2)
}
def @ID@Verify(p: String, pins: Seq[(String, String, String, String, String, String)], deps: Seq[ModuleID], r: UpdateReport): UpdateReport = {
  deps.foreach { d => pins.find(x => x._1 == d.organization && (x._2 == d.name || x._2.startsWith(d.name + "_"))).foreach { case (g, a, sv, _, _, _) =>
    val base = sv.substring(0, sv.lastIndexOf("-socket."))
    if (!d.revision.exists(c => "+[](),".indexOf(c) >= 0) && !d.revision.startsWith("latest.") && @ID@Newer(d.revision, base)) @ID@Fail(p + " declares " + g + ":" + a + ":" + d.revision + " but socket-patch forces " + sv + " (a downgrade); roll the patch back, or declare " + base)
  } }
  r.configurations.foreach { c => c.modules.filter(!_.evicted).foreach { m =>
    val mine = pins.filter(x => x._1 == m.module.organization && x._2 == m.module.name)
    mine.headOption.foreach { case (g, a, sv, _, _, _) =>
      if (m.module.revision != sv) @ID@Fail(p + " resolves " + g + ":" + a + ":" + m.module.revision + ", expected " + sv + "; a dependencyOverrides := or resolver change in the build replaced socket-patch's")
      m.artifacts.foreach { case (_, f) =>
        val got = @ID@Sha256(f)
        if (!mine.exists(_._5 == got)) @ID@Fail(g + ":" + a + ":" + sv + " resolved to " + f + " with sha256 " + got + ", which is not pinned (tampered, or from ivy-local, mavenLocal or another checkout); delete it and run sbt update")
      }
    }
  } }
  r
}
@ROWS_SETTING@
inThisBuild(Seq(
  resolvers += {
    val repo = new java.io.File(baseDirectory.value, ".socket/@DIR@/maven2").getCanonicalFile
@GITIGNORE@    @ID@Pins.foreach { case (_, _, _, rel, want, src) =>
      val f = new java.io.File(repo, rel)
      if (!f.isFile || @ID@Sha256(f) != want) {
        if (src.isEmpty) @ID@Fail(if (f.isFile) "" + f + " has sha256 " + @ID@Sha256(f) + ", pinned " + want else "missing " + f)
        f.getParentFile.mkdirs()
        val tmp = java.io.File.createTempFile("socket-patch", ".part", f.getParentFile)
        try {
          try {
            val c = new java.net.URL(src).openConnection(); c.setConnectTimeout(30000); c.setReadTimeout(120000)
            val in = c.getInputStream
            try java.nio.file.Files.copy(in, tmp.toPath, java.nio.file.StandardCopyOption.REPLACE_EXISTING) finally in.close()
          } catch { case e: java.io.IOException => @ID@Fail("cannot download " + src + " (" + e + ")") }
          val got = @ID@Sha256(tmp)
          if (got != want) @ID@Fail("" + src + " served sha256 " + got + ", pinned " + want)
          java.nio.file.Files.move(tmp.toPath, f.toPath, java.nio.file.StandardCopyOption.REPLACE_EXISTING)
        } finally tmp.delete()
      }
    }
    "@RESOLVER@" at repo.toURI.toString
  },
@OVERRIDES@
))
"##;

/// The hosted-only line writing `.socket/sbt-hosted/.gitignore` (`*`). A
/// plain statement: a `{` block on its own line would parse as an argument
/// to the previous call.
const GITIGNORE: &str = r#"    val gitignore = new java.io.File(repo.getParentFile, ".gitignore"); if (!gitignore.isFile) { repo.mkdirs(); java.nio.file.Files.write(gitignore.toPath, "*\n".getBytes) }
"#;

/// The `onLoad` installer, 0.13 spelling (`in` scopes, `x.append`). It reads
/// both files' rows by label, so either file's installer enforces both.
const INSTALL_013: &str = r#"onLoad in Global := (onLoad in Global).value andThen { s =>
  val x = Project.extract(s)
  val pins = Seq("socketPatchHostedRows", "socketPatchVendorRows").flatMap(k => x.getOpt(SettingKey[Seq[(String, String, String, String, String, String)]](k) in Global).getOrElse(Nil))
  if (x.getOpt(@ID@Applied in Global).isDefined) s
  else x.append((@ID@Applied in Global := true) +: x.structure.allProjectRefs.flatMap(p => Seq[Def.Setting[_]](update in p := @ID@Verify(p.project, pins, (allDependencies in p).value, (update in p).value), externalResolvers in p := { val (ours, rest) = (externalResolvers in p).value.partition(r => r.name == "socket-patch" || r.name == "socket-patch-vendor"); ours ++ rest })), s)
}
"#;

/// The installer, 1.x spelling (slash scopes, `appendWithoutSession`).
const INSTALL_1: &str = r#"Global / onLoad := (Global / onLoad).value andThen { s =>
  val x = Project.extract(s)
  val pins = Seq("socketPatchHostedRows", "socketPatchVendorRows").flatMap(k => x.getOpt(Global / SettingKey[Seq[(String, String, String, String, String, String)]](k)).getOrElse(Nil))
  if (x.getOpt(Global / @ID@Applied).isDefined) s
  else x.appendWithoutSession((Global / @ID@Applied := true) +: x.structure.allProjectRefs.flatMap(p => Seq[Def.Setting[_]](p / update := @ID@Verify(p.project, pins, (p / allDependencies).value, (p / update).value), p / externalResolvers := { val (ours, rest) = (p / externalResolvers).value.partition(r => r.name == "socket-patch" || r.name == "socket-patch-vendor"); ours ++ rest })), s)
}
"#;

/// The installer, 2.x spelling: 1.x with `Def.uncached` around the wrapped
/// `update` (sbt 2 caches tasks).
const INSTALL_2: &str = r#"Global / onLoad := (Global / onLoad).value andThen { s =>
  val x = Project.extract(s)
  val pins = Seq("socketPatchHostedRows", "socketPatchVendorRows").flatMap(k => x.getOpt(Global / SettingKey[Seq[(String, String, String, String, String, String)]](k)).getOrElse(Nil))
  if (x.getOpt(Global / @ID@Applied).isDefined) s
  else x.appendWithoutSession((Global / @ID@Applied := true) +: x.structure.allProjectRefs.map(p => p / update := Def.uncached(@ID@Verify(p.project, pins, (p / allDependencies).value, (p / update).value))), s)
}
"#;

const ROWS: &str = "@ROWS@";
const OVERRIDES: &str = "@OVERRIDES@";

/// The full LF template for `mode` and `line`, with only `@ROWS@` and
/// `@OVERRIDES@` left (the probe's `.sbt.tpl` files).
fn template(mode: SbtFileMode, line: SbtLine) -> String {
    let (cmd, id, dir, resolver) = mode.consts();
    let (rows_setting, install) = match line {
        SbtLine::Sbt013 => ("@ID@Rows in Global := @ID@Pins", INSTALL_013),
        SbtLine::Sbt1 => ("Global / @ID@Rows := @ID@Pins", INSTALL_1),
        SbtLine::Sbt2 => ("Global / @ID@Rows := @ID@Pins", INSTALL_2),
    };
    let gitignore = match mode {
        SbtFileMode::Hosted => GITIGNORE,
        SbtFileMode::Vendored => "",
    };
    format!("{}{install}", BODY.replace("@ROWS_SETTING@", rows_setting))
        .replace("@RESOLVER@", resolver)
        .replace("@GITIGNORE@", gitignore)
        .replace("@CMD@", cmd)
        .replace("@ID@", id)
        .replace("@DIR@", dir)
}

/// The `src` column of a row: `<index>/<rel>` hosted, `""` vendored.
fn source_url(pin: &SbtPin, rel: &str) -> String {
    pin.index_url
        .as_deref()
        .map_or_else(String::new, |index| format!("{index}/{rel}"))
}

/// `items` joined one per line, `,` on every line but the last, then the
/// trailing `// socket-patch <comment>`.
fn join_lines(items: &[(String, String)]) -> String {
    let last = items.len().saturating_sub(1);
    items
        .iter()
        .enumerate()
        .map(|(i, (code, comment))| {
            let comma = if i < last { "," } else { "" };
            format!("{code}{comma} // socket-patch {comment}")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Whether `pin` may go into a file of `mode`, beyond [`validate_values`].
fn check_mode(mode: SbtFileMode, pin: &SbtPin) -> Result<(), &'static str> {
    match (mode, pin.index_url.as_deref()) {
        (SbtFileMode::Hosted, None) => Err("hosted pin has no index URL"),
        (SbtFileMode::Hosted, Some(url)) if !url.contains(&pin.uuid) => {
            Err("index URL does not name the patch uuid")
        }
        (SbtFileMode::Vendored, Some(_)) => Err("vendored pin has an index URL"),
        _ => Ok(()),
    }
}

/// The file's exact bytes for `f`: rows and overrides sorted by
/// `(group, artifact, sv)`, hashes bare, `\r\n` when `f.crlf`.
///
/// Refuses (never renders) zero pins, a pin keyed under another uuid, a pin
/// failing [`validate_values`] or its mode's URL rule, and two pins for one
/// `group:artifact` (one file forces one version per GA; callers replace or
/// refuse before rendering).
pub fn render(f: &SbtOwnedFile) -> Result<String, RenderError> {
    if f.pins.is_empty() {
        return Err(RenderError::NoPins);
    }
    let invalid = |p: &SbtPin, reason| RenderError::Invalid {
        uuid: p.uuid.clone(),
        reason,
    };
    let mut pins: Vec<&SbtPin> = Vec::with_capacity(f.pins.len());
    for (key, p) in &f.pins {
        if *key != p.uuid {
            return Err(invalid(p, "pin is keyed under another uuid"));
        }
        validate_values(p).map_err(|reason| invalid(p, reason))?;
        check_mode(f.mode, p).map_err(|reason| invalid(p, reason))?;
        pins.push(p);
    }
    pins.sort_by(|x, y| (&x.group, &x.artifact, &x.sv).cmp(&(&y.group, &y.artifact, &y.sv)));
    if let Some(w) = pins
        .windows(2)
        .find(|w| (&w[0].group, &w[0].artifact) == (&w[1].group, &w[1].artifact))
    {
        return Err(invalid(w[1], "two pins for one group:artifact"));
    }

    let mut rows = Vec::with_capacity(pins.len() * 2);
    let mut overrides = Vec::with_capacity(pins.len());
    for p in pins {
        for (ext, sha) in [("pom", &p.pom_sha256), ("jar", &p.jar_sha256)] {
            let rel = p.repo_path(ext);
            rows.push((
                format!(
                    "  (\"{}\", \"{}\", \"{}\", \"{rel}\", \"{}\", \"{}\")",
                    p.group,
                    p.artifact,
                    p.sv,
                    bare_sha256(sha),
                    source_url(p, &rel)
                ),
                p.uuid.clone(),
            ));
        }
        overrides.push((
            format!(
                "  dependencyOverrides += \"{}\" % \"{}\" % \"{}\"",
                p.group, p.artifact, p.sv
            ),
            format!("{} deps={}", p.uuid, p.deps_digest),
        ));
    }
    let text = template(f.mode, f.line)
        .replace(ROWS, &join_lines(&rows))
        .replace(OVERRIDES, &join_lines(&overrides));
    Ok(if f.crlf {
        text.replace('\n', "\r\n")
    } else {
        text
    })
}

static ROW: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r#"^  \("([^"]*)", "([^"]*)", "([^"]*)", "([^"]*)", "([0-9a-f]{64})", "([^"]*)"\)(,?) // socket-patch ([0-9a-f-]{36})$"#,
    )
    .expect("row regex")
});

static OVERRIDE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r#"^  dependencyOverrides \+= "([^"]*)" % "([^"]*)" % "([^"]*)"(,?) // socket-patch ([0-9a-f-]{36}) deps=([0-9a-f]{8})$"#,
    )
    .expect("override regex")
});

/// One parsed row.
struct Row<'t> {
    group: &'t str,
    artifact: &'t str,
    sv: &'t str,
    rel: &'t str,
    sha256: &'t str,
    src: &'t str,
    uuid: &'t str,
}

/// Lines of a region between fixed text, each matched by `re`, with the
/// comma rule checked: `,` (capture `comma`) on every line but the last.
fn region_lines<'t>(
    region: &'t str,
    re: &Regex,
    comma: usize,
    what: &str,
) -> Result<Vec<regex::Captures<'t>>, OwnedFileError> {
    let lines: Vec<&str> = region.split('\n').collect();
    let last = lines.len() - 1;
    let mut out = Vec::with_capacity(lines.len());
    for (i, l) in lines.into_iter().enumerate() {
        let caps = re.captures(l).ok_or_else(|| {
            OwnedFileError::Modified(format!("{what} {} is not one socket-patch writes", i + 1))
        })?;
        if caps[comma].is_empty() != (i == last) {
            return Err(OwnedFileError::Modified(format!(
                "{what} {} has a misplaced trailing comma",
                i + 1
            )));
        }
        out.push(caps);
    }
    Ok(out)
}

/// A `Modified` error.
fn modified(reason: impl Into<String>) -> OwnedFileError {
    OwnedFileError::Modified(reason.into())
}

/// The 1-based number of the first line where `text` and `fixed` differ.
fn first_differing_line(text: &str, fixed: &str) -> usize {
    text.split('\n')
        .zip(fixed.split('\n'))
        .take_while(|(a, b)| a == b)
        .count()
        + 1
}

/// Strict parse of a generated file of `mode`. The syntax line comes from
/// the installer the file carries.
///
/// - No socket-patch header (after an optional BOM) → [`OwnedFileError::Foreign`].
/// - Otherwise [`OwnedFileError::Modified`] unless: every fixed line is the
///   template's; every row and override matches its grammar with `,` on
///   all but the last; each pin has exactly a pom row then a jar row and one
///   override (in row order), with the same coordinates and uuid; the rels
///   are the coordinates' paths; hosted sources are `<index>/<rel>` under
///   one index naming the uuid, vendored sources `""`; every pin passes
///   [`validate_values`]; and the text re-renders byte-identically (modulo
///   CRLF), which also fixes the order and one pin per GA.
pub fn parse(mode: SbtFileMode, text: &str) -> Result<SbtOwnedFile, OwnedFileError> {
    let unbommed = text.trim_start_matches('\u{feff}');
    if !unbommed.starts_with(HEADER_PREFIX) {
        return Err(OwnedFileError::Foreign);
    }
    if unbommed.len() != text.len() {
        return Err(modified("the file starts with a byte-order mark"));
    }
    let crlf = text.contains("\r\n");
    let norm = text.replace("\r\n", "\n");
    if norm.contains('\r') {
        return Err(modified("the file has a stray carriage return"));
    }

    // The fixed text around the two regions; the head is shared by every line.
    let lines = [SbtLine::Sbt013, SbtLine::Sbt1, SbtLine::Sbt2];
    let tpl = template(mode, SbtLine::Sbt1);
    let (head, _) = tpl.split_once(ROWS).expect("template has rows");
    if !norm.starts_with(head) {
        return Err(modified(format!(
            "line {} is not socket-patch's",
            first_differing_line(&norm, head)
        )));
    }
    let mut found = None;
    for line in lines {
        let tpl = template(mode, line);
        let (_, rest) = tpl.split_once(ROWS).expect("template has rows");
        let (mid, tail) = rest.split_once(OVERRIDES).expect("template has overrides");
        let Some(body) = norm[head.len()..].strip_suffix(tail) else {
            continue;
        };
        if let Some((rows, overrides)) = body.split_once(mid) {
            found = Some((line, rows.to_string(), overrides.to_string()));
            break;
        }
    }
    let Some((line, rows_text, overrides_text)) = found else {
        return Err(modified(
            "the settings after the pin rows are not socket-patch's template",
        ));
    };
    if rows_text.is_empty() || overrides_text.is_empty() {
        return Err(modified("the file pins nothing"));
    }

    let rows: Vec<Row> = region_lines(&rows_text, &ROW, 7, "pin row")?
        .iter()
        .map(|c| Row {
            group: c.get(1).map_or("", |m| m.as_str()),
            artifact: c.get(2).map_or("", |m| m.as_str()),
            sv: c.get(3).map_or("", |m| m.as_str()),
            rel: c.get(4).map_or("", |m| m.as_str()),
            sha256: c.get(5).map_or("", |m| m.as_str()),
            src: c.get(6).map_or("", |m| m.as_str()),
            uuid: c.get(8).map_or("", |m| m.as_str()),
        })
        .collect();
    let overrides = region_lines(&overrides_text, &OVERRIDE, 4, "override")?;
    if !rows.len().is_multiple_of(2) {
        return Err(modified(
            "a pin does not have exactly a pom row and a jar row",
        ));
    }
    if rows.len() / 2 != overrides.len() {
        return Err(modified(
            "the overrides do not match the pin rows one to one",
        ));
    }

    let mut pins = BTreeMap::new();
    let mut seen = BTreeSet::new();
    for (pair, ov) in rows.chunks(2).zip(&overrides) {
        let (pom, jar) = (&pair[0], &pair[1]);
        let uuid = pom.uuid;
        let bad = |why: &str| modified(format!("pin {uuid}: {why}"));
        if !seen.insert(uuid) {
            return Err(bad("the uuid has more than two rows"));
        }
        if (jar.uuid, jar.group, jar.artifact, jar.sv) != (uuid, pom.group, pom.artifact, pom.sv) {
            return Err(bad("its pom and jar rows disagree"));
        }
        if (&ov[1], &ov[2], &ov[3], &ov[5]) != (pom.group, pom.artifact, pom.sv, uuid) {
            return Err(bad("its override does not match its rows"));
        }
        let mut index = None;
        for (row, ext) in [(pom, "pom"), (jar, "jar")] {
            if row.rel != layout::artifact_path(row.group, row.artifact, row.sv, None, ext) {
                return Err(bad(&format!("the {ext} path is not its coordinates' path")));
            }
            match mode {
                SbtFileMode::Vendored if !row.src.is_empty() => {
                    return Err(bad("a vendored row has a source URL"));
                }
                SbtFileMode::Vendored => {}
                SbtFileMode::Hosted => {
                    let Some(i) = row
                        .src
                        .strip_suffix(row.rel)
                        .and_then(|s| s.strip_suffix('/'))
                    else {
                        return Err(bad(&format!("the {ext} source URL is not under its path")));
                    };
                    if index.is_some_and(|prev| prev != i) {
                        return Err(bad("its pom and jar come from different indexes"));
                    }
                    index = Some(i);
                }
            }
        }
        let hex8 = crate::vendor::jvm::Coords {
            group_id: "",
            artifact_id: "",
            version: "",
            uuid,
        }
        .hex8();
        let Some(base) = pom.sv.strip_suffix(&format!("-socket.{hex8}")) else {
            return Err(bad("the version is not the uuid's suffixed version"));
        };
        let pin = SbtPin {
            uuid: uuid.to_string(),
            group: pom.group.to_string(),
            artifact: pom.artifact.to_string(),
            base: base.to_string(),
            sv: pom.sv.to_string(),
            pom_sha256: pom.sha256.to_string(),
            jar_sha256: jar.sha256.to_string(),
            deps_digest: ov[6].to_string(),
            index_url: index.map(str::to_string),
        };
        validate_values(&pin).map_err(&bad)?;
        check_mode(mode, &pin).map_err(bad)?;
        pins.insert(pin.uuid.clone(), pin);
    }

    let file = SbtOwnedFile {
        mode,
        line,
        crlf,
        pins,
    };
    match render(&SbtOwnedFile {
        crlf: false,
        ..file.clone()
    }) {
        Ok(again) if again == norm => Ok(file),
        Ok(_) => Err(modified("the pins are not in socket-patch's order")),
        Err(RenderError::Invalid { uuid, reason }) => {
            Err(modified(format!("pin {uuid}: {reason}")))
        }
        Err(RenderError::NoPins) => Err(modified("the file pins nothing")),
    }
}

/// `hash` as bare lowercase hex: a `sha256-` / `sha256:` prefix and
/// surrounding whitespace dropped (the patch API spells it several ways).
pub fn bare_sha256(hash: &str) -> String {
    crate::patch::redirect::bare_sha256_hex(hash)
}

/// The suffixed version for `base` and `uuid`: `<base>-socket.<hex8>`.
pub fn suffixed_version(base: &str, uuid: &str) -> String {
    crate::vendor::jvm::Coords {
        group_id: "",
        artifact_id: "",
        version: base,
        uuid,
    }
    .suffixed_version()
}

/// Whether every value of `p` is safe to write into the template's Scala
/// string literals and repository paths; the reason when not.
pub fn validate_values(p: &SbtPin) -> Result<(), &'static str> {
    static URL: LazyLock<Regex> =
        LazyLock::new(|| Regex::new(r"^https?://[A-Za-z0-9._~:/%+-]+$").expect("regex"));
    if !crate::patch::path_safety::is_canonical_uuid(&p.uuid) {
        return Err("uuid is not a canonical uuid");
    }
    if !layout::safe_coordinates(&p.group, &p.artifact, &p.base) {
        return Err("unsafe maven coordinates");
    }
    if p.sv != suffixed_version(&p.base, &p.uuid) {
        return Err("suffixed version does not match the base and uuid");
    }
    if !layout::safe_coordinates(&p.group, &p.artifact, &p.sv) {
        return Err("unsafe suffixed version");
    }
    for hash in [&p.pom_sha256, &p.jar_sha256] {
        if !is_hex64_lower(&bare_sha256(hash)) {
            return Err("sha256 is not 64 hex digits");
        }
    }
    if p.deps_digest.len() != 8
        || !p
            .deps_digest
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
    {
        return Err("dependency digest is not 8 lowercase hex digits");
    }
    if let Some(url) = &p.index_url {
        if !URL.is_match(url) {
            return Err("index URL has characters outside the safe set");
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const UUID: &str = "abcdef12-3456-4789-8abc-def012345678";

    fn pin() -> SbtPin {
        SbtPin {
            uuid: UUID.into(),
            group: "org.apache.commons".into(),
            artifact: "commons-lang3".into(),
            base: "3.11".into(),
            sv: "3.11-socket.abcdef12".into(),
            pom_sha256: "a".repeat(64),
            jar_sha256: format!("sha256-{}", "B".repeat(64)),
            deps_digest: "0123abcd".into(),
            index_url: Some(format!(
                "https://patch.socket.dev/patch-registry/maven/tok/{UUID}/maven2"
            )),
        }
    }

    // The probe's two pins (tpl-probe harness/mkfix.py), with the hashes of
    // the fixture pom/jar bytes it served.
    const LANG3: &str = "abcdef12-0000-4000-8000-000000000001";
    const TEXT: &str = "12345678-0000-4000-8000-000000000002";

    fn probe_pin(uuid: &str, mode: SbtFileMode) -> SbtPin {
        let (artifact, base, pom, jar, deps) = if uuid == LANG3 {
            (
                "commons-lang3",
                "3.11",
                "b883c974d2b1e818d95e597c6c0c48ac79bd8bef5d148c2a55e503b061431f7f",
                "9a89cb5d42d1007bdf1c8fcaa621088adea13d4bb3ee3880c30eda55459b2940",
                "0a1b2c3d",
            )
        } else {
            (
                "commons-text",
                "1.9",
                "769677b191e5c2d2b1a616d8ae779909f1008955758ddfb3414c4b007154b237",
                "60588301ab3c82c261151a35fad5e547a635e0e5b90985f4c2a668e5cea0ac2e",
                "4e5f6a7b",
            )
        };
        SbtPin {
            uuid: uuid.into(),
            group: "org.apache.commons".into(),
            artifact: artifact.into(),
            base: base.into(),
            sv: suffixed_version(base, uuid),
            pom_sha256: pom.into(),
            jar_sha256: jar.into(),
            deps_digest: deps.into(),
            index_url: (mode == SbtFileMode::Hosted)
                .then(|| format!("https://localhost:8443/patch-registry/maven/good/{uuid}/maven2")),
        }
    }

    fn probe_file(mode: SbtFileMode, line: SbtLine, n: usize) -> SbtOwnedFile {
        SbtOwnedFile {
            mode,
            line,
            crlf: false,
            pins: [LANG3, TEXT][..n]
                .iter()
                .map(|u| (u.to_string(), probe_pin(u, mode)))
                .collect(),
        }
    }

    /// Every golden: (mode, line, pins, the probe's bytes).
    fn goldens() -> Vec<(SbtFileMode, SbtLine, usize, &'static str)> {
        use SbtFileMode::{Hosted, Vendored};
        use SbtLine::{Sbt013, Sbt1, Sbt2};
        macro_rules! fx {
            ($name:literal) => {
                include_str!(concat!(
                    "../../../tests/fixtures/sbt/owned_file/",
                    $name,
                    ".sbt"
                ))
            };
        }
        vec![
            (Hosted, Sbt013, 1, fx!("hosted-013-1pin")),
            (Hosted, Sbt013, 2, fx!("hosted-013-2pin")),
            (Hosted, Sbt1, 1, fx!("hosted-1-1pin")),
            (Hosted, Sbt1, 2, fx!("hosted-1-2pin")),
            (Hosted, Sbt2, 1, fx!("hosted-2-1pin")),
            (Hosted, Sbt2, 2, fx!("hosted-2-2pin")),
            (Vendored, Sbt013, 1, fx!("vendored-013-1pin")),
            (Vendored, Sbt013, 2, fx!("vendored-013-2pin")),
            (Vendored, Sbt1, 1, fx!("vendored-1-1pin")),
            (Vendored, Sbt1, 2, fx!("vendored-1-2pin")),
            (Vendored, Sbt2, 1, fx!("vendored-2-1pin")),
            (Vendored, Sbt2, 2, fx!("vendored-2-2pin")),
        ]
    }

    fn golden(mode: SbtFileMode, line: SbtLine, n: usize) -> &'static str {
        goldens()
            .into_iter()
            .find(|g| (g.0, g.1, g.2) == (mode, line, n))
            .expect("golden")
            .3
    }

    #[test]
    fn render_is_byte_identical_to_the_probe_renders() {
        for (mode, line, n, bytes) in goldens() {
            let got = render(&probe_file(mode, line, n)).expect("renders");
            assert_eq!(got, bytes, "{mode:?} {line:?} {n} pins");
        }
    }

    #[test]
    fn parse_round_trips_every_golden() {
        for (mode, line, n, bytes) in goldens() {
            let parsed = parse(mode, bytes).expect("parses");
            assert_eq!(parsed, probe_file(mode, line, n), "{mode:?} {line:?} {n}");
            assert_eq!(render(&parsed).as_deref(), Ok(bytes));
        }
    }

    #[test]
    fn crlf_is_kept_on_render_and_detected_on_parse() {
        for (mode, line, n, bytes) in goldens() {
            let mut f = probe_file(mode, line, n);
            f.crlf = true;
            let crlf = render(&f).expect("renders");
            assert_eq!(crlf, bytes.replace('\n', "\r\n"));
            assert_eq!(parse(mode, &crlf), Ok(f.clone()));
            assert_eq!(render(&parse(mode, &crlf).unwrap()), Ok(crlf));
        }
    }

    #[test]
    fn render_sorts_by_coordinates_and_drops_hash_prefixes() {
        let mut f = probe_file(SbtFileMode::Hosted, SbtLine::Sbt1, 2);
        // A uuid sorting first but coordinates sorting last keeps row order.
        let p = f.pins.get_mut(LANG3).unwrap();
        p.pom_sha256 = format!("sha256-{}", p.pom_sha256.to_uppercase());
        p.jar_sha256 = format!("sha256:{}", p.jar_sha256);
        assert_eq!(
            render(&f).as_deref(),
            Ok(golden(SbtFileMode::Hosted, SbtLine::Sbt1, 2))
        );
    }

    #[test]
    fn templates_differ_only_where_the_probe_says() {
        // Hosted vs vendored: the .gitignore line, and the vendored file has
        // no other extra or missing line.
        let h = template(SbtFileMode::Hosted, SbtLine::Sbt1);
        let v = template(SbtFileMode::Vendored, SbtLine::Sbt1);
        assert_eq!(h.lines().count(), v.lines().count() + 1);
        assert!(h.contains(".socket/sbt-hosted/maven2") && v.contains(".socket/vendor/maven2"));
        assert!(h.contains(&format!("\"{}\"", HOSTED_REPO_REL)));
        assert!(v.contains(&format!("\"{}\"", VENDORED_REPO_REL)));
        assert!(v.contains("\"socket-patch-vendor\" at") && !v.contains("gitignore"));
        assert!(h.contains("\"socket-patch\" at") && h.contains("\"*\\n\".getBytes"));
        let interpolated = Regex::new(r#"[ (,=+{]s""#).unwrap();
        for line in [SbtLine::Sbt013, SbtLine::Sbt1, SbtLine::Sbt2] {
            for mode in [SbtFileMode::Hosted, SbtFileMode::Vendored] {
                let t = template(mode, line);
                assert!(!interpolated.is_match(&t), "no interpolated literals");
                assert_eq!(
                    t.matches("@ROWS@").count() + t.matches("@OVERRIDES@").count(),
                    2
                );
                assert_eq!(t.matches('@').count(), 4, "{mode:?} {line:?}");
                assert!(t.contains("SettingKey[Boolean](\"socketPatchApplied\")"));
            }
        }
    }

    #[test]
    fn foreign_files_have_no_socket_patch_header() {
        for text in [
            "resolvers += \"x\" at \"y\"\n",
            "",
            "\u{feff}// my own build file\n",
            "  // Generated by socket-patch. Do not edit\n",
        ] {
            assert_eq!(
                parse(SbtFileMode::Hosted, text),
                Err(OwnedFileError::Foreign)
            );
        }
        assert!(matches!(
            parse(
                SbtFileMode::Vendored,
                "// Generated by socket-patch. Do not edit; re-run `socket-patch vendor`.\n"
            ),
            Err(OwnedFileError::Modified(_))
        ));
    }

    /// The rows and overrides of `text`, in file order.
    fn regions(text: &str) -> (Vec<String>, Vec<String>) {
        let pick = |prefix: &str| {
            text.lines()
                .filter(|l| l.starts_with(prefix))
                .map(str::to_string)
                .collect()
        };
        (pick("  (\""), pick("  dependencyOverrides"))
    }

    /// The file of `mode`/`line` holding exactly `rows` and `overrides`,
    /// commas re-placed so only the edit under test is wrong.
    fn assemble(mode: SbtFileMode, line: SbtLine, rows: &[String], ovs: &[String]) -> String {
        let recomma = |lines: &[String]| {
            let items: Vec<(String, String)> = lines
                .iter()
                .map(|l| {
                    let (code, comment) = l.split_once(" // socket-patch ").expect("comment");
                    (code.trim_end_matches(',').to_string(), comment.to_string())
                })
                .collect();
            join_lines(&items)
        };
        template(mode, line)
            .replace(ROWS, &recomma(rows))
            .replace(OVERRIDES, &recomma(ovs))
    }

    #[test]
    fn assemble_reproduces_the_goldens() {
        for (mode, line, _, bytes) in goldens() {
            let (rows, ovs) = regions(bytes);
            assert_eq!(assemble(mode, line, &rows, &ovs), bytes);
        }
    }

    #[test]
    fn every_strictness_failure_is_modified() {
        use SbtFileMode::{Hosted, Vendored};
        use SbtLine::Sbt1;
        let h = golden(Hosted, Sbt1, 2);
        let v = golden(Vendored, Sbt1, 2);
        let (rows, ovs) = regions(h);
        let (vrows, vovs) = regions(v);
        // `rows` with row `i` edited by `f`.
        let edit_row = |i: usize, f: &dyn Fn(&str) -> String| {
            let mut r = rows.clone();
            r[i] = f(&r[i]);
            assemble(Hosted, Sbt1, &r, &ovs)
        };
        let edit_ov = |i: usize, f: &dyn Fn(&str) -> String| {
            let mut o = ovs.clone();
            o[i] = f(&o[i]);
            assemble(Hosted, Sbt1, &rows, &o)
        };
        let lang3_index =
            format!("https://localhost:8443/patch-registry/maven/good/{LANG3}/maven2");
        let other = "abcdef12-0000-4000-8000-000000000009";
        let cases: Vec<(SbtFileMode, String, &str)> = vec![
            // Encoding.
            (Hosted, format!("\u{feff}{h}"), "byte-order mark"),
            (Hosted, h.replacen('\n', "\r", 1), "carriage return"),
            // Fixed lines.
            (
                Hosted,
                h.replace("val socketPatchHostedPins", "val pins"),
                "line 2",
            ),
            (
                Hosted,
                h.replacen(
                    "re-run `socket-patch get`",
                    "re-run `socket-patch vendor`",
                    1,
                ),
                "line 1",
            ),
            (Vendored, h.to_string(), "line 1"),
            (Hosted, v.to_string(), "line 1"),
            (Hosted, h.replace("30000", "3000"), "settings after"),
            (
                Hosted,
                h.replace("Verify(p.project", "Check(p.project"),
                "settings after",
            ),
            (Hosted, h.trim_end().to_string(), "settings after"),
            (Hosted, format!("{h}\n"), "settings after"),
            (
                Hosted,
                format!("{h}resolvers += Resolver.mavenLocal\n"),
                "settings after",
            ),
            (
                Hosted,
                h.replace(
                    &INSTALL_1.replace("@ID@", "socketPatchHosted"),
                    &INSTALL_013.replace("@ID@", "socketPatchHosted"),
                ),
                "settings after",
            ),
            (
                Hosted,
                template(Hosted, Sbt1)
                    .replace(ROWS, "")
                    .replace(OVERRIDES, ""),
                "pins nothing",
            ),
            (
                Hosted,
                template(Hosted, Sbt1)
                    .replace("@ROWS@\n", "")
                    .replace("@OVERRIDES@\n", ""),
                "settings after",
            ),
            // Row grammar and commas.
            (
                Hosted,
                edit_row(0, &|r| r.replacen(",", "", 1)),
                "pin row 1",
            ),
            (
                Hosted,
                edit_row(0, &|r| r.replacen("\"b883c974", "\"B883C974", 1)),
                "pin row 1",
            ),
            (
                Hosted,
                edit_row(0, &|r| r.replacen("\"b883c974", "\"883c974", 1)),
                "pin row 1",
            ),
            (Hosted, edit_row(0, &|r| format!(" {r}")), "pin row 1"),
            (
                Hosted,
                edit_row(0, &|r| {
                    r.replacen(
                        &format!("// socket-patch {LANG3}"),
                        "// socket-patch abcdef12-0000-4000-8000-00000000000X",
                        1,
                    )
                }),
                "pin row 1",
            ),
            (Hosted, edit_row(0, &|r| format!("{r} extra")), "pin row 1"),
            (
                Hosted,
                h.replacen(
                    &format!("{}\n", rows[0]),
                    &format!("{}\n", rows[0].replacen("),", ")", 1)),
                    1,
                ),
                "comma",
            ),
            (
                Hosted,
                h.replacen(
                    &format!("{}\n)", rows[3]),
                    &format!("{}\n)", rows[3].replacen(") //", "), //", 1)),
                    1,
                ),
                "comma",
            ),
            (
                Hosted,
                h.replacen(
                    &format!("{}\n))", ovs[1]),
                    &format!("{}\n))", ovs[1].replacen("\" //", "\", //", 1)),
                    1,
                ),
                "comma",
            ),
            // Row structure.
            (
                Hosted,
                assemble(Hosted, Sbt1, &rows[1..], &ovs),
                "exactly a pom row",
            ),
            (
                Hosted,
                assemble(
                    Hosted,
                    Sbt1,
                    &[
                        rows[1].clone(),
                        rows[0].clone(),
                        rows[2].clone(),
                        rows[3].clone(),
                    ],
                    &ovs,
                ),
                "pom path",
            ),
            (Hosted, edit_row(1, &|r| r.replace(LANG3, TEXT)), "disagree"),
            (
                Hosted,
                edit_row(1, &|r| {
                    r.replacen("\"3.11-socket.abcdef12\"", "\"3.12-socket.abcdef12\"", 1)
                }),
                "disagree",
            ),
            (
                Hosted,
                edit_row(0, &|r| {
                    r.replacen("abcdef12.pom\", \"", "abcdef12.jar\", \"", 1)
                }),
                "pom path",
            ),
            (
                Hosted,
                assemble(
                    Hosted,
                    Sbt1,
                    &[
                        rows[0].clone(),
                        rows[1].clone(),
                        rows[0].clone(),
                        rows[1].clone(),
                    ],
                    &[ovs[0].clone(), ovs[0].clone()],
                ),
                "more than two rows",
            ),
            // Sources.
            (
                Hosted,
                edit_row(0, &|r| {
                    r.replacen(
                        &format!("{lang3_index}/org"),
                        &format!("{lang3_index}/x/org"),
                        1,
                    )
                }),
                "different indexes",
            ),
            (
                Hosted,
                edit_row(0, &|r| r.replacen(".pom\")", ".pomx\")", 1)),
                "not under its path",
            ),
            (
                Hosted,
                edit_row(0, &|r| r.replacen(&format!("\"{lang3_index}/"), "\"", 1)),
                "not under its path",
            ),
            (
                Hosted,
                edit_row(0, &|r| {
                    r.replacen(&format!("\"{lang3_index}/org/apache/commons/commons-lang3/3.11-socket.abcdef12/commons-lang3-3.11-socket.abcdef12.pom\""), "\"\"", 1)
                }),
                "not under its path",
            ),
            (
                Hosted,
                h.replace(&format!("good/{LANG3}/"), "good/x/"),
                "uuid",
            ),
            (
                Hosted,
                h.replace(&lang3_index, &format!("file:///tmp/{LANG3}")),
                "safe set",
            ),
            (
                Hosted,
                h.replace(&lang3_index, &format!("https://x/${{HOME}}/{LANG3}")),
                "safe set",
            ),
            (
                Vendored,
                {
                    let mut r = vrows.clone();
                    r[0] = r[0].replacen(
                        "\"\")",
                        &format!(
                            "\"{lang3_index}/{}\")",
                            probe_pin(LANG3, Vendored).repo_path("pom")
                        ),
                        1,
                    );
                    assemble(Vendored, Sbt1, &r, &vovs)
                },
                "vendored row",
            ),
            // Overrides.
            (
                Hosted,
                assemble(Hosted, Sbt1, &rows, &ovs[..1]),
                "one to one",
            ),
            (
                Hosted,
                assemble(
                    Hosted,
                    Sbt1,
                    &rows,
                    &[ovs[0].clone(), ovs[0].clone(), ovs[1].clone()],
                ),
                "one to one",
            ),
            (
                Hosted,
                assemble(Hosted, Sbt1, &rows, &[ovs[1].clone(), ovs[0].clone()]),
                "override does not match",
            ),
            (
                Hosted,
                edit_ov(0, &|o| o.replacen("+=", ":=", 1)),
                "override 1",
            ),
            (
                Hosted,
                edit_ov(0, &|o| o.replacen("% \"commons", "%% \"commons", 1)),
                "override 1",
            ),
            (
                Hosted,
                edit_ov(0, &|o| o.replacen("deps=0a1b2c3d", "deps=0A1B2C3D", 1)),
                "override 1",
            ),
            (
                Hosted,
                edit_ov(0, &|o| o.replacen(" deps=0a1b2c3d", "", 1)),
                "override 1",
            ),
            (
                Hosted,
                edit_ov(0, &|o| o.replacen("\"3.11-socket", "\"3.12-socket", 1)),
                "override does not match",
            ),
            (
                Hosted,
                edit_ov(0, &|o| o.replacen(LANG3, other, 1)),
                "override does not match",
            ),
            // Values.
            (
                Hosted,
                h.replace("3.11-socket.abcdef12", "3.11-socket.12345678"),
                "suffixed version",
            ),
            (
                Hosted,
                h.replace("org.apache.commons\"", "org.apache.common$\"")
                    .replace("org/apache/commons", "org/apache/common$"),
                "unsafe maven coordinates",
            ),
            (
                Hosted,
                h.replace("org.apache.commons\"", "org..commons\"")
                    .replace("org/apache/commons", "org//commons"),
                "unsafe maven coordinates",
            ),
            (
                Hosted,
                h.replace("\"commons-text\"", "\"common\\\"s\"")
                    .replace("commons-text-", "common\\\"s-")
                    .replace("commons-text/", "common\\\"s/"),
                "pin row 3",
            ),
            // Order and one pin per GA: only the re-render can tell.
            (
                Hosted,
                assemble(
                    Hosted,
                    Sbt1,
                    &[
                        rows[2].clone(),
                        rows[3].clone(),
                        rows[0].clone(),
                        rows[1].clone(),
                    ],
                    &[ovs[1].clone(), ovs[0].clone()],
                ),
                "order",
            ),
            (
                Hosted,
                {
                    let twin = |s: &str| {
                        s.replace(TEXT, other)
                            .replace("commons-text", "commons-lang3")
                            .replace("1.9-socket.12345678", "3.12-socket.abcdef12")
                    };
                    let r: Vec<String> = rows[..2]
                        .iter()
                        .cloned()
                        .chain(rows[2..].iter().map(|r| twin(r)))
                        .collect();
                    let o = vec![ovs[0].clone(), twin(&ovs[1])];
                    assemble(Hosted, Sbt1, &r, &o)
                },
                "two pins for one group:artifact",
            ),
        ];
        for (mode, text, why) in cases {
            match parse(mode, &text) {
                Err(OwnedFileError::Modified(reason)) => {
                    assert!(reason.contains(why), "want {why:?}, got {reason:?}")
                }
                other => panic!("{why}: expected Modified, got {other:?}"),
            }
        }
    }

    #[test]
    fn render_refuses_what_it_must_never_write() {
        let invalid = |f: &SbtOwnedFile| match render(f) {
            Err(RenderError::Invalid { reason, .. }) => reason,
            other => panic!("expected Invalid, got {other:?}"),
        };
        let mut f = probe_file(SbtFileMode::Hosted, SbtLine::Sbt1, 2);
        f.pins.clear();
        assert_eq!(render(&f), Err(RenderError::NoPins));

        let mut f = probe_file(SbtFileMode::Hosted, SbtLine::Sbt1, 1);
        let p = f.pins.remove(LANG3).unwrap();
        f.pins.insert(TEXT.into(), p);
        assert!(invalid(&f).contains("keyed"));

        let mut f = probe_file(SbtFileMode::Hosted, SbtLine::Sbt2, 1);
        f.pins.get_mut(LANG3).unwrap().index_url = None;
        assert!(invalid(&f).contains("no index URL"));
        f.pins.get_mut(LANG3).unwrap().index_url = Some("https://x/maven2".into());
        assert!(invalid(&f).contains("uuid"));
        f.pins.get_mut(LANG3).unwrap().group = "org.ex\"ample".into();
        assert!(invalid(&f).contains("coordinates"));

        let mut f = probe_file(SbtFileMode::Vendored, SbtLine::Sbt013, 1);
        f.pins.get_mut(LANG3).unwrap().index_url = Some("https://x/maven2".into());
        assert!(invalid(&f).contains("vendored pin"));

        let mut f = probe_file(SbtFileMode::Vendored, SbtLine::Sbt1, 2);
        let t = f.pins.get_mut(TEXT).unwrap();
        t.artifact = "commons-lang3".into();
        assert!(invalid(&f).contains("two pins"));
    }

    #[test]
    fn validate_values_accepts_a_good_pin_and_prefixed_hashes() {
        assert_eq!(validate_values(&pin()), Ok(()));
        let mut p = pin();
        p.pom_sha256 = format!("sha256:{}", "c".repeat(64));
        p.index_url = None;
        assert_eq!(validate_values(&p), Ok(()));
        assert_eq!(bare_sha256(" SHA256-AB "), "ab");
    }

    #[test]
    fn validate_values_rejects_every_unsafe_value() {
        type Mutate = fn(&mut SbtPin);
        let cases: Vec<(Mutate, &str)> = vec![
            (|p| p.uuid = "not-a-uuid".into(), "uuid"),
            (|p| p.uuid = UUID.to_uppercase(), "uuid"),
            (|p| p.group = "org.ex\"ample".into(), "coordinates"),
            (|p| p.group = "org/apache".into(), "coordinates"),
            (|p| p.group = "org..apache".into(), "coordinates"),
            (|p| p.artifact = "a$b".into(), "coordinates"),
            (|p| p.artifact = "..".into(), "coordinates"),
            (|p| p.artifact = "a--b".into(), "coordinates"),
            (|p| p.artifact = "a\\b".into(), "coordinates"),
            (|p| p.base = "1 0".into(), "coordinates"),
            (|p| p.base = "latest.release".into(), "coordinates"),
            (|p| p.base = "1.0+".into(), "coordinates"),
            (|p| p.sv = "3.11-socket.00000000".into(), "suffixed"),
            (|p| p.sv = "3.11".into(), "suffixed"),
            (|p| p.pom_sha256 = "a".repeat(63), "sha256"),
            (|p| p.jar_sha256 = "z".repeat(64), "sha256"),
            (
                |p| p.jar_sha256 = format!("md5-{}", "a".repeat(64)),
                "sha256",
            ),
            (|p| p.deps_digest = "ABCDEF01".into(), "digest"),
            (|p| p.deps_digest = "abc".into(), "digest"),
            (
                |p| p.index_url = Some("https://x/\"+sys.exit()+\"".into()),
                "URL",
            ),
            (|p| p.index_url = Some("file:///etc".into()), "URL"),
            (|p| p.index_url = Some("https://x/${HOME}".into()), "URL"),
            (|p| p.index_url = Some("https://x/a b".into()), "URL"),
            (|p| p.index_url = Some("https://x/\\u0022".into()), "URL"),
            (|p| p.index_url = Some("https://x/\n".into()), "URL"),
        ];
        for (mutate, why) in cases {
            let mut p = pin();
            mutate(&mut p);
            let err = validate_values(&p).expect_err(why);
            assert!(err.contains(why), "{why}: {err}");
        }
    }

    #[test]
    fn suffixed_version_matches_the_maven_rule() {
        assert_eq!(suffixed_version("3.11", UUID), "3.11-socket.abcdef12");
        assert_eq!(
            pin().repo_path("jar"),
            "org/apache/commons/commons-lang3/3.11-socket.abcdef12/commons-lang3-3.11-socket.abcdef12.jar"
        );
        assert_eq!(SbtFileMode::Hosted.file(), HOSTED_FILE);
        assert_eq!(SbtFileMode::Vendored.repo_rel(), VENDORED_REPO_REL);
    }
}
