//! Go `setup` support: wire a project's fail-closed patch guard.
//!
//! Go has **no build hook** (no `build.rs` equivalent), so — unlike cargo, whose
//! guard rides in via a build-dependency — the gate is delivered as committed
//! source the user's own toolchain runs:
//!
//!   * `internal/socketpatchguard/{guard.go,guard_test.go}` — a generated
//!     package whose `TestSocketPatchesApplied` is the CI gate (`go test ./...`)
//!     and whose `init()` guards `go run` / a binary launched from the module
//!     tree. Both delegate to `socket-patch apply --check` / `apply` (the same
//!     fail-closed, self-healing contract as the cargo build-script guard).
//!   * `socket_patch_guard_import.go` in each `package main` directory — a tiny
//!     generated file that blank-imports the guard so its `init()` fires. A
//!     *separate generated file* (never an edit to the user's sources) keeps
//!     setup non-destructive and removal exact.
//!
//! The actual `replace` redirects + copies are materialised by `apply`
//! (`crate::patch::go_redirect`), triggered by `setup` and re-checked by the
//! guard — this module only manages the guard wiring.

use std::path::{Path, PathBuf};

use tokio::fs;

use crate::crawlers::go_crawler::parse_go_mod_module;

/// The in-module guard package directory (forward-slashed; `internal/` so only
/// the owning module can import it).
pub const GUARD_DIR: &str = "internal/socketpatchguard";
/// Generated blank-import file name dropped into each `package main` dir.
pub const IMPORT_FILE: &str = "socket_patch_guard_import.go";
/// First line of every generated file — the ownership signal for removal (we
/// never delete a file lacking it).
pub const GENERATED_MARKER: &str = "// Code generated by `socket-patch setup`. DO NOT EDIT.";

/// `guard.go` — the runtime/CI guard logic (static; the package needs no
/// knowledge of the module path).
pub const GUARD_GO: &str = include_str!("templates/guard.go.tmpl");
/// `guard_test.go` — the `go test ./...` gate.
pub const GUARD_TEST: &str = include_str!("templates/guard_test.go.tmpl");

/// The blank-import file body for a `package main` dir.
pub fn main_import_source(module_path: &str) -> String {
    format!(
        "{GENERATED_MARKER}\npackage main\n\nimport _ \"{module_path}/internal/socketpatchguard\"\n"
    )
}

/// A Go module path safe to interpolate into a generated `import` string:
/// non-empty, no whitespace / quotes / backslash / control characters. (Go's
/// own module-path grammar is stricter, but this is enough to bar injection /
/// a syntactically broken generated file.)
fn is_safe_module_path(p: &str) -> bool {
    !p.is_empty()
        && p.chars().all(|c| {
            !c.is_whitespace() && !c.is_control() && c != '"' && c != '\'' && c != '\\' && c != '`'
        })
}

/// A discovered Go module.
#[derive(Debug, Clone)]
pub struct GoModule {
    /// Directory containing `go.mod` (the project root).
    pub root: PathBuf,
    /// The module path from the `module` directive (e.g. `example.com/app`).
    pub module_path: String,
}

/// Find the Go module that `cwd` belongs to by walking up to the nearest
/// `go.mod`. Returns `None` if there is none, or if its `module` directive is
/// missing/malformed (we cannot form the guard import path without it).
pub async fn discover_go_module(cwd: &Path) -> Option<GoModule> {
    let mut dir = cwd.to_path_buf();
    loop {
        let candidate = dir.join("go.mod");
        if let Ok(content) = fs::read_to_string(&candidate).await {
            let module_path = parse_go_mod_module(&content)?;
            // Defense-in-depth: the path is interpolated verbatim into a Go
            // `import _ "<path>/internal/socketpatchguard"` string. Real module
            // paths never contain whitespace/quotes/control chars; reject a
            // hostile/malformed one rather than emit a broken (or injected)
            // import file. A valid `go.mod` always passes this.
            if !is_safe_module_path(&module_path) {
                return None;
            }
            return Some(GoModule {
                root: dir,
                module_path,
            });
        }
        dir = dir.parent()?.to_path_buf();
    }
}

/// Status of a single guard-wiring edit (mirrors cargo's `CargoSetupStatus`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GoSetupStatus {
    Updated,
    AlreadyConfigured,
    Error,
}

/// Result of one guard-wiring edit.
#[derive(Debug, Clone)]
pub struct GoEditResult {
    /// Envelope `files[].kind` (`go_guard` | `go_import`).
    pub kind: &'static str,
    pub path: String,
    pub status: GoSetupStatus,
    pub error: Option<String>,
}

// ── guard package (internal/socketpatchguard) ────────────────────────────────

fn guard_go_path(root: &Path) -> PathBuf {
    root.join(GUARD_DIR).join("guard.go")
}
fn guard_test_path(root: &Path) -> PathBuf {
    root.join(GUARD_DIR).join("guard_test.go")
}

/// Whether both guard files exist (the `setup --check` "configured" signal).
pub async fn guard_files_present(root: &Path) -> bool {
    fs::metadata(guard_go_path(root)).await.is_ok()
        && fs::metadata(guard_test_path(root)).await.is_ok()
}

/// Write `internal/socketpatchguard/{guard.go,guard_test.go}` to their generated
/// content. Idempotent: `AlreadyConfigured` when both already match.
pub async fn add_guard(root: &Path, dry_run: bool) -> GoEditResult {
    let dir = root.join(GUARD_DIR);
    let result = async {
        let go_changed = needs_write(&guard_go_path(root), GUARD_GO).await;
        let test_changed = needs_write(&guard_test_path(root), GUARD_TEST).await;
        if !go_changed && !test_changed {
            return Ok(false);
        }
        if !dry_run {
            fs::create_dir_all(&dir)
                .await
                .map_err(|e| format!("create {}: {e}", dir.display()))?;
            if go_changed {
                write_file(&guard_go_path(root), GUARD_GO).await?;
            }
            if test_changed {
                write_file(&guard_test_path(root), GUARD_TEST).await?;
            }
        }
        Ok(true)
    }
    .await;
    edit_result("go_guard", dir.display().to_string(), result)
}

/// Remove the guard package (both files + the now-empty `internal/` dirs).
pub async fn remove_guard(root: &Path, dry_run: bool) -> GoEditResult {
    let dir = root.join(GUARD_DIR);
    let result = async {
        let present = guard_files_present(root).await
            || fs::metadata(guard_go_path(root)).await.is_ok()
            || fs::metadata(guard_test_path(root)).await.is_ok();
        if !present {
            return Ok(false);
        }
        if !dry_run {
            let _ = fs::remove_file(guard_go_path(root)).await;
            let _ = fs::remove_file(guard_test_path(root)).await;
            // Prune now-empty internal/socketpatchguard and internal/.
            let _ = fs::remove_dir(&dir).await;
            let _ = fs::remove_dir(root.join("internal")).await;
        }
        Ok(true)
    }
    .await;
    edit_result("go_guard", dir.display().to_string(), result)
}

// ── main-package blank imports ────────────────────────────────────────────────

/// The generated blank-import file path for a `package main` directory.
pub fn import_file_path(main_dir: &Path) -> PathBuf {
    main_dir.join(IMPORT_FILE)
}

/// Add the blank-import file to every `package main` directory.
pub async fn add_main_imports(root: &Path, module_path: &str, dry_run: bool) -> Vec<GoEditResult> {
    let body = main_import_source(module_path);
    let mut out = Vec::new();
    for dir in find_main_package_dirs(root).await {
        let path = import_file_path(&dir);
        let result = async {
            if !needs_write(&path, &body).await {
                return Ok(false);
            }
            if !dry_run {
                write_file(&path, &body).await?;
            }
            Ok(true)
        }
        .await;
        out.push(edit_result("go_import", path.display().to_string(), result));
    }
    out
}

/// Remove the generated blank-import files (identified by the marker, so a
/// user's same-named file is never deleted) from every `package main` dir.
pub async fn remove_main_imports(root: &Path, dry_run: bool) -> Vec<GoEditResult> {
    let mut out = Vec::new();
    for dir in find_main_package_dirs(root).await {
        let path = import_file_path(&dir);
        match fs::read_to_string(&path).await {
            Ok(content) if content.starts_with(GENERATED_MARKER) => {
                let result = async {
                    if !dry_run {
                        fs::remove_file(&path)
                            .await
                            .map_err(|e| format!("remove {}: {e}", path.display()))?;
                    }
                    Ok(true)
                }
                .await;
                out.push(edit_result("go_import", path.display().to_string(), result));
            }
            // Absent, or a user-authored file with the same name — leave it.
            _ => {}
        }
    }
    out
}

/// Every `package main` directory under `root`, excluding `vendor/`, `.socket/`,
/// the guard dir, hidden / `_`-prefixed / `testdata` dirs (which the Go
/// toolchain itself ignores).
pub async fn find_main_package_dirs(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    find_main_dirs_inner(root, root, &mut out).await;
    out.sort();
    out
}

fn find_main_dirs_inner<'a>(
    root: &'a Path,
    dir: &'a Path,
    out: &'a mut Vec<PathBuf>,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = ()> + 'a>> {
    Box::pin(async move {
        let mut has_main = false;
        let mut subdirs: Vec<PathBuf> = Vec::new();
        let mut rd = match fs::read_dir(dir).await {
            Ok(rd) => rd,
            Err(_) => return,
        };
        while let Ok(Some(entry)) = rd.next_entry().await {
            let name = entry.file_name().to_string_lossy().to_string();
            let ft = match entry.file_type().await {
                Ok(ft) => ft,
                Err(_) => continue,
            };
            // `file_type()` does NOT traverse symlinks, so a symlinked dir is
            // reported as a symlink (is_dir() == false) and skipped here —
            // which also makes symlink loops (`cmd -> ..`) impossible to
            // recurse into. The explicit guard documents that invariant.
            if ft.is_symlink() {
                continue;
            }
            if ft.is_dir() {
                if is_skipped_dir(&name) {
                    continue;
                }
                subdirs.push(entry.path());
            } else if ft.is_file()
                && name.ends_with(".go")
                && !name.ends_with("_test.go")
                && !is_skipped_go_file(&name)
                && file_is_package_main(&entry.path()).await
            {
                has_main = true;
            }
        }
        if has_main {
            out.push(dir.to_path_buf());
        }
        for sub in subdirs {
            // Never descend into the guard package dir.
            if sub == root.join(GUARD_DIR) {
                continue;
            }
            find_main_dirs_inner(root, &sub, out).await;
        }
    })
}

fn is_skipped_dir(name: &str) -> bool {
    name == "vendor"
        || name == ".socket"
        || name == "testdata"
        || name.starts_with('.')
        || name.starts_with('_')
}

/// True if the go tool itself ignores this `.go` file by name. Files whose names
/// begin with `.` or `_` are excluded from the build by `go/build` (the same
/// convention that hides `.`/`_`-prefixed directories). A `_gen.go` declaring
/// `package main` inside a library package must NOT make that dir look like a
/// main dir — doing so would drop a conflicting `package main` import file and
/// break the build (the file-level twin of the `//go:build ignore` guard).
fn is_skipped_go_file(name: &str) -> bool {
    name.starts_with('.') || name.starts_with('_')
}

/// True if a `.go` file's package clause is `package main` AND the file is not
/// excluded from the build by an `ignore` build constraint. The `ignore` tag is
/// the conventional marker for files the toolchain never compiles (e.g. `go run
/// gen.go` generators), which commonly declare `package main` while living in a
/// directory whose real package is something else — counting them would make us
/// drop a `package main` import file into a non-main package and break the build.
async fn file_is_package_main(path: &Path) -> bool {
    let Ok(content) = fs::read_to_string(path).await else {
        return false;
    };
    // Go permits a leading UTF-8 BOM (U+FEFF) as the first code point of a source
    // file. Strip it before parsing, or the package clause would read as the
    // token `"\u{feff}package"` and a real `main` package would be missed — a
    // fail-open: the dir gets no guard import.
    let content = content.strip_prefix('\u{feff}').unwrap_or(&content);
    if has_ignore_build_tag(content) {
        return false;
    }
    // The package clause is the first non-blank, non-comment line. Strip BOTH
    // comment forms first: a `//`-line comment alone is not enough, because a
    // library file's doc/example block comment can contain a line that reads
    // `package main` (`/* … package main … */`). Counting that would drop a
    // `package main` import file into a non-main dir and break the build with
    // two conflicting package clauses. We also must stop AT the package clause,
    // not scan the whole file, for the same reason.
    let cleaned = strip_go_comments(content);
    for line in cleaned.lines() {
        let t = line.trim();
        if t.is_empty() {
            continue;
        }
        // First code line: it is the package clause. `package` + name, any
        // amount of whitespace between (gofmt uses one space, but a tab or
        // extra spaces are still valid Go and must not be a false negative).
        let mut toks = t.split_whitespace();
        return toks.next() == Some("package")
            && toks.next() == Some("main")
            && toks.next().is_none();
    }
    false
}

/// Strip Go `//` line comments and `/* … */` block comments from `src`,
/// preserving newlines so line structure survives. Used only to locate the
/// package clause, which precedes any string literals, so no string-literal
/// awareness is needed. Block comments do not nest in Go.
fn strip_go_comments(src: &str) -> String {
    let bytes = src.as_bytes();
    let mut out = String::with_capacity(src.len());
    let mut i = 0;
    // 0 = code, 1 = line comment (to EOL), 2 = block comment (to `*/`).
    let mut state = 0u8;
    while i < bytes.len() {
        let c = bytes[i];
        let next = bytes.get(i + 1).copied();
        match state {
            1 => {
                if c == b'\n' {
                    state = 0;
                    out.push('\n');
                }
                i += 1;
            }
            2 => {
                if c == b'*' && next == Some(b'/') {
                    state = 0;
                    i += 2;
                } else {
                    if c == b'\n' {
                        out.push('\n');
                    }
                    i += 1;
                }
            }
            _ => {
                if c == b'/' && next == Some(b'/') {
                    state = 1;
                    i += 2;
                } else if c == b'/' && next == Some(b'*') {
                    state = 2;
                    i += 2;
                } else {
                    // Preserve the byte. The package clause is ASCII; only
                    // pre-package code (none) or the clause itself reaches here.
                    out.push(c as char);
                    i += 1;
                }
            }
        }
    }
    out
}

/// True if the file's build-constraint header carries the `ignore` tag (either
/// `//go:build ignore` form or a `// +build ... ignore` line). Constraints must
/// precede the package clause, so scanning stops at the first non-comment line.
fn has_ignore_build_tag(content: &str) -> bool {
    for line in content.lines() {
        let t = line.trim();
        if t.is_empty() {
            continue;
        }
        if let Some(expr) = t.strip_prefix("//go:build ") {
            // `ignore` as a build term is never satisfied → file excluded.
            if expr.split(|c: char| !(c.is_alphanumeric() || c == '_' || c == '.'))
                .any(|tok| tok == "ignore")
            {
                return true;
            }
        } else if let Some(rest) = t.strip_prefix("// +build ") {
            if rest.split_whitespace().any(|tok| tok == "ignore") {
                return true;
            }
        } else if !t.starts_with("//") {
            break; // reached real code; constraints (if any) are all above
        }
    }
    false
}

// ── helpers ──────────────────────────────────────────────────────────────────

/// True if the file is absent or its content differs from `desired`.
async fn needs_write(path: &Path, desired: &str) -> bool {
    match fs::read_to_string(path).await {
        Ok(c) => c != desired,
        Err(_) => true,
    }
}

async fn write_file(path: &Path, body: &str) -> Result<(), String> {
    if let Some(p) = path.parent() {
        fs::create_dir_all(p)
            .await
            .map_err(|e| format!("create {}: {e}", p.display()))?;
    }
    fs::write(path, body)
        .await
        .map_err(|e| format!("write {}: {e}", path.display()))
}

fn edit_result(kind: &'static str, path: String, result: Result<bool, String>) -> GoEditResult {
    match result {
        Ok(true) => GoEditResult {
            kind,
            path,
            status: GoSetupStatus::Updated,
            error: None,
        },
        Ok(false) => GoEditResult {
            kind,
            path,
            status: GoSetupStatus::AlreadyConfigured,
            error: None,
        },
        Err(e) => GoEditResult {
            kind,
            path,
            status: GoSetupStatus::Error,
            error: Some(e),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    async fn write(path: &Path, body: &str) {
        if let Some(p) = path.parent() {
            fs::create_dir_all(p).await.unwrap();
        }
        fs::write(path, body).await.unwrap();
    }

    #[tokio::test]
    async fn test_discover_module_walks_up() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        let sub = root.join("cmd/server");
        fs::create_dir_all(&sub).await.unwrap();
        let m = discover_go_module(&sub).await.unwrap();
        assert_eq!(m.root, root);
        assert_eq!(m.module_path, "example.com/app");
    }

    #[tokio::test]
    async fn test_discover_none_without_go_mod() {
        let dir = tempfile::tempdir().unwrap();
        assert!(discover_go_module(dir.path()).await.is_none());
    }

    #[test]
    fn test_main_import_source() {
        let s = main_import_source("example.com/app");
        assert!(s.starts_with(GENERATED_MARKER));
        assert!(s.contains("package main"));
        assert!(s.contains("import _ \"example.com/app/internal/socketpatchguard\""));
    }

    #[test]
    fn test_guard_templates_are_socketpatchguard_package() {
        // Structural pins: catch corruption of the load-bearing control flow,
        // not just the package name.
        assert!(GUARD_GO.contains("package socketpatchguard"));
        assert!(GUARD_GO.contains("func init()"));
        assert!(GUARD_GO.contains("func check() (string, bool)"));
        assert!(GUARD_GO.contains("func moduleRoot() string"));
        // The probe + heal must use the read-only check and the golang scope.
        assert!(GUARD_GO.contains("\"apply\", \"--check\", \"--offline\", \"--ecosystems\", \"golang\""));
        assert!(GUARD_GO.contains("\"apply\", \"--offline\", \"--ecosystems\", \"golang\""));
        // Fail-closed primitives.
        assert!(GUARD_GO.contains("panic(msg)"));
        assert!(GUARD_GO.contains("manifest.json"), "must gate on a socket manifest");
        assert!(GUARD_TEST.contains("package socketpatchguard"));
        assert!(GUARD_TEST.contains("func TestSocketPatchesApplied"));
        assert!(GUARD_TEST.contains("t.Fatal(msg)"));
    }

    #[test]
    fn test_is_safe_module_path() {
        assert!(is_safe_module_path("github.com/foo/bar"));
        assert!(is_safe_module_path("example.com/x/v2"));
        assert!(!is_safe_module_path(""));
        assert!(!is_safe_module_path("foo bar")); // whitespace
        assert!(!is_safe_module_path("foo\"bar")); // quote (import-string injection)
        assert!(!is_safe_module_path("foo\nimport evil")); // newline
        assert!(!is_safe_module_path("foo\\bar"));
    }

    #[tokio::test]
    async fn test_discover_rejects_unsafe_module_path() {
        let dir = tempfile::tempdir().unwrap();
        // A go.mod whose module directive carries a quote would inject into the
        // generated import string — must be rejected.
        write(&dir.path().join("go.mod"), "module \"ev\\\"il\"\n\ngo 1.21\n").await;
        assert!(discover_go_module(dir.path()).await.is_none());
    }

    #[tokio::test]
    async fn test_ignore_tagged_main_file_is_not_a_main_dir() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        // A real library package dir that also holds a `go run`-style generator
        // tagged `//go:build ignore` with `package main`. Go excludes the
        // generator from the build, so this dir's package is `lib`, NOT main —
        // we must not drop a `package main` import file here.
        write(&root.join("pkg/lib.go"), "package lib\n").await;
        write(
            &root.join("pkg/gen.go"),
            "//go:build ignore\n\npackage main\n\nfunc main() {}\n",
        )
        .await;
        // Legacy `// +build ignore` form too.
        write(&root.join("tool/tool.go"), "package tool\n").await;
        write(
            &root.join("tool/gen2.go"),
            "// +build ignore\n\npackage main\n\nfunc main() {}\n",
        )
        .await;

        let dirs = find_main_package_dirs(root).await;
        assert!(
            !dirs.contains(&root.join("pkg")),
            "ignore-tagged generator must not make pkg/ a main dir: {dirs:?}"
        );
        assert!(
            !dirs.contains(&root.join("tool")),
            "+build ignore generator must not make tool/ a main dir"
        );
    }

    #[tokio::test]
    async fn test_underscore_and_dot_prefixed_main_file_is_not_a_main_dir() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        // A real library package dir that also holds `_`/`.`-prefixed files that
        // declare `package main`. The go tool IGNORES files whose names begin
        // with `.` or `_`, so this dir's package is `lib`, NOT main — we must not
        // drop a `package main` import file here (it would conflict and break the
        // build). Twin of the `//go:build ignore` exclusion.
        write(&root.join("pkg/lib.go"), "package lib\n").await;
        write(
            &root.join("pkg/_gen.go"),
            "package main\n\nfunc main() {}\n",
        )
        .await;
        write(
            &root.join("pkg/.hidden.go"),
            "package main\n\nfunc main() {}\n",
        )
        .await;

        let dirs = find_main_package_dirs(root).await;
        assert!(
            !dirs.contains(&root.join("pkg")),
            "`_`/`.`-prefixed main file must not make pkg/ a main dir: {dirs:?}"
        );
    }

    #[tokio::test]
    async fn test_bom_prefixed_main_file_is_detected() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        // Go permits a leading UTF-8 BOM. A real `package main` file that starts
        // with one must still be detected — a false negative is fail-open (the
        // guard import is never wired for this binary).
        write(
            &root.join("cmd/app/main.go"),
            "\u{feff}package main\n\nfunc main() {}\n",
        )
        .await;
        let dirs = find_main_package_dirs(root).await;
        assert!(
            dirs.contains(&root.join("cmd/app")),
            "BOM-prefixed `package main` must still be detected: {dirs:?}"
        );
    }

    #[test]
    fn test_is_skipped_go_file() {
        assert!(is_skipped_go_file("_gen.go"));
        assert!(is_skipped_go_file(".hidden.go"));
        assert!(!is_skipped_go_file("main.go"));
        assert!(!is_skipped_go_file("gen_main.go")); // underscore not at start
    }

    #[tokio::test]
    async fn test_block_comment_package_main_is_not_a_main_dir() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        // A library package whose doc comment shows an *example* `package main`
        // inside a /* … */ block. The real package clause is `lib`, so we must
        // NOT treat this dir as main (doing so drops a conflicting `package
        // main` import file and breaks the build).
        write(
            &root.join("pkg/doc.go"),
            "/*\nPackage lib is great.\n\nExample:\n\n\tpackage main\n\n\tfunc main() {}\n*/\npackage lib\n",
        )
        .await;
        // Also a real main dir as a positive control.
        write(&root.join("main.go"), "package main\n\nfunc main() {}\n").await;

        let dirs = find_main_package_dirs(root).await;
        assert!(
            !dirs.contains(&root.join("pkg")),
            "block-comment example `package main` must not make pkg/ a main dir: {dirs:?}"
        );
        assert!(dirs.contains(&root.to_path_buf()), "real main dir still found");
    }

    #[tokio::test]
    async fn test_package_main_with_irregular_whitespace_is_detected() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        // Valid Go: a tab / multiple spaces between `package` and `main`. Must
        // still be detected (a false negative here is fail-open: no guard).
        write(&root.join("cmd/a/main.go"), "package\tmain\n\nfunc main() {}\n").await;
        write(&root.join("cmd/b/main.go"), "package   main\n\nfunc main() {}\n").await;

        let dirs = find_main_package_dirs(root).await;
        assert!(dirs.contains(&root.join("cmd/a")), "tab-separated clause detected: {dirs:?}");
        assert!(dirs.contains(&root.join("cmd/b")), "multi-space clause detected: {dirs:?}");
    }

    #[tokio::test]
    async fn test_trailing_block_comment_package_main_after_clause_ignored() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        // The real clause is `lib`; a later block comment mentions `package
        // main`. Scanning must stop at the (first) clause, not keep going.
        write(
            &root.join("pkg/x.go"),
            "package lib\n\n/* historical note:\npackage main\n*/\n\nfunc Do() {}\n",
        )
        .await;
        let dirs = find_main_package_dirs(root).await;
        assert!(!dirs.contains(&root.join("pkg")), "trailing block comment must not matter: {dirs:?}");
    }

    #[test]
    fn test_strip_go_comments() {
        assert_eq!(strip_go_comments("package main // hi\n").trim(), "package main");
        assert_eq!(strip_go_comments("/* a */package lib\n").trim(), "package lib");
        // Block comment content is removed but newlines are preserved.
        let cleaned = strip_go_comments("/*\npackage main\n*/\npackage lib\n");
        let first = cleaned.lines().map(str::trim).find(|l| !l.is_empty());
        assert_eq!(first, Some("package lib"));
    }

    #[tokio::test]
    async fn test_find_main_dirs_terminates_on_symlink_loop() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        write(&root.join("main.go"), "package main\n\nfunc main() {}\n").await;
        std::fs::create_dir_all(root.join("sub")).unwrap();
        // A symlink loop: sub/loop -> .. (the module root). Must not recurse
        // forever / overflow the stack.
        #[cfg(unix)]
        std::os::unix::fs::symlink(root, root.join("sub/loop")).unwrap();

        // Completes (does not hang/overflow) and finds the real main dir.
        let dirs = find_main_package_dirs(root).await;
        assert!(dirs.contains(&root.to_path_buf()));
    }

    #[tokio::test]
    async fn test_add_then_remove_guard_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let r = add_guard(root, false).await;
        assert_eq!(r.status, GoSetupStatus::Updated);
        assert!(guard_files_present(root).await);
        assert_eq!(
            fs::read_to_string(guard_go_path(root)).await.unwrap(),
            GUARD_GO
        );
        // Idempotent.
        assert_eq!(add_guard(root, false).await.status, GoSetupStatus::AlreadyConfigured);
        // Remove.
        let rr = remove_guard(root, false).await;
        assert_eq!(rr.status, GoSetupStatus::Updated);
        assert!(!guard_files_present(root).await);
        assert!(!root.join("internal").exists(), "empty internal/ pruned");
        // Remove again → not_configured.
        assert_eq!(remove_guard(root, false).await.status, GoSetupStatus::AlreadyConfigured);
    }

    #[tokio::test]
    async fn test_add_guard_dry_run_writes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let r = add_guard(root, true).await;
        assert_eq!(r.status, GoSetupStatus::Updated, "dry-run reports the change");
        assert!(!guard_files_present(root).await, "dry-run wrote nothing");
    }

    #[tokio::test]
    async fn test_find_main_dirs_and_imports() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("go.mod"), "module example.com/app\n\ngo 1.21\n").await;
        // A main package at cmd/server.
        write(&root.join("cmd/server/main.go"), "package main\n\nfunc main() {}\n").await;
        // A library package (not main) — must be ignored.
        write(&root.join("pkg/lib/lib.go"), "package lib\n").await;
        // A main package at root.
        write(&root.join("main.go"), "package main\n\nfunc main() {}\n").await;
        // vendored main — must be ignored.
        write(&root.join("vendor/x/cmd/main.go"), "package main\n\nfunc main() {}\n").await;

        let dirs = find_main_package_dirs(root).await;
        assert!(dirs.contains(&root.to_path_buf()));
        assert!(dirs.contains(&root.join("cmd/server")));
        assert!(!dirs.iter().any(|d| d.starts_with(root.join("vendor"))));
        assert!(!dirs.contains(&root.join("pkg/lib")));

        // Add imports → one per main dir.
        let added = add_main_imports(root, "example.com/app", false).await;
        assert_eq!(added.len(), 2);
        assert!(added.iter().all(|r| r.status == GoSetupStatus::Updated));
        let import_body = fs::read_to_string(import_file_path(&root.join("cmd/server")))
            .await
            .unwrap();
        assert!(import_body.contains("import _ \"example.com/app/internal/socketpatchguard\""));

        // Idempotent.
        assert!(add_main_imports(root, "example.com/app", false)
            .await
            .iter()
            .all(|r| r.status == GoSetupStatus::AlreadyConfigured));

        // Remove only marker-bearing files.
        let removed = remove_main_imports(root, false).await;
        assert_eq!(removed.len(), 2);
        assert!(!import_file_path(&root.join("cmd/server")).exists());
    }

    #[tokio::test]
    async fn test_remove_main_imports_spares_user_file() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(&root.join("main.go"), "package main\n\nfunc main() {}\n").await;
        // A user file at the generated name WITHOUT our marker.
        write(&import_file_path(root), "package main\n\n// mine\n").await;
        let removed = remove_main_imports(root, false).await;
        assert!(removed.is_empty(), "user file must not be removed");
        assert!(import_file_path(root).exists());
    }
}
